Libevhtp: evhtp_numtoa.c File Reference
evhtp_numtoa.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "evhtp-internal.h"
#include "evhtp_numtoa.h"
Functions
static void strreverse (char *begin, char *end)
size_t evhtp_modp_u64toa (uint64_t value, char *str)
convert uint64_t value to a string
size_t evhtp_modp_u32toa (uint32_t value, char *str)
converts uint32_t value to string
size_t evhtp_modp_sizetoa (size_t value, char *str)
based on the system architecture, convert a size_t number to a string.
Function Documentation
static void strreverse (char * begin, char * end) inline static
Referenced by evhtp_modp_u32toa(), and evhtp_modp_u64toa().
{
     char aux;
     while (end > begin) {
         aux = *end, *end-- = *begin, *begin++ = aux;
     }
 }
size_t evhtp_modp_u64toa (uint64_t value, char * str)
convert uint64_t value to a string
Parameters
value input value
str output buffer, should be 24 chars or more
Returns
References strreverse().
Referenced by evhtp_modp_sizetoa().
{
     char * wstr = str;
     /* Conversion. Number is reversed. */
     do {
         *wstr++ = (char)(48 + (value % 10));
     } while (value /= 10);
     *wstr = '\0';
     /* Reverse string */
     strreverse(str, wstr - 1);
     return (size_t)(wstr - str);
 }
size_t evhtp_modp_u32toa (uint32_t value, char * str)
converts uint32_t value to string
Parameters
value input value
str output buffer, should be 16 chars or more
Returns
References strreverse().
Referenced by _evhtp_create_reply(), and evhtp_modp_sizetoa().
{
     char * wstr = str;
     /* Conversion. Number is reversed. */
     do {
         *wstr++ = (char)(48 + (value % 10));
     } while (value /= 10);
     *wstr = '\0';
     /* Reverse string */
     strreverse(str, wstr - 1);
     return (size_t)(wstr - str);
 }
size_t evhtp_modp_sizetoa (size_t value, char * str) inline
based on the system architecture, convert a size_t number to a string.
Parameters
value the input value
str The output buffer, should be 24 chars or more.
Returns
References evhtp_modp_u32toa(), and evhtp_modp_u64toa().
Referenced by _evhtp_create_reply().
{
 #if EVHTP_SYS_ARCH == 64
     return evhtp_modp_u64toa(value, str);
 #elif EVHTP_SYS_ARCH == 32
     return evhtp_modp_u32toa(value, str);
 #else
 #warn "UNKNOWN ARCH"
 #endif
 }