Libevhtp: evhtp.h File Reference
evhtp.h File Reference
#include <evhtp-config.h>
#include <evthr.h>
#include <htparse.h>
#include <onigposix.h>
#include <sys/queue.h>
#include <event2/event.h>
#include <event2/listener.h>
#include <event2/buffer.h>
#include <event2/bufferevent.h>
#include <event2/bufferevent_ssl.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/rand.h>
Classes
struct evhtp_defaults_5
struct evhtp_alias_t
struct evhtp_t
main structure containing all configuration information
struct evhtp_callback_t
structure containing a single callback and configuration
struct evhtp_kv_t
a generic key/value structure
struct evhtp_uri_t
a generic container representing an entire URI strucutre
struct evhtp_authority_t
structure which represents authority information in a URI
struct evhtp_path_t
structure which represents a URI path and or file
struct evhtp_request_t
a structure containing all information for a http request.
struct evhtp_connection_t
struct evhtp_hooks_t
struct evhtp_ssl_cfg_t
Macros
#define htp_debug_strlen(x) 0
#define htp_log_debug(fmt, ...) do {} while (0)
#define evhtp_header_s evhtp_kv_s
#define evhtp_headers_s evhtp_kvs_s
#define evhtp_query_s evhtp_kvs_s
#define evhtp_header_t evhtp_kv_t
#define evhtp_headers_t evhtp_kvs_t
#define evhtp_query_t evhtp_kvs_t
#define EVHTP_VERSION "1.2.11"
#define EVHTP_VERSION_MAJOR 1
#define EVHTP_VERSION_MINOR 2
#define EVHTP_VERSION_PATCH 11
#define evhtp_headers_iterator evhtp_kvs_iterator
#define EVHTP_RES_ERROR 0
#define EVHTP_RES_PAUSE 1
#define EVHTP_RES_FATAL 2
#define EVHTP_RES_USER 3
#define EVHTP_RES_DATA_TOO_LONG 4
#define EVHTP_RES_OK 200
#define EVHTP_RES_100 100
#define EVHTP_RES_CONTINUE 100
#define EVHTP_RES_SWITCH_PROTO 101
#define EVHTP_RES_PROCESSING 102
#define EVHTP_RES_URI_TOOLONG 122
#define EVHTP_RES_200 200
#define EVHTP_RES_CREATED 201
#define EVHTP_RES_ACCEPTED 202
#define EVHTP_RES_NAUTHINFO 203
#define EVHTP_RES_NOCONTENT 204
#define EVHTP_RES_RSTCONTENT 205
#define EVHTP_RES_PARTIAL 206
#define EVHTP_RES_MSTATUS 207
#define EVHTP_RES_IMUSED 226
#define EVHTP_RES_300 300
#define EVHTP_RES_MCHOICE 300
#define EVHTP_RES_MOVEDPERM 301
#define EVHTP_RES_FOUND 302
#define EVHTP_RES_SEEOTHER 303
#define EVHTP_RES_NOTMOD 304
#define EVHTP_RES_USEPROXY 305
#define EVHTP_RES_SWITCHPROXY 306
#define EVHTP_RES_TMPREDIR 307
#define EVHTP_RES_400 400
#define EVHTP_RES_BADREQ 400
#define EVHTP_RES_UNAUTH 401
#define EVHTP_RES_PAYREQ 402
#define EVHTP_RES_FORBIDDEN 403
#define EVHTP_RES_NOTFOUND 404
#define EVHTP_RES_METHNALLOWED 405
#define EVHTP_RES_NACCEPTABLE 406
#define EVHTP_RES_PROXYAUTHREQ 407
#define EVHTP_RES_TIMEOUT 408
#define EVHTP_RES_CONFLICT 409
#define EVHTP_RES_GONE 410
#define EVHTP_RES_LENREQ 411
#define EVHTP_RES_PRECONDFAIL 412
#define EVHTP_RES_ENTOOLARGE 413
#define EVHTP_RES_URITOOLARGE 414
#define EVHTP_RES_UNSUPPORTED 415
#define EVHTP_RES_RANGENOTSC 416
#define EVHTP_RES_EXPECTFAIL 417
#define EVHTP_RES_IAMATEAPOT 418
#define EVHTP_RES_500 500
#define EVHTP_RES_SERVERR 500
#define EVHTP_RES_NOTIMPL 501
#define EVHTP_RES_BADGATEWAY 502
#define EVHTP_RES_SERVUNAVAIL 503
#define EVHTP_RES_GWTIMEOUT 504
#define EVHTP_RES_VERNSUPPORT 505
#define EVHTP_RES_BWEXEED 509
#define thread_init_cbarg thread_cbarg
#define evhtp_request_content_len(r) htparser_get_content_length(r->conn->parser)
#define EVHTP_PARSE_QUERY_FLAG_STRICT 0
#define EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX (1 << 0)
#define EVHTP_PARSE_QUERY_FLAG_ALLOW_EMPTY_VALS (1 << 1)
#define EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS (1 << 2)
#define EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP (1 << 3)
#define EVHTP_PARSE_QUERY_FLAG_IGNORE_FRAGMENTS (1 << 4)
#define EVHTP_PARSE_QUERY_FLAG_LENIENT
#define evhtp_header_find evhtp_kv_find
#define evhtp_headers_find_header evhtp_kvs_find_kv
#define evhtp_headers_for_each evhtp_kvs_for_each
#define evhtp_header_new evhtp_kv_new
#define evhtp_header_free evhtp_kv_free
#define evhtp_headers_new evhtp_kvs_new
#define evhtp_headers_free evhtp_kvs_free
#define evhtp_header_rm_and_free evhtp_kv_rm_and_free
#define evhtp_headers_add_header evhtp_kvs_add_kv
#define evhtp_headers_add_headers evhtp_kvs_add_kvs
#define evhtp_query_new evhtp_kvs_new
#define evhtp_query_free evhtp_kvs_free
Typedefs
typedef SSL_SESSION evhtp_ssl_sess_t
typedef SSL evhtp_ssl_t
typedef SSL_CTX evhtp_ssl_ctx_t
typedef X509 evhtp_x509_t
typedef X509_STORE_CTX evhtp_x509_store_ctx_t
typedef struct evbuffer evbuf_t
typedef struct event event_t
typedef struct evconnlistener evserv_t
typedef struct bufferevent evbev_t
typedef pthread_mutex_t evhtp_mutex_t
typedef struct evhtp_callbacks_s evhtp_callbacks_t
typedef struct evhtp_kvs_s evhtp_kvs_t
typedef uint16_t evhtp_res
typedef uint8_t evhtp_error_flags
typedef enum evhtp_hook_type evhtp_hook_type
typedef enum evhtp_callback_type evhtp_callback_type
typedef enum evhtp_proto evhtp_proto
typedef enum evhtp_ssl_scache_type evhtp_ssl_scache_type
typedef enum evhtp_type evhtp_type
typedef void(* evhtp_thread_init_cb) (evhtp_t *htp, evthr_t *thr, void *arg)
typedef void(* evhtp_thread_exit_cb) (evhtp_t *htp, evthr_t *thr, void *arg)
typedef void(* evhtp_callback_cb) (evhtp_request_t *req, void *arg)
typedef void(* evhtp_hook_err_cb) (evhtp_request_t *req, evhtp_error_flags errtype, void *arg)
typedef void(* evhtp_hook_event_cb) (evhtp_connection_t *conn, short events, void *arg)
typedef evhtp_res(* evhtp_hook) ()
typedef evhtp_res(* evhtp_hook_conn_err_cb) (evhtp_connection_t *connection, evhtp_error_flags errtype, void *arg)
typedef evhtp_res(* evhtp_pre_accept_cb) (evhtp_connection_t *conn, void *arg)
typedef evhtp_res(* evhtp_post_accept_cb) (evhtp_connection_t *conn, void *arg)
typedef evhtp_res(* evhtp_hook_header_cb) (evhtp_request_t *req, evhtp_header_t *hdr, void *arg)
typedef evhtp_res(* evhtp_hook_headers_cb) (evhtp_request_t *req, evhtp_headers_t *hdr, void *arg)
typedef evhtp_res(* evhtp_hook_path_cb) (evhtp_request_t *req, evhtp_path_t *path, void *arg)
typedef evhtp_res(* evhtp_hook_read_cb) (evhtp_request_t *req, evbuf_t *buf, void *arg)
typedef evhtp_res(* evhtp_hook_request_fini_cb) (evhtp_request_t *req, void *arg)
typedef evhtp_res(* evhtp_hook_connection_fini_cb) (evhtp_connection_t *connection, void *arg)
typedef evhtp_res(* evhtp_hook_chunk_new_cb) (evhtp_request_t *r, uint64_t len, void *arg)
typedef evhtp_res(* evhtp_hook_chunk_fini_cb) (evhtp_request_t *r, void *arg)
typedef evhtp_res(* evhtp_hook_chunks_fini_cb) (evhtp_request_t *r, void *arg)
typedef evhtp_res(* evhtp_hook_headers_start_cb) (evhtp_request_t *r, void *arg)
typedef evhtp_res(* evhtp_hook_hostname_cb) (evhtp_request_t *r, const char *hostname, void *arg)
typedef evhtp_res(* evhtp_hook_write_cb) (evhtp_connection_t *conn, void *arg)
typedef int(* evhtp_kvs_iterator) (evhtp_kv_t *kv, void *arg)
typedef int(* evhtp_headers_iterator) (evhtp_header_t *header, void *arg)
typedef int(* evhtp_ssl_verify_cb) (int pre_verify, evhtp_x509_store_ctx_t *ctx)
typedef int(* evhtp_ssl_chk_issued_cb) (evhtp_x509_store_ctx_t *ctx, evhtp_x509_t *x, evhtp_x509_t *issuer)
typedef int(* evhtp_ssl_scache_add) (evhtp_connection_t *connection, unsigned char *sid, int sid_len, evhtp_ssl_sess_t *sess)
typedef void(* evhtp_ssl_scache_del) (evhtp_t *htp, unsigned char *sid, int sid_len)
typedef evhtp_ssl_sess_t *(* evhtp_ssl_scache_get) (evhtp_connection_t *connection, unsigned char *sid, int sid_len)
typedef void *(* evhtp_ssl_scache_init) (evhtp_t *)
Enumerations
enum evhtp_ssl_scache_type { evhtp_ssl_scache_type_disabled = 0, evhtp_ssl_scache_type_internal, evhtp_ssl_scache_type_user, evhtp_ssl_scache_type_builtin }
enum evhtp_hook_type {
evhtp_hook_on_header, evhtp_hook_on_headers, evhtp_hook_on_path, evhtp_hook_on_read,
evhtp_hook_on_request_fini, evhtp_hook_on_connection_fini, evhtp_hook_on_new_chunk, evhtp_hook_on_chunk_complete,
evhtp_hook_on_chunks_complete, evhtp_hook_on_headers_start, evhtp_hook_on_error, evhtp_hook_on_hostname,
evhtp_hook_on_write, evhtp_hook_on_event, evhtp_hook_on_conn_error
}
types associated with where a developer can hook into during the request processing cycle.
enum evhtp_callback_type { evhtp_callback_type_hash, evhtp_callback_type_glob, evhtp_callback_type_regex }
enum evhtp_proto { EVHTP_PROTO_INVALID, EVHTP_PROTO_10, EVHTP_PROTO_11 }
enum evhtp_type { evhtp_type_client, evhtp_type_server }
Functions
TAILQ_HEAD (evhtp_callbacks_s, evhtp_callback_s)
TAILQ_HEAD (evhtp_kvs_s, evhtp_kv_s)
EVHTP_EXPORT evhtp_t * evhtp_new (evbase_t *evbase, void *arg)
creates a new evhtp_t instance
EVHTP_EXPORT void evhtp_free (evhtp_t *evhtp)
EVHTP_EXPORT void evhtp_set_timeouts (evhtp_t *htp, const struct timeval *r, const struct timeval *w)
set a read/write timeout on all things evhtp_t. When the timeout expires your error hook will be called with the libevent supplied event flags.
EVHTP_EXPORT void evhtp_set_parser_flags (evhtp_t *htp, int flags)
during the request processing cycle, these flags will be used to for query argument parsing. i.e., what to parse and not to parse.
EVHTP_EXPORT void evhtp_set_bev_flags (evhtp_t *htp, int flags)
bufferevent flags which will be used for bev sockets.
EVHTP_EXPORT int evhtp_ssl_use_threads (void)
EVHTP_EXPORT int evhtp_ssl_init (evhtp_t *htp, evhtp_ssl_cfg_t *ssl_cfg)
EVHTP_EXPORT void evhtp_disable_100_continue (evhtp_t *htp)
when a client sends an Expect: 100-continue, if this is function is called, evhtp will not send a HTTP/x.x continue response.
EVHTP_EXPORT int evhtp_use_callback_locks (evhtp_t *htp)
creates a lock around callbacks and hooks, allowing for threaded applications to add/remove/modify hooks & callbacks in a thread-safe manner.
EVHTP_EXPORT void evhtp_set_gencb (evhtp_t *htp, evhtp_callback_cb cb, void *arg)
sets a callback which is called if no other callbacks are matched
EVHTP_EXPORT void evhtp_set_pre_accept_cb (evhtp_t *htp, evhtp_pre_accept_cb, void *arg)
call a user-defined function before the connection is accepted.
EVHTP_EXPORT void evhtp_set_post_accept_cb (evhtp_t *htp, evhtp_post_accept_cb, void *arg)
call a user-defined function right after a connection is accepted.
EVHTP_EXPORT evhtp_callback_t * evhtp_set_cb (evhtp_t *htp, const char *path, evhtp_callback_cb cb, void *arg)
sets a callback to be executed on a specific path
EVHTP_EXPORT evhtp_callback_t * evhtp_set_regex_cb (evhtp_t *htp, const char *pattern, evhtp_callback_cb cb, void *arg)
sets a callback to be executed based on a regex pattern
EVHTP_EXPORT evhtp_callback_t * evhtp_set_glob_cb (evhtp_t *htp, const char *pattern, evhtp_callback_cb cb, void *arg)
sets a callback to to be executed on simple glob/wildcard patterns this is useful if the app does not care about what was matched, but just that it matched. This is technically faster than regex.
EVHTP_EXPORT evhtp_callback_t * evhtp_get_cb (evhtp_t *htp, const char *needle)
attempts to find the callback matching the exact string 'needle'. This is useful in cases where we want to get the original handle, but is not in scope.
EVHTP_EXPORT int evhtp_set_hook (evhtp_hooks_t **hooks, evhtp_hook_type type, evhtp_hook cb, void *arg)
sets a callback hook for either a connection or a path/regex .
EVHTP_EXPORT int evhtp_unset_hook (evhtp_hooks_t **hooks, evhtp_hook_type type)
remove a specific hook from being called.
EVHTP_EXPORT int evhtp_unset_all_hooks (evhtp_hooks_t **hooks)
removes all hooks.
EVHTP_EXPORT int evhtp_bind_socket (evhtp_t *htp, const char *addr, uint16_t port, int backlog)
bind to a socket, optionally with specific protocol support formatting. The addr can be defined as one of the following: ipv6:<ipv6addr> for binding to an IPv6 address. unix:<named pipe>=""> for binding to a unix named socket ipv4:<ipv4addr> for binding to an ipv4 address Otherwise the addr is assumed to be ipv4.
EVHTP_EXPORT void evhtp_unbind_socket (evhtp_t *htp)
stops the listening socket.
EVHTP_EXPORT int evhtp_accept_socket (evhtp_t *htp, evutil_socket_t sock, int backlog)
create the listener plus setup various options with an already-bound socket.
EVHTP_EXPORT int evhtp_bind_sockaddr (evhtp_t *htp, struct sockaddr *, size_t sin_len, int backlog)
bind to an already allocated sockaddr.
EVHTP_EXPORT int evhtp_use_threads (evhtp_t *, evhtp_thread_init_cb, int nthreads, void *) DEPRECATED("will take on the syntax of evhtp_use_threads_wexit")
Enable thread-pool support for an evhtp_t context. Connectios are distributed across 'nthreads'. An optional "on-start" callback can be set which allows you to manipulate the thread-specific inforation (such as the thread-specific event_base).
EVHTP_EXPORT int evhtp_use_threads_wexit (evhtp_t *, evhtp_thread_init_cb, evhtp_thread_exit_cb, int nthreads, void *arg)
Temporary function which will be renamed evhtp_use_threads in the future. evhtp_use_threads() has been noted as deprecated for now.
EVHTP_EXPORT void evhtp_send_reply (evhtp_request_t *request, evhtp_res code)
generates all the right information for a reply to be sent to the client
EVHTP_EXPORT void evhtp_send_reply_start (evhtp_request_t *request, evhtp_res code)
EVHTP_EXPORT void evhtp_send_reply_body (evhtp_request_t *request, evbuf_t *buf)
EVHTP_EXPORT void evhtp_send_reply_end (evhtp_request_t *request)
EVHTP_EXPORT int evhtp_response_needs_body (const evhtp_res code, const htp_method method)
Determine if a response should have a body. Follows the rules in RFC 2616 section 4.3.
EVHTP_EXPORT void evhtp_send_reply_chunk_start (evhtp_request_t *request, evhtp_res code)
start a chunked response. If data already exists on the output buffer, this will be converted to the first chunk.
EVHTP_EXPORT void evhtp_send_reply_chunk (evhtp_request_t *request, evbuf_t *buf)
send a chunk reply.
EVHTP_EXPORT void evhtp_send_reply_chunk_end (evhtp_request_t *request)
call when all chunks have been sent and you wish to send the last bits. This will add the last 0CRLFCRCL and call send_reply_end().
EVHTP_EXPORT evhtp_callback_t * evhtp_callback_new (const char *path, evhtp_callback_type type, evhtp_callback_cb cb, void *arg)
creates a new evhtp_callback_t structure.
EVHTP_EXPORT void evhtp_callback_free (evhtp_callback_t *callback)
frees information associated with a ainflwx callback.
EVHTP_EXPORT int evhtp_callbacks_add_callback (evhtp_callbacks_t *cbs, evhtp_callback_t *cb)
Adds a evhtp_callback_t to the evhtp_callbacks_t list.
EVHTP_EXPORT int evhtp_add_vhost (evhtp_t *evhtp, const char *name, evhtp_t *vhost)
add an evhtp_t structure (with its own callbacks) to a base evhtp_t structure for virtual hosts. It should be noted that if you enable SSL on the base evhtp_t and your version of OpenSSL supports SNI, the SNI hostname will always take precedence over the Host header value.
EVHTP_EXPORT int evhtp_add_alias (evhtp_t *evhtp, const char *name)
Add an alias hostname for a virtual-host specific evhtp_t. This avoids having multiple evhtp_t virtual hosts with the same callback for the same vhost.
EVHTP_EXPORT evhtp_kv_t * evhtp_kv_new (const char *key, const char *val, char kalloc, char valloc)
Allocates a new key/value structure.
EVHTP_EXPORT evhtp_kvs_t * evhtp_kvs_new (void)
creates an empty list of key/values
EVHTP_EXPORT void evhtp_kv_free (evhtp_kv_t *kv)
frees resources allocated for a single key/value
EVHTP_EXPORT void evhtp_kvs_free (evhtp_kvs_t *kvs)
frees a the list of key/values, and all underlying entries
EVHTP_EXPORT void evhtp_kv_rm_and_free (evhtp_kvs_t *kvs, evhtp_kv_t *kv)
free's resources associated with 'kv' if ONLY found within the key/value list
EVHTP_EXPORT const char * evhtp_kv_find (evhtp_kvs_t *kvs, const char *key)
find the string value of 'key' from the key/value list 'kvs'
EVHTP_EXPORT evhtp_kv_t * evhtp_kvs_find_kv (evhtp_kvs_t *kvs, const char *key)
find the evhtp_kv_t reference 'key' from the k/val list 'kvs'
EVHTP_EXPORT void evhtp_kvs_add_kv (evhtp_kvs_t *kvs, evhtp_kv_t *kv)
appends a key/val structure to a evhtp_kvs_t tailq
EVHTP_EXPORT void evhtp_kvs_add_kvs (evhtp_kvs_t *dst, evhtp_kvs_t *src)
appends all key/val structures from src tailq onto dst tailq
EVHTP_EXPORT int evhtp_kvs_for_each (evhtp_kvs_t *kvs, evhtp_kvs_iterator cb, void *arg)
callback iterator which executes 'cb' for every entry in 'kvs'
EVHTP_EXPORT evhtp_query_t * evhtp_parse_query_wflags (const char *query, size_t len, int flags)
Parses the query portion of the uri into a set of key/values.
EVHTP_EXPORT evhtp_query_t * evhtp_parse_query (const char *query, size_t len)
Parses the query portion of the uri into a set of key/values in a strict manner.
EVHTP_EXPORT int evhtp_unescape_string (unsigned char **out, unsigned char *str, size_t str_len)
Unescapes strings like '%7B1,%202,%203%7D' would become '{1, 2, 3}'.
EVHTP_EXPORT evhtp_header_t * evhtp_header_new (const char *key, const char *val, char kalloc, char valloc)
creates a new evhtp_header_t key/val structure
EVHTP_EXPORT evhtp_header_t * evhtp_header_key_add (evhtp_headers_t *headers, const char *key, char kalloc)
creates a new evhtp_header_t, sets only the key, and adds to the evhtp_headers TAILQ
EVHTP_EXPORT evhtp_header_t * evhtp_header_val_add (evhtp_headers_t *headers, const char *val, char valloc)
finds the last header in the headers tailq and adds the value
EVHTP_EXPORT void evhtp_headers_add_header (evhtp_headers_t *headers, evhtp_header_t *header)
adds an evhtp_header_t to the end of the evhtp_headers_t tailq
EVHTP_EXPORT const char * evhtp_header_find (evhtp_headers_t *headers, const char *key)
finds the value of a key in a evhtp_headers_t structure
EVHTP_EXPORT htp_method evhtp_request_get_method (evhtp_request_t *r)
returns the htp_method enum version of the request method.
EVHTP_EXPORT evhtp_proto evhtp_request_get_proto (evhtp_request_t *r)
EVHTP_EXPORT void evhtp_connection_pause (evhtp_connection_t *connection)
pauses a connection (disables reading)
EVHTP_EXPORT void evhtp_connection_resume (evhtp_connection_t *connection)
resumes a connection (enables reading) and activates resume event.
EVHTP_EXPORT void evhtp_request_pause (evhtp_request_t *request)
Wrapper around evhtp_connection_pause.
EVHTP_EXPORT void evhtp_request_resume (evhtp_request_t *request)
Wrapper around evhtp_connection_resume.
EVHTP_EXPORT evhtp_connection_t * evhtp_request_get_connection (evhtp_request_t *request)
returns the underlying evhtp_connection_t structure from a request
EVHTP_EXPORT void evhtp_connection_set_bev (evhtp_connection_t *conn, evbev_t *bev)
Sets the connections underlying bufferevent.
EVHTP_EXPORT void evhtp_request_set_bev (evhtp_request_t *request, evbev_t *bev)
sets the underlying bufferevent for a evhtp_request
EVHTP_EXPORT evbev_t * evhtp_connection_get_bev (evhtp_connection_t *conn)
returns the underlying connections bufferevent
EVHTP_EXPORT void evhtp_connection_set_timeouts (evhtp_connection_t *conn, const struct timeval *r, const struct timeval *w)
sets a connection-specific read/write timeout which overrides the global read/write settings.
EVHTP_EXPORT evbev_t * evhtp_request_get_bev (evhtp_request_t *request)
returns the underlying requests bufferevent
EVHTP_EXPORT evbev_t * evhtp_connection_take_ownership (evhtp_connection_t *connection)
let a user take ownership of the underlying bufferevent and free all other underlying resources.
EVHTP_EXPORT void evhtp_connection_free (evhtp_connection_t *connection)
free's all connection related resources, this will also call your request fini hook and request fini hook.
EVHTP_EXPORT void evhtp_request_free (evhtp_request_t *request)
EVHTP_EXPORT void evhtp_set_max_body_size (evhtp_t *htp, uint64_t len)
set a max body size to accept for an incoming request, this will default to unlimited.
EVHTP_EXPORT void evhtp_connection_set_max_body_size (evhtp_connection_t *conn, uint64_t len)
set a max body size for a specific connection, this will default to the size set by evhtp_set_max_body_size
EVHTP_EXPORT void evhtp_request_set_max_body_size (evhtp_request_t *request, uint64_t len)
just calls evhtp_connection_set_max_body_size for the request.
EVHTP_EXPORT void evhtp_request_set_keepalive (evhtp_request_t *request, int val)
EVHTP_EXPORT void evhtp_set_max_keepalive_requests (evhtp_t *htp, uint64_t num)
sets a maximum number of requests that a single connection can make.
EVHTP_EXPORT evhtp_connection_t * evhtp_connection_new_dns (evbase_t *evbase, struct evdns_base *dns_base, const char *addr, uint16_t port)
allocate a new connection
EVHTP_EXPORT evhtp_connection_t * evhtp_connection_new (evbase_t *evbase, const char *addr, uint16_t port)
allocate a new connection
EVHTP_EXPORT evhtp_connection_t * evhtp_connection_ssl_new (evbase_t *evbase, const char *addr, uint16_t port, evhtp_ssl_ctx_t *ctx)
EVHTP_EXPORT evhtp_request_t * evhtp_request_new (evhtp_callback_cb cb, void *arg)
allocate a new request
EVHTP_EXPORT int evhtp_make_request (evhtp_connection_t *c, evhtp_request_t *r, htp_method meth, const char *uri)
make a client request
EVHTP_EXPORT unsigned int evhtp_request_status (evhtp_request_t *)
Macro Definition Documentation
#define htp_debug_strlen (x) 0
#define htp_log_debug (fmt, ...) do {} while (0)
Referenced by _evhtp_accept_cb(), _evhtp_connection_accept(), _evhtp_connection_readcb(), and _evhtp_connection_writecb().
#define evhtp_header_s evhtp_kv_s
#define evhtp_headers_s evhtp_kvs_s
Referenced by evhtp_header_val_add().
#define evhtp_query_s evhtp_kvs_s
#define evhtp_header_t evhtp_kv_t
Referenced by _evhtp_request_parser_header_key(), _evhtp_request_parser_header_val(), evhtp_header_key_add(), evhtp_header_val_add(), and evhtp_send_reply_chunk_start().
#define evhtp_headers_t evhtp_kvs_t
Referenced by _evhtp_request_new().
#define evhtp_query_t evhtp_kvs_t
Referenced by evhtp_parse_query_wflags(), and query_test().
#define EVHTP_VERSION "1.2.11"
#define EVHTP_VERSION_MAJOR 1
#define EVHTP_VERSION_MINOR 2
#define EVHTP_VERSION_PATCH 11
#define evhtp_headers_iterator evhtp_kvs_iterator
#define EVHTP_RES_ERROR 0
Referenced by _evhtp_request_parser_args(), and test_pre_accept().
#define EVHTP_RES_PAUSE 1
Referenced by _evhtp_connection_readcb(), evhtp_request_pause(), and pause_cb().
#define EVHTP_RES_FATAL 2
Referenced by _evhtp_request_parser_header_key(), _evhtp_request_parser_header_val(), _evhtp_request_parser_host(), _evhtp_request_parser_path(), and _evhtp_request_parser_port().
#define EVHTP_RES_USER 3
#define EVHTP_RES_DATA_TOO_LONG 4
Referenced by _evhtp_connection_readcb(), and _evhtp_request_parser_body().
#define EVHTP_RES_OK 200
Referenced by _evhtp_body_hook(), _evhtp_chunk_fini_hook(), _evhtp_chunk_new_hook(), _evhtp_chunks_fini_hook(), _evhtp_connection_error_hook(), _evhtp_connection_fini_hook(), _evhtp_connection_readcb(), _evhtp_connection_resumecb(), _evhtp_connection_write_hook(), _evhtp_header_hook(), _evhtp_headers_hook(), _evhtp_headers_start_hook(), _evhtp_hostname_hook(), _evhtp_path_hook(), _evhtp_request_fini_hook(), _evhtp_request_new(), _evhtp_request_parser_body(), _evhtp_request_parser_chunk_fini(), _evhtp_request_parser_chunk_new(), _evhtp_request_parser_chunks_fini(), _evhtp_request_parser_header_val(), _evhtp_request_parser_headers(), _evhtp_request_parser_headers_start(), _evhtp_request_parser_hostname(), _evhtp_request_parser_path(), _evhtp_run_post_accept(), _evhtp_run_pre_accept(), _req_cb(), backend_cb(), create_callback(), dynamic_cb(), issue161cb(), pause_connection_fini(), pause_init_cb(), pause_request_fini(), print_chunk_complete(), print_chunks_complete(), print_data(), print_kv(), print_kvs(), print_new_chunk_len(), print_path(), redis_get_srcport_cb(), response_cb(), set_max_body(), set_my_connection_handlers(), test_bar_cb(), test_chunking(), test_default_cb(), test_fini(), test_foo_cb(), test_glob_cb(), test_max_body(), test_pause_cb(), test_pre_accept(), test_regex(), test_regex_hdrs_cb(), and testcb().
#define EVHTP_RES_100 100
#define EVHTP_RES_CONTINUE 100
Referenced by status_code_to_str().
#define EVHTP_RES_SWITCH_PROTO 101
Referenced by status_code_to_str().
#define EVHTP_RES_PROCESSING 102
Referenced by status_code_to_str().
#define EVHTP_RES_URI_TOOLONG 122
Referenced by status_code_to_str().
#define EVHTP_RES_200 200
Referenced by status_code_to_str().
#define EVHTP_RES_CREATED 201
Referenced by status_code_to_str().
#define EVHTP_RES_ACCEPTED 202
Referenced by status_code_to_str().
#define EVHTP_RES_NAUTHINFO 203
Referenced by status_code_to_str().
#define EVHTP_RES_NOCONTENT 204
Referenced by evhtp_response_needs_body(), and status_code_to_str().
#define EVHTP_RES_RSTCONTENT 205
Referenced by status_code_to_str().
#define EVHTP_RES_PARTIAL 206
Referenced by status_code_to_str().
#define EVHTP_RES_MSTATUS 207
Referenced by status_code_to_str().
#define EVHTP_RES_IMUSED 226
Referenced by status_code_to_str().
#define EVHTP_RES_300 300
Referenced by status_code_to_str().
#define EVHTP_RES_MCHOICE 300
#define EVHTP_RES_MOVEDPERM 301
Referenced by status_code_to_str().
#define EVHTP_RES_FOUND 302
Referenced by status_code_to_str().
#define EVHTP_RES_SEEOTHER 303
Referenced by status_code_to_str().
#define EVHTP_RES_NOTMOD 304
Referenced by evhtp_response_needs_body(), and status_code_to_str().
#define EVHTP_RES_USEPROXY 305
Referenced by status_code_to_str().
#define EVHTP_RES_SWITCHPROXY 306
Referenced by status_code_to_str().
#define EVHTP_RES_TMPREDIR 307
Referenced by status_code_to_str().
#define EVHTP_RES_400 400
Referenced by status_code_to_str().
#define EVHTP_RES_BADREQ 400
Referenced by create_callback().
#define EVHTP_RES_UNAUTH 401
Referenced by status_code_to_str().
#define EVHTP_RES_PAYREQ 402
Referenced by status_code_to_str().
#define EVHTP_RES_FORBIDDEN 403
Referenced by status_code_to_str().
#define EVHTP_RES_NOTFOUND 404
Referenced by _evhtp_default_request_cb(), and status_code_to_str().
#define EVHTP_RES_METHNALLOWED 405
Referenced by status_code_to_str().
#define EVHTP_RES_NACCEPTABLE 406
Referenced by status_code_to_str().
#define EVHTP_RES_PROXYAUTHREQ 407
Referenced by status_code_to_str().
#define EVHTP_RES_TIMEOUT 408
Referenced by status_code_to_str().
#define EVHTP_RES_CONFLICT 409
Referenced by status_code_to_str().
#define EVHTP_RES_GONE 410
Referenced by status_code_to_str().
#define EVHTP_RES_LENREQ 411
Referenced by status_code_to_str().
#define EVHTP_RES_PRECONDFAIL 412
Referenced by status_code_to_str().
#define EVHTP_RES_ENTOOLARGE 413
Referenced by status_code_to_str().
#define EVHTP_RES_URITOOLARGE 414
Referenced by status_code_to_str().
#define EVHTP_RES_UNSUPPORTED 415
Referenced by status_code_to_str().
#define EVHTP_RES_RANGENOTSC 416
Referenced by status_code_to_str().
#define EVHTP_RES_EXPECTFAIL 417
Referenced by status_code_to_str().
#define EVHTP_RES_IAMATEAPOT 418
Referenced by status_code_to_str().
#define EVHTP_RES_500 500
#define EVHTP_RES_SERVERR 500
Referenced by status_code_to_str(), and test_500_cb().
#define EVHTP_RES_NOTIMPL 501
Referenced by status_code_to_str().
#define EVHTP_RES_BADGATEWAY 502
Referenced by status_code_to_str().
#define EVHTP_RES_SERVUNAVAIL 503
Referenced by status_code_to_str().
#define EVHTP_RES_GWTIMEOUT 504
Referenced by status_code_to_str().
#define EVHTP_RES_VERNSUPPORT 505
Referenced by status_code_to_str().
#define EVHTP_RES_BWEXEED 509
Referenced by status_code_to_str().
#define thread_init_cbarg thread_cbarg
#define evhtp_request_content_len (r) htparser_get_content_length(r->conn->parser)
Referenced by _evhtp_should_parse_query_body().
#define EVHTP_PARSE_QUERY_FLAG_STRICT 0
Referenced by evhtp_parse_query(), and main().
#define EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX (1 << 0)
Referenced by evhtp_parse_query_wflags(), and main().
#define EVHTP_PARSE_QUERY_FLAG_ALLOW_EMPTY_VALS (1 << 1)
Referenced by evhtp_parse_query_wflags(), and main().
#define EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS (1 << 2)
Referenced by evhtp_parse_query_wflags(), and main().
#define EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP (1 << 3)
Referenced by evhtp_parse_query_wflags(), and main().
#define EVHTP_PARSE_QUERY_FLAG_IGNORE_FRAGMENTS (1 << 4)
Referenced by _evhtp_request_parser_args().
#define EVHTP_PARSE_QUERY_FLAG_LENIENT
Value:
EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX         \
    | EVHTP_PARSE_QUERY_FLAG_ALLOW_EMPTY_VALS \
    | EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS  \
    | EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP
Referenced by evhtp_new(), and main().
#define evhtp_header_find evhtp_kv_find
#define evhtp_headers_find_header evhtp_kvs_find_kv
Referenced by evhtp_send_reply_chunk_start().
#define evhtp_headers_for_each evhtp_kvs_for_each
Referenced by _evhtp_create_reply(), evhtp_make_request(), and print_kvs().
#define evhtp_header_new evhtp_kv_new
#define evhtp_header_free evhtp_kv_free
#define evhtp_headers_new evhtp_kvs_new
#define evhtp_headers_free evhtp_kvs_free
Referenced by _evhtp_request_free().
#define evhtp_header_rm_and_free evhtp_kv_rm_and_free
#define evhtp_headers_add_header evhtp_kvs_add_kv
#define evhtp_headers_add_headers evhtp_kvs_add_kvs
Referenced by backend_cb(), and make_request().
#define evhtp_query_new evhtp_kvs_new
Referenced by evhtp_parse_query_wflags().
#define evhtp_query_free evhtp_kvs_free
Referenced by _evhtp_uri_free(), and evhtp_parse_query_wflags().
Typedef Documentation
typedef SSL_SESSION evhtp_ssl_sess_t
typedef SSL evhtp_ssl_t
typedef SSL_CTX evhtp_ssl_ctx_t
typedef X509 evhtp_x509_t
typedef X509_STORE_CTX evhtp_x509_store_ctx_t
typedef struct evbuffer evbuf_t
typedef struct event event_t
typedef struct evconnlistener evserv_t
typedef struct bufferevent evbev_t
typedef pthread_mutex_t evhtp_mutex_t
typedef struct evhtp_callbacks_s evhtp_callbacks_t
typedef struct evhtp_kvs_s evhtp_kvs_t
typedef uint16_t evhtp_res
typedef uint8_t evhtp_error_flags
typedef enum evhtp_hook_type evhtp_hook_type
typedef enum evhtp_callback_type evhtp_callback_type
typedef enum evhtp_proto evhtp_proto
typedef enum evhtp_ssl_scache_type evhtp_ssl_scache_type
typedef enum evhtp_type evhtp_type
typedef void(* evhtp_thread_init_cb) (evhtp_t *htp, evthr_t *thr, void *arg)
typedef void(* evhtp_thread_exit_cb) (evhtp_t *htp, evthr_t *thr, void *arg)
typedef void(* evhtp_callback_cb) (evhtp_request_t *req, void *arg)
typedef void(* evhtp_hook_err_cb) (evhtp_request_t *req, evhtp_error_flags errtype, void *arg)
typedef void(* evhtp_hook_event_cb) (evhtp_connection_t *conn, short events, void *arg)
typedef evhtp_res(* evhtp_hook) ()
typedef evhtp_res(* evhtp_hook_conn_err_cb) (evhtp_connection_t *connection, evhtp_error_flags errtype, void *arg)
typedef evhtp_res(* evhtp_pre_accept_cb) (evhtp_connection_t *conn, void *arg)
typedef evhtp_res(* evhtp_post_accept_cb) (evhtp_connection_t *conn, void *arg)
typedef evhtp_res(* evhtp_hook_header_cb) (evhtp_request_t *req, evhtp_header_t *hdr, void *arg)
typedef evhtp_res(* evhtp_hook_headers_cb) (evhtp_request_t *req, evhtp_headers_t *hdr, void *arg)
typedef evhtp_res(* evhtp_hook_path_cb) (evhtp_request_t *req, evhtp_path_t *path, void *arg)
typedef evhtp_res(* evhtp_hook_read_cb) (evhtp_request_t *req, evbuf_t *buf, void *arg)
typedef evhtp_res(* evhtp_hook_request_fini_cb) (evhtp_request_t *req, void *arg)
typedef evhtp_res(* evhtp_hook_connection_fini_cb) (evhtp_connection_t *connection, void *arg)
typedef evhtp_res(* evhtp_hook_chunk_new_cb) (evhtp_request_t *r, uint64_t len, void *arg)
typedef evhtp_res(* evhtp_hook_chunk_fini_cb) (evhtp_request_t *r, void *arg)
typedef evhtp_res(* evhtp_hook_chunks_fini_cb) (evhtp_request_t *r, void *arg)
typedef evhtp_res(* evhtp_hook_headers_start_cb) (evhtp_request_t *r, void *arg)
typedef evhtp_res(* evhtp_hook_hostname_cb) (evhtp_request_t *r, const char *hostname, void *arg)
typedef evhtp_res(* evhtp_hook_write_cb) (evhtp_connection_t *conn, void *arg)
typedef int(* evhtp_kvs_iterator) (evhtp_kv_t *kv, void *arg)
typedef int(* evhtp_headers_iterator) (evhtp_header_t *header, void *arg)
typedef int(* evhtp_ssl_verify_cb) (int pre_verify, evhtp_x509_store_ctx_t *ctx)
typedef int(* evhtp_ssl_chk_issued_cb) (evhtp_x509_store_ctx_t *ctx, evhtp_x509_t *x, evhtp_x509_t *issuer)
typedef int(* evhtp_ssl_scache_add) (evhtp_connection_t *connection, unsigned char *sid, int sid_len, evhtp_ssl_sess_t *sess)
typedef void(* evhtp_ssl_scache_del) (evhtp_t *htp, unsigned char *sid, int sid_len)
typedef evhtp_ssl_sess_t*(* evhtp_ssl_scache_get) (evhtp_connection_t *connection, unsigned char *sid, int sid_len)
typedef void*(* evhtp_ssl_scache_init) (evhtp_t *)
Enumeration Type Documentation
enum evhtp_ssl_scache_type
Enumerator
evhtp_ssl_scache_type_disabled
evhtp_ssl_scache_type_internal
evhtp_ssl_scache_type_user
evhtp_ssl_scache_type_builtin
{
     evhtp_ssl_scache_type_disabled = 0,
     evhtp_ssl_scache_type_internal,
     evhtp_ssl_scache_type_user,
     evhtp_ssl_scache_type_builtin
 };
enum evhtp_hook_type
types associated with where a developer can hook into during the request processing cycle.
Enumerator
evhtp_hook_on_header
type which defines to hook after one header has been parsed
evhtp_hook_on_headers
type which defines to hook after all headers have been parsed
evhtp_hook_on_path
type which defines to hook once a path has been parsed
evhtp_hook_on_read
type which defines to hook whenever the parser recieves data in a body
evhtp_hook_on_request_fini
type which defines to hook before the request is free'd
evhtp_hook_on_connection_fini
evhtp_hook_on_new_chunk
evhtp_hook_on_chunk_complete
evhtp_hook_on_chunks_complete
evhtp_hook_on_headers_start
evhtp_hook_on_error
type which defines to hook whenever an error occurs
evhtp_hook_on_hostname
evhtp_hook_on_write
evhtp_hook_on_event
evhtp_hook_on_conn_error
type which defines to hook whenever a connection error occurs
                      {
     evhtp_hook_on_header,
     evhtp_hook_on_headers,
     evhtp_hook_on_path,
     evhtp_hook_on_read,
     evhtp_hook_on_request_fini,
     evhtp_hook_on_connection_fini,
     evhtp_hook_on_new_chunk,
     evhtp_hook_on_chunk_complete,
     evhtp_hook_on_chunks_complete,
     evhtp_hook_on_headers_start,
     evhtp_hook_on_error,
     evhtp_hook_on_hostname,
     evhtp_hook_on_write,
     evhtp_hook_on_event,
     evhtp_hook_on_conn_error,
 };
enum evhtp_callback_type
Enumerator
evhtp_callback_type_hash
evhtp_callback_type_glob
evhtp_callback_type_regex
{
     evhtp_callback_type_hash,
     evhtp_callback_type_glob,
 #ifndef EVHTP_DISABLE_REGEX
     evhtp_callback_type_regex,
 #endif
 };
enum evhtp_proto
Enumerator
EVHTP_PROTO_INVALID
EVHTP_PROTO_10
EVHTP_PROTO_11
                  {
     EVHTP_PROTO_INVALID,
     EVHTP_PROTO_10,
     EVHTP_PROTO_11
 };
enum evhtp_type
Enumerator
evhtp_type_client
evhtp_type_server
                 {
     evhtp_type_client,
     evhtp_type_server
 };
Function Documentation
TAILQ_HEAD (evhtp_callbacks_s , evhtp_callback_s)
TAILQ_HEAD (evhtp_kvs_s , evhtp_kv_s)
EVHTP_EXPORT evhtp_t* evhtp_new (evbase_t * evbase, void * arg)
creates a new evhtp_t instance
Parameters
evbase the initialized event base
arg user-defined argument which is evhtp_t specific
Returns
a new evhtp_t structure or NULL on error
References _evhtp_default_request_cb(), evhtp_alloc_assert, evhtp_assert, EVHTP_PARSE_QUERY_FLAG_LENIENT, and evhtp_set_gencb().
Referenced by main().
{
     evhtp_t * htp;
     evhtp_assert(evbase != NULL);
     htp               = calloc(sizeof(evhtp_t), 1);
     evhtp_alloc_assert(htp);
     htp->arg          = arg;
     htp->evbase       = evbase;
     htp->bev_flags    = BEV_OPT_CLOSE_ON_FREE;
     /* default to lenient argument parsing */
     htp->parser_flags = EVHTP_PARSE_QUERY_FLAG_LENIENT;
     TAILQ_INIT(&htp->vhosts);
     TAILQ_INIT(&htp->aliases);
     evhtp_set_gencb(htp, _evhtp_default_request_cb, (void *)htp);
     return htp;
 }
EVHTP_EXPORT void evhtp_free (evhtp_t * evhtp)
References evhtp_callbacks_free(), evhtp_safe_free, evthr_pool_free(), evthr_pool_stop(), and TAILQ_FOREACH_SAFE.
Referenced by main().
{
     evhtp_alias_t * evhtp_alias, * tmp;
     if (evhtp == NULL) {
         return;
     }
 #ifndef EVHTP_DISABLE_EVTHR
     if (evhtp->thr_pool) {
         evthr_pool_stop(evhtp->thr_pool);
         evthr_pool_free(evhtp->thr_pool);
     }
 #endif
 #ifndef EVHTP_DISABLE_SSL
     if (evhtp->ssl_ctx) {
         SSL_CTX_free(evhtp->ssl_ctx);
     }
 #endif
     if (evhtp->server_name) {
         evhtp_safe_free(evhtp->server_name, free);
     }
     if (evhtp->callbacks) {
         evhtp_safe_free(evhtp->callbacks, evhtp_callbacks_free);
     }
     TAILQ_FOREACH_SAFE(evhtp_alias, &evhtp->aliases, next, tmp) {
         if (evhtp_alias->alias != NULL) {
             evhtp_safe_free(evhtp_alias->alias, free);
         }
         TAILQ_REMOVE(&evhtp->aliases, evhtp_alias, next);
         evhtp_safe_free(evhtp_alias, free);
     }
 #ifndef EVHTP_DISABLE_SSL
     if (evhtp->ssl_ctx) {
         SSL_CTX_free(evhtp->ssl_ctx);
     }
 #endif
     evhtp_safe_free(evhtp, free);
 } /* evhtp_free */
EVHTP_EXPORT void evhtp_set_timeouts (evhtp_t * htp, const struct timeval * r, const struct timeval * w)
set a read/write timeout on all things evhtp_t. When the timeout expires your error hook will be called with the libevent supplied event flags.
Parameters
htp the base evhtp_t struct
r read-timeout in timeval
w write-timeout in timeval.
{
     if (r_timeo != NULL) {
         htp->recv_timeo = *r_timeo;
     }
     if (w_timeo != NULL) {
         htp->send_timeo = *w_timeo;
     }
 }
EVHTP_EXPORT void evhtp_set_parser_flags (evhtp_t * htp, int flags)
during the request processing cycle, these flags will be used to for query argument parsing. i.e., what to parse and not to parse.
SEE: EVHTP_PARSE_QUERY_* stuff.
For example, if you do not wish for the streaming parser attempting the act of fragment parsing: evhtp_set_parser_flags(htp, EVHTP_PARSE_QUERY_FLAG_IGNORE_FRAGMENTS);
Parameters
htp
flags
Referenced by main().
{
     htp->parser_flags = flags;
 }
EVHTP_EXPORT void evhtp_set_bev_flags (evhtp_t * htp, int flags)
bufferevent flags which will be used for bev sockets.
Parameters
htp
flags bufferevent flags which will be used for bev sockets.
htp
flags
{
     htp->bev_flags = flags;
 }
EVHTP_EXPORT int evhtp_ssl_use_threads (void)
References _evhtp_ssl_get_thread_id(), _evhtp_ssl_thread_lock(), ssl_locks, ssl_locks_initialized, and ssl_num_locks.
Referenced by _evhtp_use_threads().
{
     int i;
     if (ssl_locks_initialized == 1) {
         return 0;
     }
     ssl_locks_initialized = 1;
     ssl_num_locks         = CRYPTO_num_locks();
     ssl_locks = malloc(ssl_num_locks * sizeof(evhtp_mutex_t));
     for (i = 0; i < ssl_num_locks; i++) {
         pthread_mutex_init(&(ssl_locks[i]), NULL);
     }
     CRYPTO_set_id_callback(_evhtp_ssl_get_thread_id);
     CRYPTO_set_locking_callback(_evhtp_ssl_thread_lock);
     return 0;
 }
EVHTP_EXPORT int evhtp_ssl_init (evhtp_t * htp, evhtp_ssl_cfg_t * ssl_cfg)
References _evhtp_ssl_add_scache_ent(), _evhtp_ssl_delete_scache_ent(), _evhtp_ssl_get_scache_ent(), evhtp_alloc_assert, evhtp_ssl_scache_type_builtin, evhtp_ssl_scache_type_disabled, evhtp_ssl_scache_type_internal, evhtp_ssl_scache_type_user, and session_id_context.
Referenced by main().
{
 #ifdef EVHTP_ENABLE_FUTURE_STUFF
     evhtp_ssl_scache_init init_cb = NULL;
     evhtp_ssl_scache_add  add_cb  = NULL;
     evhtp_ssl_scache_get  get_cb  = NULL;
     evhtp_ssl_scache_del  del_cb  = NULL;
 #endif
     long                  cache_mode;
     if (cfg == NULL || htp == NULL || cfg->pemfile == NULL) {
         return -1;
     }
     SSL_library_init();
     SSL_load_error_strings();
     RAND_poll();
 #if OPENSSL_VERSION_NUMBER < 0x10000000L
     STACK_OF(SSL_COMP) * comp_methods = SSL_COMP_get_compression_methods();
     sk_SSL_COMP_zero(comp_methods);
 #endif
     htp->ssl_cfg = cfg;
     htp->ssl_ctx = SSL_CTX_new(SSLv23_server_method());
     evhtp_alloc_assert(htp->ssl_ctx);
 #if OPENSSL_VERSION_NUMBER >= 0x10000000L
     SSL_CTX_set_options(htp->ssl_ctx, SSL_MODE_RELEASE_BUFFERS | SSL_OP_NO_COMPRESSION);
     SSL_CTX_set_timeout(htp->ssl_ctx, cfg->ssl_ctx_timeout);
 #endif
     SSL_CTX_set_options(htp->ssl_ctx, cfg->ssl_opts);
 #ifndef OPENSSL_NO_ECDH
     if (cfg->named_curve != NULL) {
         EC_KEY * ecdh = NULL;
         int      nid  = 0;
         nid  = OBJ_sn2nid(cfg->named_curve);
         if (nid == 0) {
             fprintf(stderr, "ECDH initialization failed: unknown curve %s\n", cfg->named_curve);
         }
         ecdh = EC_KEY_new_by_curve_name(nid);
         if (ecdh == NULL) {
             fprintf(stderr, "ECDH initialization failed for curve %s\n", cfg->named_curve);
         }
         SSL_CTX_set_tmp_ecdh(htp->ssl_ctx, ecdh);
         EC_KEY_free(ecdh);
     }
 #endif /* OPENSSL_NO_ECDH */
 #ifndef OPENSSL_NO_DH
     if (cfg->dhparams != NULL) {
         FILE * fh;
         DH   * dh;
         fh = fopen(cfg->dhparams, "r");
         if (fh != NULL) {
             dh = PEM_read_DHparams(fh, NULL, NULL, NULL);
             if (dh != NULL) {
                 SSL_CTX_set_tmp_dh(htp->ssl_ctx, dh);
                 DH_free(dh);
             } else {
                 fprintf(stderr, "DH initialization failed: unable to parse file %s\n", cfg->dhparams);
             }
             fclose(fh);
         } else {
             fprintf(stderr, "DH initialization failed: unable to open file %s\n", cfg->dhparams);
         }
     }
 #endif /* OPENSSL_NO_DH */
     if (cfg->ciphers != NULL) {
         SSL_CTX_set_cipher_list(htp->ssl_ctx, cfg->ciphers);
     }
     SSL_CTX_load_verify_locations(htp->ssl_ctx, cfg->cafile, cfg->capath);
     X509_STORE_set_flags(SSL_CTX_get_cert_store(htp->ssl_ctx), cfg->store_flags);
     SSL_CTX_set_verify(htp->ssl_ctx, cfg->verify_peer, cfg->x509_verify_cb);
     if (cfg->x509_chk_issued_cb != NULL) {
         htp->ssl_ctx->cert_store->check_issued = cfg->x509_chk_issued_cb;
     }
     if (cfg->verify_depth) {
         SSL_CTX_set_verify_depth(htp->ssl_ctx, cfg->verify_depth);
     }
     switch (cfg->scache_type) {
         case evhtp_ssl_scache_type_disabled:
             cache_mode = SSL_SESS_CACHE_OFF;
             break;
 #ifdef EVHTP_ENABLE_FUTURE_STUFF
         case evhtp_ssl_scache_type_user:
             cache_mode = SSL_SESS_CACHE_SERVER |
                          SSL_SESS_CACHE_NO_INTERNAL |
                          SSL_SESS_CACHE_NO_INTERNAL_LOOKUP;
             init_cb    = cfg->scache_init;
             add_cb     = cfg->scache_add;
             get_cb     = cfg->scache_get;
             del_cb     = cfg->scache_del;
             break;
         case evhtp_ssl_scache_type_builtin:
             cache_mode = SSL_SESS_CACHE_SERVER |
                          SSL_SESS_CACHE_NO_INTERNAL |
                          SSL_SESS_CACHE_NO_INTERNAL_LOOKUP;
             init_cb    = _evhtp_ssl_builtin_init;
             add_cb     = _evhtp_ssl_builtin_add;
             get_cb     = _evhtp_ssl_builtin_get;
             del_cb     = _evhtp_ssl_builtin_del;
             break;
 #endif
         case evhtp_ssl_scache_type_internal:
         default:
             cache_mode = SSL_SESS_CACHE_SERVER;
             break;
     }     /* switch */
     SSL_CTX_use_certificate_file(htp->ssl_ctx, cfg->pemfile, SSL_FILETYPE_PEM);
     SSL_CTX_use_PrivateKey_file(htp->ssl_ctx,
                                 cfg->privfile ? cfg->privfile : cfg->pemfile, SSL_FILETYPE_PEM);
     SSL_CTX_set_session_id_context(htp->ssl_ctx,
                                    (void *)&session_id_context,
                                    sizeof(session_id_context));
     SSL_CTX_set_app_data(htp->ssl_ctx, htp);
     SSL_CTX_set_session_cache_mode(htp->ssl_ctx, cache_mode);
     if (cache_mode != SSL_SESS_CACHE_OFF) {
         SSL_CTX_sess_set_cache_size(htp->ssl_ctx,
                                     cfg->scache_size ? cfg->scache_size : 1024);
         if (cfg->scache_type == evhtp_ssl_scache_type_builtin ||
             cfg->scache_type == evhtp_ssl_scache_type_user) {
             SSL_CTX_sess_set_new_cb(htp->ssl_ctx, _evhtp_ssl_add_scache_ent);
             SSL_CTX_sess_set_get_cb(htp->ssl_ctx, _evhtp_ssl_get_scache_ent);
             SSL_CTX_sess_set_remove_cb(htp->ssl_ctx, _evhtp_ssl_delete_scache_ent);
             if (cfg->scache_init) {
                 cfg->args = (cfg->scache_init)(htp);
             }
         }
     }
     return 0;
 }     /* evhtp_use_ssl */
EVHTP_EXPORT void evhtp_disable_100_continue (evhtp_t * htp)
when a client sends an Expect: 100-continue, if this is function is called, evhtp will not send a HTTP/x.x continue response.
Parameters
htp
{
     htp->disable_100_cont = 1;
 }
EVHTP_EXPORT int evhtp_use_callback_locks (evhtp_t * htp)
creates a lock around callbacks and hooks, allowing for threaded applications to add/remove/modify hooks & callbacks in a thread-safe manner.
Parameters
htp
Returns
0 on success, -1 on error
{
     if (htp == NULL) {
         return -1;
     }
     if (!(htp->lock = malloc(sizeof(pthread_mutex_t)))) {
         return -1;
     }
     return pthread_mutex_init(htp->lock, NULL);
 }
EVHTP_EXPORT void evhtp_set_gencb (evhtp_t * htp, evhtp_callback_cb cb, void * arg)
sets a callback which is called if no other callbacks are matched
Parameters
htp the initialized evhtp_t
cb the function to be executed
arg user-defined argument passed to the callback
References cb.
Referenced by evhtp_new(), and main().
{
     htp->defaults.cb    = cb;
     htp->defaults.cbarg = arg;
 }
EVHTP_EXPORT void evhtp_set_pre_accept_cb (evhtp_t * htp, evhtp_pre_accept_cb , void * arg)
call a user-defined function before the connection is accepted.
Parameters
htp
evhtp_pre_accept_cb
arg
Returns
References cb.
Referenced by main().
{
     htp->defaults.pre_accept       = cb;
     htp->defaults.pre_accept_cbarg = arg;
 }
EVHTP_EXPORT void evhtp_set_post_accept_cb (evhtp_t * htp, evhtp_post_accept_cb , void * arg)
call a user-defined function right after a connection is accepted.
Parameters
htp
evhtp_post_accept_cb
arg
Returns
References cb.
Referenced by main().
{
     htp->defaults.post_accept       = cb;
     htp->defaults.post_accept_cbarg = arg;
 }
EVHTP_EXPORT evhtp_callback_t* evhtp_set_cb (evhtp_t * htp, const char * path, evhtp_callback_cb cb, void * arg)
sets a callback to be executed on a specific path
Parameters
htp the initialized evhtp_t
path the path to match
cb the function to be executed
arg user-defined argument passed to the callback
Returns
evhtp_callback_t * on success, NULL on error.
References _evhtp_lock, _evhtp_unlock, evhtp_callback_free(), evhtp_callback_new(), evhtp_callback_type_hash, evhtp_callbacks_add_callback(), and evhtp_safe_free.
Referenced by create_callback(), and main().
{
     evhtp_callback_t * hcb;
     _evhtp_lock(htp);
     if (htp->callbacks == NULL) {
         if (!(htp->callbacks = calloc(sizeof(evhtp_callbacks_t), 1))) {
             _evhtp_unlock(htp);
             return NULL;
         }
         TAILQ_INIT(htp->callbacks);
     }
     if (!(hcb = evhtp_callback_new(path, evhtp_callback_type_hash, cb, arg))) {
         _evhtp_unlock(htp);
         return NULL;
     }
     if (evhtp_callbacks_add_callback(htp->callbacks, hcb)) {
         evhtp_safe_free(hcb, evhtp_callback_free);
         _evhtp_unlock(htp);
         return NULL;
     }
     _evhtp_unlock(htp);
     return hcb;
 }
EVHTP_EXPORT evhtp_callback_t* evhtp_set_regex_cb (evhtp_t * htp, const char * pattern, evhtp_callback_cb cb, void * arg)
sets a callback to be executed based on a regex pattern
Parameters
htp the initialized evhtp_t
pattern a POSIX compat regular expression
cb the function to be executed
arg user-defined argument passed to the callback
Returns
evhtp_callback_t * on success, NULL on error
References _evhtp_lock, _evhtp_unlock, evhtp_callback_free(), evhtp_callback_new(), evhtp_callback_type_regex, evhtp_callbacks_add_callback(), and evhtp_safe_free.
Referenced by main().
{
     evhtp_callback_t * hcb;
     _evhtp_lock(htp);
     if (htp->callbacks == NULL) {
         if (!(htp->callbacks = calloc(sizeof(evhtp_callbacks_t), 1))) {
             _evhtp_unlock(htp);
             return NULL;
         }
         TAILQ_INIT(htp->callbacks);
     }
     if (!(hcb = evhtp_callback_new(pattern, evhtp_callback_type_regex, cb, arg))) {
         _evhtp_unlock(htp);
         return NULL;
     }
     if (evhtp_callbacks_add_callback(htp->callbacks, hcb)) {
         evhtp_safe_free(hcb, evhtp_callback_free);
         _evhtp_unlock(htp);
         return NULL;
     }
     _evhtp_unlock(htp);
     return hcb;
 }
EVHTP_EXPORT evhtp_callback_t* evhtp_set_glob_cb (evhtp_t * htp, const char * pattern, evhtp_callback_cb cb, void * arg)
sets a callback to to be executed on simple glob/wildcard patterns this is useful if the app does not care about what was matched, but just that it matched. This is technically faster than regex.
Parameters
htp
pattern wildcard pattern, the '*' can be set at either or both the front or end.
cb
arg
Returns
References _evhtp_lock, _evhtp_unlock, evhtp_callback_free(), evhtp_callback_new(), evhtp_callback_type_glob, evhtp_callbacks_add_callback(), and evhtp_safe_free.
Referenced by main().
{
     evhtp_callback_t * hcb;
     _evhtp_lock(htp);
     if (htp->callbacks == NULL) {
         if (!(htp->callbacks = calloc(sizeof(evhtp_callbacks_t), 1))) {
             _evhtp_unlock(htp);
             return NULL;
         }
         TAILQ_INIT(htp->callbacks);
     }
     if (!(hcb = evhtp_callback_new(pattern, evhtp_callback_type_glob, cb, arg))) {
         _evhtp_unlock(htp);
         return NULL;
     }
     if (evhtp_callbacks_add_callback(htp->callbacks, hcb)) {
         evhtp_safe_free(hcb, evhtp_callback_free);
         _evhtp_unlock(htp);
         return NULL;
     }
     _evhtp_unlock(htp);
     return hcb;
 }
EVHTP_EXPORT evhtp_callback_t* evhtp_get_cb (evhtp_t * htp, const char * needle)
attempts to find the callback matching the exact string 'needle'. This is useful in cases where we want to get the original handle, but is not in scope.
with pattern based callbacks, this does not attempt to find a callback that would match the string if the pattern matcher was executed.
Meaning: evhtp_set_glob_cb(htp, "/foo/bar*", ....);
Calling evhtp_get_cb(htp, "/foo/bar/baz");
Will return NULL since it's not the exact pattern set
Calling evhtp_get_cb(htp, "/foo/bar*");
Is the correct usage.
Parameters
htp
needle
Returns
NULL if callback is not not found
{
     evhtp_callback_t * callback;
     TAILQ_FOREACH(callback, htp->callbacks, next) {
         if (strcmp(callback->val.path, path) == 0) {
             return callback;
         }
     }
     return NULL;
 }
EVHTP_EXPORT int evhtp_set_hook (evhtp_hooks_t ** hooks, evhtp_hook_type type, evhtp_hook cb, void * arg)
sets a callback hook for either a connection or a path/regex .
A user may set a variety of hooks either per-connection, or per-callback. This allows the developer to hook into various parts of the request processing cycle.
a per-connection hook can be set at any time, but it is recommended to set these during either a pre-accept phase, or post-accept phase. This allows a developer to set hooks before any other hooks are called.
a per-callback hook works differently. In this mode a developer can setup a set of hooks prior to starting the event loop for specific callbacks. For example if you wanted to hook something ONLY for a callback set by evhtp_set_cb or evhtp_set_regex_cb this is the method of doing so.
per-callback example:
evhtp_callback_t * cb = evhtp_set_regex_cb(htp, "/anything/(.*)", default_cb, NULL);
evhtp_set_hook(&cb->hooks, evhtp_hook_on_headers, anything_headers_cb, NULL);
evhtp_set_hook(&cb->hooks, evhtp_hook_on_fini, anything_fini_cb, NULL);
With the above example, once libevhtp has determined that it has a user-defined callback for /anything/.*; anything_headers_cb will be executed after all headers have been parsed, and anything_fini_cb will be executed before the request is free()'d.
The same logic applies to per-connection hooks, but it should be noted that if a per-callback hook is set, the per-connection hook will be ignored.
Parameters
hooks double pointer to the evhtp_hooks_t structure
type the hook type
cb the callback to be executed.
arg optional argument which is passed when the callback is executed
Returns
0 on success, -1 on error (if hooks is NULL, it is allocated)
References evhtp_hook_on_chunk_complete, evhtp_hook_on_chunks_complete, evhtp_hook_on_conn_error, evhtp_hook_on_connection_fini, evhtp_hook_on_error, evhtp_hook_on_event, evhtp_hook_on_header, evhtp_hook_on_headers, evhtp_hook_on_headers_start, evhtp_hook_on_hostname, evhtp_hook_on_new_chunk, evhtp_hook_on_path, evhtp_hook_on_read, evhtp_hook_on_request_fini, and evhtp_hook_on_write.
Referenced by evhtp_unset_hook(), main(), pause_init_cb(), and set_my_connection_handlers().
{
     if (*hooks == NULL) {
         if (!(*hooks = calloc(sizeof(evhtp_hooks_t), 1))) {
             return -1;
         }
     }
     switch (type) {
         case evhtp_hook_on_headers_start:
             (*hooks)->on_headers_start        = (evhtp_hook_headers_start_cb)cb;
             (*hooks)->on_headers_start_arg    = arg;
             break;
         case evhtp_hook_on_header:
             (*hooks)->on_header = (evhtp_hook_header_cb)cb;
             (*hooks)->on_header_arg           = arg;
             break;
         case evhtp_hook_on_headers:
             (*hooks)->on_headers              = (evhtp_hook_headers_cb)cb;
             (*hooks)->on_headers_arg          = arg;
             break;
         case evhtp_hook_on_path:
             (*hooks)->on_path = (evhtp_hook_path_cb)cb;
             (*hooks)->on_path_arg             = arg;
             break;
         case evhtp_hook_on_read:
             (*hooks)->on_read = (evhtp_hook_read_cb)cb;
             (*hooks)->on_read_arg             = arg;
             break;
         case evhtp_hook_on_request_fini:
             (*hooks)->on_request_fini         = (evhtp_hook_request_fini_cb)cb;
             (*hooks)->on_request_fini_arg     = arg;
             break;
         case evhtp_hook_on_connection_fini:
             (*hooks)->on_connection_fini      = (evhtp_hook_connection_fini_cb)cb;
             (*hooks)->on_connection_fini_arg  = arg;
             break;
         case evhtp_hook_on_conn_error:
             (*hooks)->on_connection_error     = (evhtp_hook_conn_err_cb)cb;
             (*hooks)->on_connection_error_arg = arg;
             break;
         case evhtp_hook_on_error:
             (*hooks)->on_error = (evhtp_hook_err_cb)cb;
             (*hooks)->on_error_arg            = arg;
             break;
         case evhtp_hook_on_new_chunk:
             (*hooks)->on_new_chunk            = (evhtp_hook_chunk_new_cb)cb;
             (*hooks)->on_new_chunk_arg        = arg;
             break;
         case evhtp_hook_on_chunk_complete:
             (*hooks)->on_chunk_fini           = (evhtp_hook_chunk_fini_cb)cb;
             (*hooks)->on_chunk_fini_arg       = arg;
             break;
         case evhtp_hook_on_chunks_complete:
             (*hooks)->on_chunks_fini          = (evhtp_hook_chunks_fini_cb)cb;
             (*hooks)->on_chunks_fini_arg      = arg;
             break;
         case evhtp_hook_on_hostname:
             (*hooks)->on_hostname             = (evhtp_hook_hostname_cb)cb;
             (*hooks)->on_hostname_arg         = arg;
             break;
         case evhtp_hook_on_write:
             (*hooks)->on_write = (evhtp_hook_write_cb)cb;
             (*hooks)->on_write_arg            = arg;
             break;
         case evhtp_hook_on_event:
             (*hooks)->on_event = (evhtp_hook_event_cb)cb;
             (*hooks)->on_event_arg            = arg;
             break;
         default:
             return -1;
     }     /* switch */
     return 0;
 }         /* evhtp_set_hook */
EVHTP_EXPORT int evhtp_unset_hook (evhtp_hooks_t ** hooks, evhtp_hook_type type)
remove a specific hook from being called.
Parameters
hooks
type
Returns
References evhtp_set_hook().
Referenced by evhtp_unset_all_hooks().
{
     return evhtp_set_hook(hooks, type, NULL, NULL);
 }
EVHTP_EXPORT int evhtp_unset_all_hooks (evhtp_hooks_t ** hooks)
removes all hooks.
Parameters
hooks
Returns
References evhtp_hook_on_chunk_complete, evhtp_hook_on_chunks_complete, evhtp_hook_on_conn_error, evhtp_hook_on_connection_fini, evhtp_hook_on_error, evhtp_hook_on_event, evhtp_hook_on_header, evhtp_hook_on_headers, evhtp_hook_on_headers_start, evhtp_hook_on_hostname, evhtp_hook_on_new_chunk, evhtp_hook_on_path, evhtp_hook_on_read, evhtp_hook_on_request_fini, evhtp_hook_on_write, and evhtp_unset_hook().
Referenced by evhtp_connection_take_ownership().
{
     int res = 0;
     if (evhtp_unset_hook(hooks, evhtp_hook_on_headers_start)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_header)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_headers)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_path)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_read)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_request_fini)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_connection_fini)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_conn_error)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_error)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_new_chunk)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_chunk_complete)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_chunks_complete)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_hostname)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_write)) {
         return -1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_event)) {
         return -1;
     }
     return res;
 } /* evhtp_unset_all_hooks */
EVHTP_EXPORT int evhtp_bind_socket (evhtp_t * htp, const char * addr, uint16_t port, int backlog)
bind to a socket, optionally with specific protocol support formatting. The addr can be defined as one of the following: ipv6:<ipv6addr> for binding to an IPv6 address. unix:<named pipe>=""> for binding to a unix named socket ipv4:<ipv4addr> for binding to an ipv4 address Otherwise the addr is assumed to be ipv4.
Parameters
htp
addr
port
backlog
Returns
References evhtp_bind_sockaddr().
Referenced by main().
{
 #ifndef NO_SYS_UN
     struct sockaddr_un  sun;
 #endif
     struct sockaddr_in6 sin6;
     struct sockaddr_in  sin;
     struct sockaddr   * sa;
     size_t              sin_len;
     memset(&sin, 0, sizeof(sin));
     if (!strncmp(baddr, "ipv6:", 5)) {
         memset(&sin6, 0, sizeof(sin6));
         baddr           += 5;
         sin_len          = sizeof(struct sockaddr_in6);
         sin6.sin6_port   = htons(port);
         sin6.sin6_family = AF_INET6;
         evutil_inet_pton(AF_INET6, baddr, &sin6.sin6_addr);
         sa = (struct sockaddr *)&sin6;
     } else if (!strncmp(baddr, "unix:", 5)) {
 #ifndef NO_SYS_UN
         baddr += 5;
         if (strlen(baddr) >= sizeof(sun.sun_path)) {
             return -1;
         }
         memset(&sun, 0, sizeof(sun));
         sin_len        = sizeof(struct sockaddr_un);
         sun.sun_family = AF_UNIX;
         strncpy(sun.sun_path, baddr, strlen(baddr));
         sa = (struct sockaddr *)&sun;
 #else
         return -1;
 #endif
     } else {
         if (!strncmp(baddr, "ipv4:", 5)) {
             baddr += 5;
         }
         sin_len             = sizeof(struct sockaddr_in);
         sin.sin_family      = AF_INET;
         sin.sin_port        = htons(port);
         sin.sin_addr.s_addr = inet_addr(baddr);
         sa = (struct sockaddr *)&sin;
     }
     return evhtp_bind_sockaddr(htp, sa, sin_len, backlog);
 } /* evhtp_bind_socket */
EVHTP_EXPORT void evhtp_unbind_socket (evhtp_t * htp)
stops the listening socket.
Parameters
htp
References evhtp_safe_free.
Referenced by main().
{
     evhtp_safe_free(htp->server, evconnlistener_free);
 }
EVHTP_EXPORT int evhtp_accept_socket (evhtp_t * htp, evutil_socket_t sock, int backlog)
create the listener plus setup various options with an already-bound socket.
Parameters
htp
sock
backlog
Returns
0 on success, -1 on error (check errno)
References _evhtp_accept_cb(), _evhtp_ssl_servername(), and evhtp_assert.
Referenced by evhtp_bind_sockaddr().
{
     int on = 1;
     evhtp_assert(htp != NULL);
     if (sock == -1) {
         return -1;
     }
 #if defined SO_REUSEPORT
     if (htp->enable_reuseport) {
         setsockopt(sock, SOL_SOCKET, SO_REUSEPORT, (void *)&on, sizeof(on));
     }
 #endif
 #if defined TCP_NODELAY
     if (htp->enable_nodelay == 1) {
         setsockopt(sock, IPPROTO_TCP, TCP_NODELAY, (void *)&on, sizeof(on));
     }
 #endif
 #if defined TCP_DEFER_ACCEPT
     if (htp->enable_defer_accept == 1) {
         setsockopt(sock, IPPROTO_TCP, TCP_DEFER_ACCEPT, (void *)&on, sizeof(on));
     }
 #endif
     htp->server = evconnlistener_new(htp->evbase, _evhtp_accept_cb, htp,
                                      LEV_OPT_CLOSE_ON_FREE | LEV_OPT_REUSEABLE,
                                      backlog, sock);
     if (htp->server == NULL) {
         return -1;
     }
 #ifndef EVHTP_DISABLE_SSL
     if (htp->ssl_ctx != NULL) {
         /* if ssl is enabled and we have virtual hosts, set our servername
          * callback. We do this here because we want to make sure that this gets
          * set after all potential virtualhosts have been set, not just after
          * ssl_init.
          */
         if (TAILQ_FIRST(&htp->vhosts) != NULL) {
             SSL_CTX_set_tlsext_servername_callback(htp->ssl_ctx,
                                                    _evhtp_ssl_servername);
         }
     }
 #endif
     return 0;
 } /* evhtp_accept_socket */
EVHTP_EXPORT int evhtp_bind_sockaddr (evhtp_t * htp, struct sockaddr * , size_t sin_len, int backlog)
bind to an already allocated sockaddr.
Parameters
htp s
sin_len
backlog
Returns
References evhtp_accept_socket(), and evhtp_errno_assert.
Referenced by evhtp_bind_socket().
{
 #ifndef WIN32
     signal(SIGPIPE, SIG_IGN);
 #endif
     evutil_socket_t fd;
     int             on = 1;
     fd = socket(sa->sa_family, SOCK_STREAM, 0);
     evhtp_errno_assert(fd != -1);
     evutil_make_socket_closeonexec(fd);
     evutil_make_socket_nonblocking(fd);
     setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, (void *)&on, sizeof(on));
     setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (void *)&on, sizeof(on));
     if (sa->sa_family == AF_INET6) {
         int rc;
         rc = setsockopt(fd, IPPROTO_IPV6, IPV6_V6ONLY, &on, sizeof(on));
         evhtp_errno_assert(rc != -1);
     }
     if (bind(fd, sa, sin_len) == -1) {
         return -1;
     }
     return evhtp_accept_socket(htp, fd, backlog);
 } /* evhtp_bind_sockaddr */
EVHTP_EXPORT int evhtp_use_threads (evhtp_t * , evhtp_thread_init_cb , int nthreads, void *)
Enable thread-pool support for an evhtp_t context. Connectios are distributed across 'nthreads'. An optional "on-start" callback can be set which allows you to manipulate the thread-specific inforation (such as the thread-specific event_base).
Parameters
htp
init_cb
exit_cb
nthreads
arg
Returns
References _evhtp_use_threads().
Referenced by main().
{
     return _evhtp_use_threads(htp, init_cb, NULL, nthreads, arg);
 }
EVHTP_EXPORT int evhtp_use_threads_wexit (evhtp_t * , evhtp_thread_init_cb , evhtp_thread_exit_cb , int nthreads, void * arg)
Temporary function which will be renamed evhtp_use_threads in the future. evhtp_use_threads() has been noted as deprecated for now.
References _evhtp_use_threads().
{
     return _evhtp_use_threads(htp, init_cb, exit_cb, nthreads, arg);
 }
EVHTP_EXPORT void evhtp_send_reply (evhtp_request_t * request, evhtp_res code)
generates all the right information for a reply to be sent to the client
Parameters
request
code HTTP return status code
References _evhtp_create_reply(), evhtp_connection_free(), evhtp_connection_get_bev(), and evhtp_request_get_connection().
Referenced by _evhtp_default_request_cb(), _req_cb(), backend_cb(), create_callback(), dynamic_cb(), redis_get_srcport_cb(), response_cb(), test_500_cb(), test_bar_cb(), test_default_cb(), test_foo_cb(), test_glob_cb(), test_max_body(), test_pause_cb(), test_regex(), and testcb().
{
     evhtp_connection_t * c;
     evbuf_t            * reply_buf;
     struct bufferevent * bev;
     c = evhtp_request_get_connection(request);
     request->finished = 1;
     if (!(reply_buf = _evhtp_create_reply(request, code))) {
         evhtp_connection_free(request->conn);
         return;
     }
     bev = evhtp_connection_get_bev(c);
     bufferevent_lock(bev);
     {
         bufferevent_write_buffer(bev, reply_buf);
     }
     bufferevent_unlock(bev);
     evbuffer_drain(reply_buf, -1);
     /* evbuffer_free(reply_buf); */
 }
EVHTP_EXPORT void evhtp_send_reply_start (evhtp_request_t * request, evhtp_res code)
References _evhtp_create_reply(), evhtp_connection_free(), and evhtp_request_get_connection().
Referenced by evhtp_send_reply_chunk_start(), and issue161cb().
{
     evhtp_connection_t * c;
     evbuf_t            * reply_buf;
     c = evhtp_request_get_connection(request);
     if (!(reply_buf = _evhtp_create_reply(request, code))) {
         evhtp_connection_free(c);
         return;
     }
     bufferevent_write_buffer(c->bev, reply_buf);
     evbuffer_drain(reply_buf, -1);
     /* evbuffer_free(reply_buf); */
 }
EVHTP_EXPORT void evhtp_send_reply_body (evhtp_request_t * request, evbuf_t * buf)
Referenced by evhtp_send_reply_chunk(), and issue161cb().
{
     evhtp_connection_t * c;
     c = request->conn;
     bufferevent_write_buffer(c->bev, buf);
 }
EVHTP_EXPORT void evhtp_send_reply_end (evhtp_request_t * request)
Referenced by evhtp_send_reply_chunk_end(), and issue161cb().
{
     request->finished = 1;
 }
EVHTP_EXPORT int evhtp_response_needs_body (const evhtp_res code, const htp_method method)
Determine if a response should have a body. Follows the rules in RFC 2616 section 4.3.
Returns
1 if the response MUST have a body; 0 if the response MUST NOT have a body.
References EVHTP_RES_NOCONTENT, EVHTP_RES_NOTMOD, and htp_method_HEAD.
Referenced by evhtp_send_reply_chunk_start().
{
     return code != EVHTP_RES_NOCONTENT &&
            code != EVHTP_RES_NOTMOD &&
            (code < 100 || code >= 200) &&
            method != htp_method_HEAD;
 }
EVHTP_EXPORT void evhtp_send_reply_chunk_start (evhtp_request_t * request, evhtp_res code)
start a chunked response. If data already exists on the output buffer, this will be converted to the first chunk.
Parameters
request
code
References evhtp_header_new(), evhtp_header_t, evhtp_headers_add_header(), evhtp_headers_find_header, evhtp_kv_rm_and_free(), EVHTP_PROTO_10, EVHTP_PROTO_11, evhtp_response_needs_body(), and evhtp_send_reply_start().
Referenced by test_chunking().
{
     evhtp_header_t * content_len;
     if (evhtp_response_needs_body(code, request->method)) {
         content_len = evhtp_headers_find_header(request->headers_out, "Content-Length");
         switch (request->proto) {
             case EVHTP_PROTO_11:
                 /*
                  * prefer HTTP/1.1 chunked encoding to closing the connection;
                  * note RFC 2616 section 4.4 forbids it with Content-Length:
                  * and it's not necessary then anyway.
                  */
                 evhtp_kv_rm_and_free(request->headers_out, content_len);
                 request->chunked = 1;
                 break;
             case EVHTP_PROTO_10:
                 /*
                  * HTTP/1.0 can be chunked as long as the Content-Length header
                  * is set to 0
                  */
                 evhtp_kv_rm_and_free(request->headers_out, content_len);
 #if 0
                 evhtp_headers_add_header(request->headers_out,
                                          evhtp_header_new("Content-Length", "0", 0, 0));
 #endif
                 request->chunked = 1;
                 break;
             default:
                 request->chunked = 0;
                 break;
         } /* switch */
     } else {
         request->chunked = 0;
     }
     if (request->chunked == 1) {
         evhtp_headers_add_header(request->headers_out,
                                  evhtp_header_new("Transfer-Encoding", "chunked", 0, 0));
         /*
          * if data already exists on the output buffer, we automagically convert
          * it to the first chunk.
          */
         if (evbuffer_get_length(request->buffer_out) > 0) {
             char lstr[128];
             int  sres;
             sres = snprintf(lstr, sizeof(lstr), "%x\r\n",
                             (unsigned)evbuffer_get_length(request->buffer_out));
             if (sres >= sizeof(lstr) || sres < 0) {
                 /* overflow condition, shouldn't ever get here, but lets
                  * terminate the connection asap */
                 goto end;
             }
             evbuffer_prepend(request->buffer_out, lstr, strlen(lstr));
             evbuffer_add(request->buffer_out, "\r\n", 2);
         }
     }
 end:
     evhtp_send_reply_start(request, code);
 } /* evhtp_send_reply_chunk_start */
EVHTP_EXPORT void evhtp_send_reply_chunk (evhtp_request_t * request, evbuf_t * buf)
send a chunk reply.
Parameters
request
buf
References evhtp_send_reply_body().
Referenced by test_chunking().
{
     evbuf_t * output;
     if (evbuffer_get_length(buf) == 0) {
         return;
     }
     output = bufferevent_get_output(request->conn->bev);
     if (request->chunked == 1) {
         evbuffer_add_printf(output, "%x\r\n",
                             (unsigned)evbuffer_get_length(buf));
     }
     evhtp_send_reply_body(request, buf);
     if (request->chunked) {
         evbuffer_add(output, "\r\n", 2);
     }
     bufferevent_flush(request->conn->bev, EV_WRITE, BEV_FLUSH);
 }
EVHTP_EXPORT void evhtp_send_reply_chunk_end (evhtp_request_t * request)
call when all chunks have been sent and you wish to send the last bits. This will add the last 0CRLFCRCL and call send_reply_end().
Parameters
request
References evhtp_request_get_bev(), and evhtp_send_reply_end().
Referenced by test_chunking().
{
     if (request->chunked == 1) {
         evbuffer_add(bufferevent_get_output(evhtp_request_get_bev(request)),
                      "0\r\n\r\n", 5);
     }
     evhtp_send_reply_end(request);
 }
EVHTP_EXPORT evhtp_callback_t* evhtp_callback_new (const char * path, evhtp_callback_type type, evhtp_callback_cb cb, void * arg)
creates a new evhtp_callback_t structure.
All callbacks are stored in this structure which define what the final function to be called after all parsing is done. A callback can be either a static string or a regular expression.
Parameters
path can either be a static path (/path/to/resource/) or a POSIX compatible regular expression (^/resource/(.*))
type informs the function what type of of information is is contained within the path argument. This can either be callback_type_path, or callback_type_regex.
cb the callback function to be invoked
arg optional argument which is passed when the callback is executed.
Returns
0 on success, -1 on error.
References _evhtp_quick_hash(), cb, evhtp_alloc_assert, evhtp_callback_type_glob, evhtp_callback_type_hash, evhtp_callback_type_regex, and evhtp_safe_free.
Referenced by evhtp_set_cb(), evhtp_set_glob_cb(), and evhtp_set_regex_cb().
{
     evhtp_callback_t * hcb;
     hcb        = calloc(sizeof(evhtp_callback_t), 1);
     evhtp_alloc_assert(hcb);
     hcb->type  = type;
     hcb->cb    = cb;
     hcb->cbarg = arg;
     switch (type) {
         case evhtp_callback_type_hash:
             hcb->hash      = _evhtp_quick_hash(path);
             hcb->val.path  = strdup(path);
             break;
 #ifndef EVHTP_DISABLE_REGEX
         case evhtp_callback_type_regex:
             hcb->val.regex = malloc(sizeof(regex_t));
             if (regcomp(hcb->val.regex, (char *)path, REG_EXTENDED) != 0) {
                 evhtp_safe_free(hcb->val.regex, free);
                 evhtp_safe_free(hcb, free);
                 return NULL;
             }
             break;
 #endif
         case evhtp_callback_type_glob:
             hcb->val.glob = strdup(path);
             break;
         default:
             evhtp_safe_free(hcb, free);
             return NULL;
     } /* switch */
     return hcb;
 }
EVHTP_EXPORT void evhtp_callback_free (evhtp_callback_t * callback)
frees information associated with a ainflwx callback.
Parameters
callback
References evhtp_callback_type_glob, evhtp_callback_type_hash, evhtp_callback_type_regex, and evhtp_safe_free.
Referenced by evhtp_callbacks_free(), evhtp_set_cb(), evhtp_set_glob_cb(), and evhtp_set_regex_cb().
{
     if (callback == NULL) {
         return;
     }
     switch (callback->type) {
         case evhtp_callback_type_hash:
             evhtp_safe_free(callback->val.path, free);
             break;
         case evhtp_callback_type_glob:
             evhtp_safe_free(callback->val.glob, free);
             break;
 #ifndef EVHTP_DISABLE_REGEX
         case evhtp_callback_type_regex:
             regfree(callback->val.regex);
             evhtp_safe_free(callback->val.regex, free);
             break;
 #endif
     }
     if (callback->hooks) {
         evhtp_safe_free(callback->hooks, free);
     }
     evhtp_safe_free(callback, free);
     return;
 }
EVHTP_EXPORT int evhtp_callbacks_add_callback (evhtp_callbacks_t * cbs, evhtp_callback_t * cb)
Adds a evhtp_callback_t to the evhtp_callbacks_t list.
Parameters
cbs an allocated evhtp_callbacks_t structure
cb an initialized evhtp_callback_t structure
Returns
0 on success, -1 on error
Referenced by evhtp_set_cb(), evhtp_set_glob_cb(), and evhtp_set_regex_cb().
{
     TAILQ_INSERT_TAIL(cbs, cb, next);
     return 0;
 }
EVHTP_EXPORT int evhtp_add_vhost (evhtp_t * evhtp, const char * name, evhtp_t * vhost)
add an evhtp_t structure (with its own callbacks) to a base evhtp_t structure for virtual hosts. It should be noted that if you enable SSL on the base evhtp_t and your version of OpenSSL supports SNI, the SNI hostname will always take precedence over the Host header value.
Parameters
evhtp
name
vhost
Returns
add an evhtp_t structure (with its own callbacks) to a base evhtp_t structure for virtual hosts. It should be noted that if you enable SSL on the base evhtp_t and your version of OpenSSL supports SNI, the SNI hostname will always take precedence over the Host header value.
NOTE: If SSL is being used and the vhost was found via SNI, the Host: header will NOT be used to find a matching vhost.
Also, any hooks which are set prior to finding a vhost that are hooks which are after the host hook, they are overwritten by the callbacks and hooks set for the vhost specific evhtp_t structure.
Parameters
evhtp
name
vhost
Returns
Referenced by main().
{
     if (evhtp == NULL || name == NULL || vhost == NULL) {
         return -1;
     }
     if (TAILQ_FIRST(&vhost->vhosts) != NULL) {
         /* vhosts cannot have secondary vhosts defined */
         return -1;
     }
     if (!(vhost->server_name = strdup(name))) {
         return -1;
     }
     /* set the parent of this vhost so when the request has been completely
      * serviced, the vhost can be reset to the original evhtp structure.
      *
      * This allows for a keep-alive connection to make multiple requests with
      * different Host: values.
      */
     vhost->parent                 = evhtp;
     /* inherit various flags from the parent evhtp structure */
     vhost->bev_flags              = evhtp->bev_flags;
     vhost->max_body_size          = evhtp->max_body_size;
     vhost->max_keepalive_requests = evhtp->max_keepalive_requests;
     vhost->recv_timeo             = evhtp->recv_timeo;
     vhost->send_timeo             = evhtp->send_timeo;
     TAILQ_INSERT_TAIL(&evhtp->vhosts, vhost, next_vhost);
     return 0;
 }
EVHTP_EXPORT int evhtp_add_alias (evhtp_t * evhtp, const char * name)
Add an alias hostname for a virtual-host specific evhtp_t. This avoids having multiple evhtp_t virtual hosts with the same callback for the same vhost.
Parameters
evhtp
name
Returns
References evhtp_alloc_assert, and evhtp_unlikely.
Referenced by main().
{
     evhtp_alias_t * alias;
     if (evhtp_unlikely(evhtp == NULL || name == NULL)) {
         return -1;
     }
     if (!(alias = calloc(sizeof(evhtp_alias_t), 1))) {
         return -1;
     }
     alias->alias = strdup(name);
     evhtp_alloc_assert(alias->alias);
     TAILQ_INSERT_TAIL(&evhtp->aliases, alias, next);
     return 0;
 }
EVHTP_EXPORT evhtp_kv_t* evhtp_kv_new (const char * key, const char * val, char kalloc, char valloc)
Allocates a new key/value structure.
Parameters
key null terminated string
val null terminated string
kalloc if set to 1, the key will be copied, if 0 no copy is done.
valloc if set to 1, the val will be copied, if 0 no copy is done.
Returns
evhtp_kv_t * on success, NULL on error.
References evhtp_alloc_assert, and evhtp_safe_free.
Referenced by evhtp_kvs_add_kvs(), and evhtp_parse_query_wflags().
{
     evhtp_kv_t * kv;
     kv           = malloc(sizeof(evhtp_kv_t));
     evhtp_alloc_assert(kv);
     kv->k_heaped = kalloc;
     kv->v_heaped = valloc;
     kv->klen     = 0;
     kv->vlen     = 0;
     kv->key      = NULL;
     kv->val      = NULL;
     if (key != NULL) {
         kv->klen = strlen(key);
         if (kalloc == 1) {
             char * s;
             if (!(s = malloc(kv->klen + 1))) {
                 evhtp_safe_free(kv, free);
                 return NULL;
             }
             memcpy(s, key, kv->klen);
             s[kv->klen] = '\0';
             kv->key     = s;
         } else {
             kv->key = (char *)key;
         }
     }
     if (val != NULL) {
         kv->vlen = strlen(val);
         if (valloc == 1) {
             char * s = malloc(kv->vlen + 1);
             s[kv->vlen] = '\0';
             memcpy(s, val, kv->vlen);
             kv->val     = s;
         } else {
             kv->val = (char *)val;
         }
     }
     return kv;
 }     /* evhtp_kv_new */
EVHTP_EXPORT evhtp_kvs_t* evhtp_kvs_new (void)
creates an empty list of key/values
Returns
References evhtp_alloc_assert.
                     {
     evhtp_kvs_t * kvs;
     kvs = malloc(sizeof(evhtp_kvs_t));
     evhtp_alloc_assert(kvs);
     TAILQ_INIT(kvs);
     return kvs;
 }
EVHTP_EXPORT void evhtp_kv_free (evhtp_kv_t * kv)
frees resources allocated for a single key/value
Parameters
kv
References evhtp_safe_free, and evhtp_unlikely.
Referenced by evhtp_kv_rm_and_free(), and evhtp_kvs_free().
{
     if (evhtp_unlikely(kv == NULL)) {
         return;
     }
     if (kv->k_heaped) {
         evhtp_safe_free(kv->key, free);
     }
     if (kv->v_heaped) {
         evhtp_safe_free(kv->val, free);
     }
     evhtp_safe_free(kv, free);
 }
EVHTP_EXPORT void evhtp_kvs_free (evhtp_kvs_t * kvs)
frees a the list of key/values, and all underlying entries
Parameters
kvs
References evhtp_kv_free(), evhtp_safe_free, and evhtp_unlikely.
{
     evhtp_kv_t * kv;
     evhtp_kv_t * save;
     if (evhtp_unlikely(kvs == NULL)) {
         return;
     }
     for (kv = TAILQ_FIRST(kvs); kv != NULL; kv = save) {
         save = TAILQ_NEXT(kv, next);
         TAILQ_REMOVE(kvs, kv, next);
         evhtp_safe_free(kv, evhtp_kv_free);
     }
     evhtp_safe_free(kvs, free);
 }
EVHTP_EXPORT void evhtp_kv_rm_and_free (evhtp_kvs_t * kvs, evhtp_kv_t * kv)
free's resources associated with 'kv' if ONLY found within the key/value list
Parameters
kvs
kv
References evhtp_kv_free(), and evhtp_unlikely.
Referenced by evhtp_send_reply_chunk_start().
{
     if (evhtp_unlikely(kvs == NULL || kv == NULL)) {
         return;
     }
     TAILQ_REMOVE(kvs, kv, next);
     evhtp_kv_free(kv);
 }
EVHTP_EXPORT const char* evhtp_kv_find (evhtp_kvs_t * kvs, const char * key)
find the string value of 'key' from the key/value list 'kvs'
Parameters
kvs
key
Returns
NULL if not found
References evhtp_unlikely.
Referenced by _evhtp_should_parse_query_body(), and query_test().
{
     evhtp_kv_t * kv;
     if (evhtp_unlikely(kvs == NULL || key == NULL)) {
         return NULL;
     }
     TAILQ_FOREACH(kv, kvs, next) {
         if (strcasecmp(kv->key, key) == 0) {
             return kv->val;
         }
     }
     return NULL;
 }
EVHTP_EXPORT evhtp_kv_t* evhtp_kvs_find_kv (evhtp_kvs_t * kvs, const char * key)
find the evhtp_kv_t reference 'key' from the k/val list 'kvs'
Parameters
kvs
key
Returns
References evhtp_unlikely.
Referenced by query_test().
{
     evhtp_kv_t * kv;
     if (evhtp_unlikely(kvs == NULL || key == NULL)) {
         return NULL;
     }
     TAILQ_FOREACH(kv, kvs, next) {
         if (strcasecmp(kv->key, key) == 0) {
             return kv;
         }
     }
     return NULL;
 }
EVHTP_EXPORT void evhtp_kvs_add_kv (evhtp_kvs_t * kvs, evhtp_kv_t * kv)
appends a key/val structure to a evhtp_kvs_t tailq
Parameters
kvs an evhtp_kvs_t structure
kv an evhtp_kv_t structure
References evhtp_unlikely.
Referenced by evhtp_kvs_add_kvs(), and evhtp_parse_query_wflags().
{
     if (evhtp_unlikely(kvs == NULL || kv == NULL)) {
         return;
     }
     TAILQ_INSERT_TAIL(kvs, kv, next);
 }
EVHTP_EXPORT void evhtp_kvs_add_kvs (evhtp_kvs_t * dst, evhtp_kvs_t * src)
appends all key/val structures from src tailq onto dst tailq
Parameters
dst an evhtp_kvs_t structure
src an evhtp_kvs_t structure
References evhtp_kv_new(), and evhtp_kvs_add_kv().
{
     if (dst == NULL || src == NULL) {
         return;
     }
     evhtp_kv_t * kv;
     TAILQ_FOREACH(kv, src, next) {
         evhtp_kvs_add_kv(dst, evhtp_kv_new(kv->key,
                                            kv->val,
                                            kv->k_heaped,
                                            kv->v_heaped));
     }
 }
EVHTP_EXPORT int evhtp_kvs_for_each (evhtp_kvs_t * kvs, evhtp_kvs_iterator cb, void * arg)
callback iterator which executes 'cb' for every entry in 'kvs'
Parameters
kvs
cb
arg
Returns
References cb.
Referenced by query_test().
{
     evhtp_kv_t * kv;
     if (kvs == NULL || cb == NULL) {
         return -1;
     }
     TAILQ_FOREACH(kv, kvs, next) {
         int res;
         if ((res = cb(kv, arg))) {
             return res;
         }
     }
     return 0;
 }
EVHTP_EXPORT evhtp_query_t* evhtp_parse_query_wflags (const char * query, size_t len, int flags)
Parses the query portion of the uri into a set of key/values.
Parses query arguments like "?herp=&foo=bar;blah=baz&a=%3"
Parameters
query data containing the uri query arguments
len size of the data
flags parse query flags to alter 'strictness' (see EVHTP_PARSE_QUERY_FLAG_*)
Returns
evhtp_query_t * on success, NULL on error
References evhtp_alloc_assert, evhtp_is_hex_query_char(), evhtp_kv_new(), evhtp_kvs_add_kv(), EVHTP_PARSE_QUERY_FLAG_ALLOW_EMPTY_VALS, EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS, EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX, EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP, evhtp_query_free, evhtp_query_new, evhtp_query_t, evhtp_safe_free, s_query_key, s_query_key_hex_1, s_query_key_hex_2, s_query_start, s_query_val, s_query_val_hex_1, and s_query_val_hex_2.
Referenced by _evhtp_request_parser_args(), evhtp_parse_query(), and query_test().
{
     evhtp_query_t    * query_args;
     query_parser_state state;
     size_t             key_idx;
     size_t             val_idx;
     unsigned char      ch;
     size_t             i;
     if (len > (SIZE_MAX - (len + 2))) {
         return NULL;
     }
     query_args = evhtp_query_new();
     state      = s_query_start;
     key_idx    = 0;
     val_idx    = 0;
 #ifdef EVHTP_HAS_C99
     char   key_buf[len + 1];
     char   val_buf[len + 1];
 #else
     char * key_buf;
     char * val_buf;
     key_buf = malloc(len + 1);
     evhtp_alloc_assert(key_buf);
     val_buf = malloc(len + 1);
     evhtp_alloc_assert(val_buf);
 #endif
     for (i = 0; i < len; i++) {
         ch = query[i];
         if (key_idx >= len || val_idx >= len) {
             goto error;
         }
         switch (state) {
             case s_query_start:
                 key_idx    = 0;
                 val_idx    = 0;
                 key_buf[0] = '\0';
                 val_buf[0] = '\0';
                 state      = s_query_key;
             /* Fall through. */
             case s_query_key:
                 switch (ch) {
                     case '=':
                         state = s_query_val;
                         break;
                     case '%':
                         key_buf[key_idx++] = ch;
                         key_buf[key_idx]   = '\0';
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX)) {
                             state = s_query_key_hex_1;
                         }
                         break;
                     case ';':
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP)) {
                             key_buf[key_idx++] = ch;
                             key_buf[key_idx]   = '\0';
                             break;
                         }
                     /* otherwise we fallthrough */
                     case '&':
                         /* in this state, we have a NULL value */
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS)) {
                             goto error;
                         }
                         /* insert the key with value of NULL and set the
                          * state back to parsing s_query_key.
                          */
                         evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, NULL, 1, 1));
                         key_idx            = 0;
                         val_idx            = 0;
                         key_buf[0]         = '\0';
                         val_buf[0]         = '\0';
                         state              = s_query_key;
                         break;
                     default:
                         key_buf[key_idx++] = ch;
                         key_buf[key_idx]   = '\0';
                         break;
                 } /* switch */
                 break;
             case s_query_key_hex_1:
                 if (!evhtp_is_hex_query_char(ch)) {
                     /* not hex, so we treat as a normal key */
                     if ((key_idx + 2) >= len) {
                         /* we need to insert \%<ch>, but not enough space */
                         goto error;
                     }
                     key_buf[key_idx - 1] = '%';
                     key_buf[key_idx++]   = ch;
                     key_buf[key_idx]     = '\0';
                     state = s_query_key;
                     break;
                 }
                 key_buf[key_idx++] = ch;
                 key_buf[key_idx]   = '\0';
                 state = s_query_key_hex_2;
                 break;
             case s_query_key_hex_2:
                 if (!evhtp_is_hex_query_char(ch)) {
                     goto error;
                 }
                 key_buf[key_idx++] = ch;
                 key_buf[key_idx]   = '\0';
                 state = s_query_key;
                 break;
             case s_query_val:
                 switch (ch) {
                     case ';':
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP)) {
                             val_buf[val_idx++] = ch;
                             val_buf[val_idx]   = '\0';
                             break;
                         }
                     case '&':
                         evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, val_buf, 1, 1));
                         key_idx            = 0;
                         val_idx            = 0;
                         key_buf[0]         = '\0';
                         val_buf[0]         = '\0';
                         state              = s_query_key;
                         break;
                     case '%':
                         val_buf[val_idx++] = ch;
                         val_buf[val_idx]   = '\0';
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX)) {
                             state = s_query_val_hex_1;
                         }
                         break;
                     default:
                         val_buf[val_idx++] = ch;
                         val_buf[val_idx]   = '\0';
                         break;
                 }     /* switch */
                 break;
             case s_query_val_hex_1:
                 if (!evhtp_is_hex_query_char(ch)) {
                     /* not really a hex val */
                     if ((val_idx + 2) >= len) {
                         /* we need to insert \%<ch>, but not enough space */
                         goto error;
                     }
                     if (val_idx == 0) {
                         goto error;
                     }
                     val_buf[val_idx - 1] = '%';
                     val_buf[val_idx++]   = ch;
                     val_buf[val_idx]     = '\0';
                     state = s_query_val;
                     break;
                 }
                 val_buf[val_idx++] = ch;
                 val_buf[val_idx]   = '\0';
                 state = s_query_val_hex_2;
                 break;
             case s_query_val_hex_2:
                 if (!evhtp_is_hex_query_char(ch)) {
                     goto error;
                 }
                 val_buf[val_idx++] = ch;
                 val_buf[val_idx]   = '\0';
                 state = s_query_val;
                 break;
             default:
                 /* bad state */
                 goto error;
         }       /* switch */
     }
     if (key_idx) {
         do {
             if (val_idx) {
                 evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, val_buf, 1, 1));
                 break;
             }
             if (state >= s_query_val) {
                 if (!(flags & EVHTP_PARSE_QUERY_FLAG_ALLOW_EMPTY_VALS)) {
                     goto error;
                 }
                 evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, "", 1, 1));
                 break;
             }
             if (!(flags & EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS)) {
                 goto error;
             }
             evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, NULL, 1, 0));
         } while (0);
     }
 #ifndef EVHTP_HAS_C99
     evhtp_safe_free(key_buf, free);
     evhtp_safe_free(val_buf, free);
 #endif
     return query_args;
 error:
 #ifndef EVHTP_HAS_C99
     evhtp_safe_free(key_buf, free);
     evhtp_safe_free(val_buf, free);
 #endif
     evhtp_query_free(query_args);
     return NULL;
 }     /* evhtp_parse_query */
EVHTP_EXPORT evhtp_query_t* evhtp_parse_query (const char * query, size_t len)
Parses the query portion of the uri into a set of key/values in a strict manner.
Parses query arguments like "?herp=derp&foo=bar&blah=baz"
Parameters
query data containing the uri query arguments
len size of the data
Returns
evhtp_query_t * on success, NULL on error
References EVHTP_PARSE_QUERY_FLAG_STRICT, and evhtp_parse_query_wflags().
Referenced by _evhtp_request_parser_fini().
{
     return evhtp_parse_query_wflags(query, len,
                                     EVHTP_PARSE_QUERY_FLAG_STRICT);
 }
EVHTP_EXPORT int evhtp_unescape_string (unsigned char ** out, unsigned char * str, size_t str_len)
Unescapes strings like '%7B1,%202,%203%7D' would become '{1, 2, 3}'.
Parameters
out double pointer where output is stored. This is allocated by the user.
str the string to unescape
str_len the length of the string to unescape
Returns
0 on success, -1 on error
References unscape_state_hex1, unscape_state_hex2, and unscape_state_start.
{
     unsigned char    * optr;
     unsigned char    * sptr;
     unsigned char      d;
     unsigned char      ch;
     unsigned char      c;
     size_t             i;
     enum unscape_state state;
     if (out == NULL || *out == NULL) {
         return -1;
     }
     state = unscape_state_start;
     optr  = *out;
     sptr  = str;
     d     = 0;
     for (i = 0; i < str_len; i++) {
         ch = *sptr++;
         switch (state) {
             case unscape_state_start:
                 if (ch == '%') {
                     state = unscape_state_hex1;
                     break;
                 }
                 *optr++ = ch;
                 break;
             case unscape_state_hex1:
                 if (ch >= '0' && ch <= '9') {
                     d     = (unsigned char)(ch - '0');
                     state = unscape_state_hex2;
                     break;
                 }
                 c = (unsigned char)(ch | 0x20);
                 if (c >= 'a' && c <= 'f') {
                     d     = (unsigned char)(c - 'a' + 10);
                     state = unscape_state_hex2;
                     break;
                 }
                 state   = unscape_state_start;
                 *optr++ = ch;
                 break;
             case unscape_state_hex2:
                 state   = unscape_state_start;
                 if (ch >= '0' && ch <= '9') {
                     ch      = (unsigned char)((d << 4) + ch - '0');
                     *optr++ = ch;
                     break;
                 }
                 c = (unsigned char)(ch | 0x20);
                 if (c >= 'a' && c <= 'f') {
                     ch      = (unsigned char)((d << 4) + c - 'a' + 10);
                     *optr++ = ch;
                     break;
                 }
                 break;
         } /* switch */
     }
     return 0;
 }         /* evhtp_unescape_string */
EVHTP_EXPORT evhtp_header_t* evhtp_header_new (const char * key, const char * val, char kalloc, char valloc)
creates a new evhtp_header_t key/val structure
Parameters
key a null terminated string
val a null terminated string
kalloc if 1, key will be copied, otherwise no copy performed
valloc if 1, val will be copied, otehrwise no copy performed
Returns
evhtp_header_t * or NULL on error
Referenced by _evhtp_create_reply(), _evhtp_default_request_cb(), evhtp_header_key_add(), evhtp_send_reply_chunk_start(), main(), and make_request().
EVHTP_EXPORT evhtp_header_t* evhtp_header_key_add (evhtp_headers_t * headers, const char * key, char kalloc)
creates a new evhtp_header_t, sets only the key, and adds to the evhtp_headers TAILQ
Parameters
headers the evhtp_headers_t TAILQ (evhtp_kv_t)
key a null terminated string
kalloc if 1 the string will be copied, otherwise assigned
Returns
an evhtp_header_t pointer or NULL on error
References evhtp_header_new(), evhtp_header_t, and evhtp_headers_add_header().
Referenced by _evhtp_request_parser_header_key().
{
     evhtp_header_t * header;
     if (!(header = evhtp_header_new(key, NULL, kalloc, 0))) {
         return NULL;
     }
     evhtp_headers_add_header(headers, header);
     return header;
 }
EVHTP_EXPORT evhtp_header_t* evhtp_header_val_add (evhtp_headers_t * headers, const char * val, char valloc)
finds the last header in the headers tailq and adds the value
Parameters
headers the evhtp_headers_t TAILQ (evhtp_kv_t)
val a null terminated string
valloc if 1 the string will be copied, otherwise assigned
Returns
an evhtp_header_t pointer or NULL on error
References evhtp_header_t, and evhtp_headers_s.
Referenced by _evhtp_request_parser_header_val().
{
     evhtp_header_t * header;
     if (!headers || !val) {
         return NULL;
     }
     if (!(header = TAILQ_LAST(headers, evhtp_headers_s))) {
         return NULL;
     }
     if (header->val != NULL) {
         return NULL;
     }
     header->vlen = strlen(val);
     if (valloc == 1) {
         header->val = malloc(header->vlen + 1);
         header->val[header->vlen] = '\0';
         memcpy(header->val, val, header->vlen);
     } else {
         header->val = (char *)val;
     }
     header->v_heaped = valloc;
     return header;
 }
EVHTP_EXPORT void evhtp_headers_add_header (evhtp_headers_t * headers, evhtp_header_t * header)
adds an evhtp_header_t to the end of the evhtp_headers_t tailq
Parameters
headers
header
Referenced by _evhtp_create_reply(), _evhtp_default_request_cb(), evhtp_header_key_add(), evhtp_send_reply_chunk_start(), main(), and make_request().
EVHTP_EXPORT const char* evhtp_header_find (evhtp_headers_t * headers, const char * key)
finds the value of a key in a evhtp_headers_t structure
Parameters
headers the evhtp_headers_t tailq
key the key to find
Returns
the value of the header key if found, NULL if not found.
Referenced by _evhtp_create_reply(), and _evhtp_request_parser_headers().
EVHTP_EXPORT htp_method evhtp_request_get_method (evhtp_request_t * r)
returns the htp_method enum version of the request method.
Parameters
r
Returns
htp_method enum
References evhtp_assert, and htparser_get_method().
Referenced by print_path().
{
     evhtp_assert(r != NULL);
     evhtp_assert(r->conn != NULL);
     evhtp_assert(r->conn->parser != NULL);
     return htparser_get_method(r->conn->parser);
 }
EVHTP_EXPORT evhtp_proto evhtp_request_get_proto (evhtp_request_t * r)
Referenced by issue161cb().
{
     return request->proto;
 }
EVHTP_EXPORT void evhtp_connection_pause (evhtp_connection_t * c)
pauses a connection (disables reading)
Parameters
c a evhtp_connection_t * structure
References evhtp_assert.
Referenced by evhtp_request_pause().
{
     evhtp_assert(c != NULL);
     c->paused = 1;
     bufferevent_disable(c->bev, EV_READ | EV_WRITE);
     return;
 }
EVHTP_EXPORT void evhtp_connection_resume (evhtp_connection_t * c)
resumes a connection (enables reading) and activates resume event.
Parameters
c
References evhtp_assert.
Referenced by _evhtp_connection_readcb(), and evhtp_request_resume().
{
     evhtp_assert(c != NULL);
     c->paused = 0;
     event_active(c->resume_ev, EV_WRITE, 1);
     return;
 }
EVHTP_EXPORT void evhtp_request_pause (evhtp_request_t * request)
Wrapper around evhtp_connection_pause.
See also
evhtp_connection_pause
Parameters
request
References evhtp_assert, evhtp_connection_pause(), and EVHTP_RES_PAUSE.
Referenced by _evhtp_connection_readcb(), app_process_request(), and frontend_cb().
{
     evhtp_assert(request != NULL);
     request->status = EVHTP_RES_PAUSE;
     evhtp_connection_pause(request->conn);
 }
EVHTP_EXPORT void evhtp_request_resume (evhtp_request_t * request)
Wrapper around evhtp_connection_resume.
See also
evhtp_connection_resume
Parameters
request
References evhtp_assert, and evhtp_connection_resume().
Referenced by backend_cb(), redis_get_srcport_cb(), and resume_request_timer().
{
     evhtp_assert(request != NULL);
     evhtp_connection_resume(request->conn);
 }
EVHTP_EXPORT evhtp_connection_t* evhtp_request_get_connection (evhtp_request_t * request)
returns the underlying evhtp_connection_t structure from a request
Parameters
request
Returns
evhtp_connection_t on success, otherwise NULL
Referenced by app_process_request(), evhtp_request_take_ownership(), evhtp_send_reply(), evhtp_send_reply_start(), get_request_thr(), and test_ownership().
{
     return request->conn;
 }
EVHTP_EXPORT void evhtp_connection_set_bev (evhtp_connection_t * conn, evbev_t * bev)
Sets the connections underlying bufferevent.
Parameters
conn
bev
Referenced by evhtp_connection_take_ownership(), and evhtp_request_set_bev().
{
     conn->bev = bev;
 }
EVHTP_EXPORT void evhtp_request_set_bev (evhtp_request_t * request, evbev_t * bev)
sets the underlying bufferevent for a evhtp_request
Parameters
request
bev
References evhtp_connection_set_bev().
{
     evhtp_connection_set_bev(request->conn, bev);
 }
EVHTP_EXPORT evbev_t* evhtp_connection_get_bev (evhtp_connection_t * conn)
returns the underlying connections bufferevent
Parameters
conn
Returns
bufferevent on success, otherwise NULL
Referenced by evhtp_connection_take_ownership(), evhtp_request_get_bev(), and evhtp_send_reply().
{
     return connection->bev;
 }
EVHTP_EXPORT void evhtp_connection_set_timeouts (evhtp_connection_t * conn, const struct timeval * r, const struct timeval * w) inline
sets a connection-specific read/write timeout which overrides the global read/write settings.
Parameters
conn
r timeval for read
w timeval for write
References evhtp_unlikely.
Referenced by _evhtp_connection_accept().
{
     if (evhtp_unlikely(c == NULL)) {
         return;
     }
     bufferevent_set_timeouts(c->bev, rtimeo, wtimeo);
 }
EVHTP_EXPORT evbev_t* evhtp_request_get_bev (evhtp_request_t * request)
returns the underlying requests bufferevent
Parameters
request
Returns
bufferevent on success, otherwise NULL
References evhtp_connection_get_bev().
Referenced by evhtp_send_reply_chunk_end().
{
     return evhtp_connection_get_bev(request->conn);
 }
EVHTP_EXPORT evbev_t* evhtp_connection_take_ownership (evhtp_connection_t * connection)
let a user take ownership of the underlying bufferevent and free all other underlying resources.
Warning: this will free all evhtp_connection/request structures, remove all associated hooks and reset the bufferevent to defaults, i.e., disable EV_READ, and set all callbacks to NULL.
Parameters
connection
Returns
underlying connections bufferevent.
References evhtp_connection_get_bev(), evhtp_connection_set_bev(), and evhtp_unset_all_hooks().
Referenced by evhtp_request_take_ownership(), and test_ownership().
{
     evbev_t * bev = evhtp_connection_get_bev(connection);
     if (connection->hooks) {
         evhtp_unset_all_hooks(&connection->hooks);
     }
     if (connection->request && connection->request->hooks) {
         evhtp_unset_all_hooks(&connection->request->hooks);
     }
     evhtp_connection_set_bev(connection, NULL);
     connection->owner = 0;
     bufferevent_disable(bev, EV_READ);
     bufferevent_setcb(bev, NULL, NULL, NULL, NULL);
     return bev;
 }
EVHTP_EXPORT void evhtp_connection_free (evhtp_connection_t * connection)
free's all connection related resources, this will also call your request fini hook and request fini hook.
Parameters
connection
References _evhtp_connection_fini_hook(), _evhtp_request_free(), evhtp_safe_free, and evhtp_unlikely.
Referenced by _evhtp_accept_cb(), _evhtp_connection_eventcb(), _evhtp_connection_readcb(), _evhtp_connection_resumecb(), _evhtp_connection_writecb(), _evhtp_run_in_thread(), evhtp_connection_new_dns(), evhtp_send_reply(), and evhtp_send_reply_start().
{
     if (evhtp_unlikely(connection == NULL)) {
         return;
     }
     _evhtp_connection_fini_hook(connection);
     evhtp_safe_free(connection->request, _evhtp_request_free);
     evhtp_safe_free(connection->parser, free);
     evhtp_safe_free(connection->hooks, free);
     evhtp_safe_free(connection->saddr, free);
     evhtp_safe_free(connection->scratch_buf, evbuffer_free);
     if (connection->resume_ev) {
         evhtp_safe_free(connection->resume_ev, event_free);
     }
     if (connection->bev) {
 #ifdef LIBEVENT_HAS_SHUTDOWN
         bufferevent_shutdown(connection->bev, _evhtp_shutdown_eventcb);
 #else
 #ifndef EVHTP_DISABLE_SSL
         if (connection->ssl != NULL) {
             SSL_set_shutdown(connection->ssl, SSL_RECEIVED_SHUTDOWN);
             SSL_shutdown(connection->ssl);
         }
 #endif
         bufferevent_free(connection->bev);
 #endif
     }
     evhtp_safe_free(connection, free);
 }     /* evhtp_connection_free */
EVHTP_EXPORT void evhtp_request_free (evhtp_request_t * request)
References _evhtp_request_free().
{
     _evhtp_request_free(request);
 }
EVHTP_EXPORT void evhtp_set_max_body_size (evhtp_t * htp, uint64_t len)
set a max body size to accept for an incoming request, this will default to unlimited.
Parameters
htp
len
{
     htp->max_body_size = len;
 }
EVHTP_EXPORT void evhtp_connection_set_max_body_size (evhtp_connection_t * conn, uint64_t len)
set a max body size for a specific connection, this will default to the size set by evhtp_set_max_body_size
Parameters
conn
len
Referenced by evhtp_request_set_max_body_size().
{
     if (len == 0) {
         c->max_body_size = c->htp->max_body_size;
     } else {
         c->max_body_size = len;
     }
 }
EVHTP_EXPORT void evhtp_request_set_max_body_size (evhtp_request_t * request, uint64_t len)
just calls evhtp_connection_set_max_body_size for the request.
Parameters
request
len
References evhtp_connection_set_max_body_size().
Referenced by set_max_body().
{
     evhtp_connection_set_max_body_size(req->conn, len);
 }
EVHTP_EXPORT void evhtp_request_set_keepalive (evhtp_request_t * request, int val)
Referenced by issue161cb().
{
     request->keepalive = (val > 0) ? 1 : 0;
 }
EVHTP_EXPORT void evhtp_set_max_keepalive_requests (evhtp_t * htp, uint64_t num)
sets a maximum number of requests that a single connection can make.
Parameters
htp
num
Referenced by main().
{
     htp->max_keepalive_requests = num;
 }
EVHTP_EXPORT evhtp_connection_t* evhtp_connection_new_dns (evbase_t * evbase, struct evdns_base * dns_base, const char * addr, uint16_t port)
allocate a new connection
References _evhtp_connection_eventcb(), _evhtp_connection_new(), evhtp_assert, evhtp_connection_free(), and evhtp_type_client.
Referenced by evhtp_connection_new().
{
     evhtp_connection_t * conn;
     int                  err;
     evhtp_assert(evbase != NULL);
     if (!(conn = _evhtp_connection_new(NULL, -1, evhtp_type_client))) {
         return NULL;
     }
     conn->evbase = evbase;
     conn->bev    = bufferevent_socket_new(evbase, -1, BEV_OPT_CLOSE_ON_FREE);
     if (conn->bev == NULL) {
         evhtp_connection_free(conn);
         return NULL;
     }
     bufferevent_enable(conn->bev, EV_READ);
     bufferevent_setcb(conn->bev, NULL, NULL,
                       _evhtp_connection_eventcb, conn);
     if (dns_base != NULL) {
         err = bufferevent_socket_connect_hostname(conn->bev, dns_base,
                                                   AF_UNSPEC, addr, port);
     } else {
         struct sockaddr_in  sin4;
         struct sockaddr_in6 sin6;
         struct sockaddr   * sin;
         int                 salen;
         if (inet_pton(AF_INET, addr, &sin4.sin_addr)) {
             sin4.sin_family = AF_INET;
             sin4.sin_port   = htons(port);
             sin = (struct sockaddr *)&sin4;
             salen           = sizeof(sin4);
         } else if (inet_pton(AF_INET6, addr, &sin6.sin6_addr)) {
             sin6.sin6_family = AF_INET6;
             sin6.sin6_port   = htons(port);
             sin = (struct sockaddr *)&sin6;
             salen = sizeof(sin6);
         } else {
             /* Not a valid IP. */
             evhtp_connection_free(conn);
             return NULL;
         }
         err = bufferevent_socket_connect(conn->bev, sin, salen);
     }
     /* not needed since any of the bufferevent errors will go straight to
      * the eventcb
      */
     if (err) {
         return NULL;
     }
     return conn;
 } /* evhtp_connection_new_dns */
EVHTP_EXPORT evhtp_connection_t* evhtp_connection_new (evbase_t * evbase, const char * addr, uint16_t port)
allocate a new connection
References evhtp_connection_new_dns().
Referenced by main(), and make_request().
{
     return evhtp_connection_new_dns(evbase, NULL, addr, port);
 }
EVHTP_EXPORT evhtp_connection_t* evhtp_connection_ssl_new (evbase_t * evbase, const char * addr, uint16_t port, evhtp_ssl_ctx_t * ctx)
References _evhtp_connection_eventcb(), _evhtp_connection_new(), evhtp_assert, and evhtp_type_client.
{
     evhtp_connection_t * conn;
     struct sockaddr_in   sin;
     evhtp_assert(evbase != NULL);
     if (!(conn = _evhtp_connection_new(NULL, -1, evhtp_type_client))) {
         return NULL;
     }
     sin.sin_family      = AF_INET;
     sin.sin_addr.s_addr = inet_addr(addr);
     sin.sin_port        = htons(port);
     conn->ssl           = SSL_new(ctx);
     conn->evbase        = evbase;
     conn->bev           = bufferevent_openssl_socket_new(evbase, -1, conn->ssl,
                                                          BUFFEREVENT_SSL_CONNECTING, BEV_OPT_CLOSE_ON_FREE);
     bufferevent_enable(conn->bev, EV_READ);
     bufferevent_setcb(conn->bev, NULL, NULL,
                       _evhtp_connection_eventcb, conn);
     bufferevent_socket_connect(conn->bev,
                                (struct sockaddr *)&sin, sizeof(sin));
     return conn;
 }
EVHTP_EXPORT evhtp_request_t* evhtp_request_new (evhtp_callback_cb cb, void * arg)
allocate a new request
References _evhtp_request_new(), cb, evhtp_alloc_assert, and EVHTP_PROTO_11.
Referenced by main(), and make_request().
{
     evhtp_request_t * r;
     r        = _evhtp_request_new(NULL);
     evhtp_alloc_assert(r);
     r->cb    = cb;
     r->cbarg = arg;
     r->proto = EVHTP_PROTO_11;
     return r;
 }
EVHTP_EXPORT int evhtp_make_request (evhtp_connection_t * c, evhtp_request_t * r, htp_method meth, const char * uri)
make a client request
References _evhtp_create_headers(), evhtp_headers_for_each, EVHTP_PROTO_10, EVHTP_PROTO_11, and htparser_get_methodstr_m().
Referenced by main(), and make_request().
{
     evbuf_t * obuf;
     char    * proto;
     obuf       = bufferevent_get_output(c->bev);
     r->conn    = c;
     c->request = r;
     switch (r->proto) {
         case EVHTP_PROTO_10:
             proto = "1.0";
             break;
         case EVHTP_PROTO_11:
         default:
             proto = "1.1";
             break;
     }
     evbuffer_add_printf(obuf, "%s %s HTTP/%s\r\n",
                         htparser_get_methodstr_m(meth), uri, proto);
     evhtp_headers_for_each(r->headers_out, _evhtp_create_headers, obuf);
     evbuffer_add_reference(obuf, "\r\n", 2, NULL, NULL);
     if (evbuffer_get_length(r->buffer_out)) {
         evbuffer_add_buffer(obuf, r->buffer_out);
     }
     return 0;
 }
EVHTP_EXPORT unsigned int evhtp_request_status (evhtp_request_t *)
References htparser_get_status().
{
     return htparser_get_status(r->conn->parser);
 }