Libevhtp: evhtp.c File Reference
evhtp.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <signal.h>
#include <strings.h>
#include <inttypes.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <arpa/inet.h>
#include <sys/un.h>
#include <limits.h>
#include <event2/dns.h>
#include "evhtp-internal.h"
#include "evhtp_numtoa.h"
#include "evhtp.h"
Macros
#define HOOK_AVAIL(var, hook_name) (var->hooks && var->hooks->hook_name)
#define HOOK_FUNC(var, hook_name) (var->hooks->hook_name)
#define HOOK_ARGS(var, hook_name) var->hooks->hook_name ## _arg
#define HOOK_REQUEST_RUN(request, hook_name, ...)
#define HOOK_REQUEST_RUN_NARGS(request, hook_name)
#define HOOK_CONN_RUN(conn, hook_name, ...)
#define _evhtp_lock(h)
#define _evhtp_unlock(h)
#define _evhtp_is_http_11(_major, _minor) (_major >= 1 && _minor >= 1)
helper macro to determine if http version is HTTP/1.0
#define _evhtp_is_http_10(_major, _minor) (_major >= 1 && _minor <= 0)
helper function to determine if http version is HTTP/1.1
Enumerations
enum query_parser_state {
s_query_start = 0, s_query_separator, s_query_key, s_query_val,
s_query_key_hex_1, s_query_key_hex_2, s_query_val_hex_1, s_query_val_hex_2,
s_query_done
}
enum unscape_state { unscape_state_start = 0, unscape_state_hex1, unscape_state_hex2 }
Functions
static int _evhtp_request_parser_start (htparser *p)
static int _evhtp_request_parser_host (htparser *p, const char *data, size_t len)
static int _evhtp_request_parser_port (htparser *p, const char *data, size_t len)
static int _evhtp_request_parser_path (htparser *p, const char *data, size_t len)
static int _evhtp_request_parser_args (htparser *p, const char *data, size_t len)
static int _evhtp_request_parser_header_key (htparser *p, const char *data, size_t len)
static int _evhtp_request_parser_header_val (htparser *p, const char *data, size_t len)
static int _evhtp_request_parser_hostname (htparser *p, const char *data, size_t len)
static int _evhtp_request_parser_headers (htparser *p)
static int _evhtp_request_parser_body (htparser *p, const char *data, size_t len)
static int _evhtp_request_parser_fini (htparser *p)
static int _evhtp_request_parser_chunk_new (htparser *p)
static int _evhtp_request_parser_chunk_fini (htparser *p)
static int _evhtp_request_parser_chunks_fini (htparser *p)
static int _evhtp_request_parser_headers_start (htparser *p)
static void _evhtp_connection_readcb (evbev_t *bev, void *arg)
static evhtp_connection_t * _evhtp_connection_new (evhtp_t *htp, evutil_socket_t sock, evhtp_type type)
static evhtp_uri_t * _evhtp_uri_new (void)
create an overlay URI structure
static void _evhtp_uri_free (evhtp_uri_t *uri)
frees an overlay URI structure
static evhtp_authority_t * _evhtp_authority_new (void)
create an authority structure
static void _evhtp_authority_free (evhtp_authority_t *authority)
frees an authority structure
static evhtp_path_t * _evhtp_path_new (const char *data, size_t len)
parses the path and file from an input buffer
static void _evhtp_path_free (evhtp_path_t *path)
static void _evhtp_request_free (evhtp_request_t *request)
frees all data in an evhtp_request_t along with calling finished hooks
static const char * status_code_to_str (evhtp_res code)
static unsigned int _evhtp_quick_hash (const char *str)
a weak hash function
static evhtp_proto _evhtp_protocol (const char major, const char minor)
returns the HTTP protocol version
static evhtp_res _evhtp_path_hook (evhtp_request_t *request, evhtp_path_t *path)
runs the user-defined on_path hook for a request
static evhtp_res _evhtp_header_hook (evhtp_request_t *request, evhtp_header_t *header)
runs the user-defined on_header hook for a request
static evhtp_res _evhtp_headers_hook (evhtp_request_t *request, evhtp_headers_t *headers)
runs the user-defined on_Headers hook for a request after all headers have been parsed.
static evhtp_res _evhtp_body_hook (evhtp_request_t *request, evbuf_t *buf)
runs the user-defined on_body hook for requests containing a body. the data is stored in the request->buffer_in so the user may either leave it, or drain upon being called.
static evhtp_res _evhtp_request_fini_hook (evhtp_request_t *request)
runs the user-defined hook called just prior to a request been free()'d
static evhtp_res _evhtp_chunk_new_hook (evhtp_request_t *request, uint64_t len)
static evhtp_res _evhtp_chunk_fini_hook (evhtp_request_t *request)
static evhtp_res _evhtp_chunks_fini_hook (evhtp_request_t *request)
static evhtp_res _evhtp_headers_start_hook (evhtp_request_t *request)
static evhtp_res _evhtp_connection_fini_hook (evhtp_connection_t *connection)
runs the user-definedhook called just prior to a connection being closed
static void _evhtp_error_hook (evhtp_request_t *request, evhtp_error_flags errtype)
runs the user-defined hook when a connection error occurs
static evhtp_res _evhtp_connection_error_hook (evhtp_connection_t *connection, evhtp_error_flags errtype)
runs the user-defined hook when a connection error occurs
static evhtp_res _evhtp_hostname_hook (evhtp_request_t *r, const char *hostname)
static evhtp_res _evhtp_connection_write_hook (evhtp_connection_t *connection)
static int _evhtp_glob_match2 (const char *pattern, size_t plen, const char *string, size_t str_len)
static int _evhtp_glob_match (const char *pattern, size_t pat_len, const char *string, size_t str_len)
glob/wildcard type pattern matching.
static evhtp_callback_t * _evhtp_callback_find (evhtp_callbacks_t *cbs, const char *path, unsigned int *start_offset, unsigned int *end_offset)
static evhtp_request_t * _evhtp_request_new (evhtp_connection_t *c)
Creates a new evhtp_request_t.
static evhtp_t * _evhtp_request_find_vhost (evhtp_t *evhtp, const char *name)
static int _evhtp_request_set_callbacks (evhtp_request_t *request)
static int _evhtp_require_uri (evhtp_connection_t *c)
static int _evhtp_should_parse_query_body (evhtp_request_t *req)
determines if the request body contains the query arguments. if the query is NULL and the contenet length of the body has never been drained, and the content-type is x-www-form-urlencoded, the function returns 1
static int _evhtp_create_headers (evhtp_header_t *header, void *arg)
static evbuf_t * _evhtp_create_reply (evhtp_request_t *request, evhtp_res code)
static void _evhtp_connection_resumecb (int fd, short events, void *arg)
static void _evhtp_connection_writecb (evbev_t *bev, void *arg)
static void _evhtp_connection_eventcb (evbev_t *bev, short events, void *arg)
static int _evhtp_run_pre_accept (evhtp_t *htp, evhtp_connection_t *conn)
static int _evhtp_connection_accept (evbase_t *evbase, evhtp_connection_t *connection)
static void _evhtp_default_request_cb (evhtp_request_t *request, void *arg)
static int _evhtp_run_post_accept (evhtp_t *htp, evhtp_connection_t *connection)
static void _evhtp_run_in_thread (evthr_t *thr, void *arg, void *shared)
static void _evhtp_accept_cb (evserv_t *serv, int fd, struct sockaddr *s, int sl, void *arg)
static unsigned long _evhtp_ssl_get_thread_id (void)
static void _evhtp_ssl_thread_lock (int mode, int type, const char *file, int line)
static void _evhtp_ssl_delete_scache_ent (evhtp_ssl_ctx_t *ctx, evhtp_ssl_sess_t *sess)
static int _evhtp_ssl_add_scache_ent (evhtp_ssl_t *ssl, evhtp_ssl_sess_t *sess)
static evhtp_ssl_sess_t * _evhtp_ssl_get_scache_ent (evhtp_ssl_t *ssl, unsigned char *sid, int sid_len, int *copy)
static int _evhtp_ssl_servername (evhtp_ssl_t *ssl, int *unused, void *arg)
htp_method evhtp_request_get_method (evhtp_request_t *r)
returns the htp_method enum version of the request method.
void evhtp_connection_pause (evhtp_connection_t *c)
pauses a connection (disables reading)
void evhtp_connection_resume (evhtp_connection_t *c)
resumes a connection (enables reading) and activates resume event.
void evhtp_request_pause (evhtp_request_t *request)
Wrapper around evhtp_connection_pause.
void evhtp_request_resume (evhtp_request_t *request)
Wrapper around evhtp_connection_resume.
evhtp_header_t * evhtp_header_key_add (evhtp_headers_t *headers, const char *key, char kalloc)
creates a new evhtp_header_t, sets only the key, and adds to the evhtp_headers TAILQ
evhtp_header_t * evhtp_header_val_add (evhtp_headers_t *headers, const char *val, char valloc)
finds the last header in the headers tailq and adds the value
evhtp_kvs_t * evhtp_kvs_new (void)
creates an empty list of key/values
evhtp_kv_t * evhtp_kv_new (const char *key, const char *val, char kalloc, char valloc)
Allocates a new key/value structure.
void evhtp_kv_free (evhtp_kv_t *kv)
frees resources allocated for a single key/value
void evhtp_kv_rm_and_free (evhtp_kvs_t *kvs, evhtp_kv_t *kv)
free's resources associated with 'kv' if ONLY found within the key/value list
void evhtp_kvs_free (evhtp_kvs_t *kvs)
frees a the list of key/values, and all underlying entries
int evhtp_kvs_for_each (evhtp_kvs_t *kvs, evhtp_kvs_iterator cb, void *arg)
callback iterator which executes 'cb' for every entry in 'kvs'
const char * evhtp_kv_find (evhtp_kvs_t *kvs, const char *key)
find the string value of 'key' from the key/value list 'kvs'
evhtp_kv_t * evhtp_kvs_find_kv (evhtp_kvs_t *kvs, const char *key)
find the evhtp_kv_t reference 'key' from the k/val list 'kvs'
void evhtp_kvs_add_kv (evhtp_kvs_t *kvs, evhtp_kv_t *kv)
appends a key/val structure to a evhtp_kvs_t tailq
void evhtp_kvs_add_kvs (evhtp_kvs_t *dst, evhtp_kvs_t *src)
appends all key/val structures from src tailq onto dst tailq
static int evhtp_is_hex_query_char (unsigned char ch)
int evhtp_unescape_string (unsigned char **out, unsigned char *str, size_t str_len)
Unescapes strings like '%7B1,%202,%203%7D' would become '{1, 2, 3}'.
evhtp_query_t * evhtp_parse_query_wflags (const char *query, size_t len, int flags)
Parses the query portion of the uri into a set of key/values.
evhtp_query_t * evhtp_parse_query (const char *query, size_t len)
Parses the query portion of the uri into a set of key/values in a strict manner.
void evhtp_send_reply_start (evhtp_request_t *request, evhtp_res code)
void evhtp_send_reply_body (evhtp_request_t *request, evbuf_t *buf)
void evhtp_send_reply_end (evhtp_request_t *request)
void evhtp_send_reply (evhtp_request_t *request, evhtp_res code)
generates all the right information for a reply to be sent to the client
int evhtp_response_needs_body (const evhtp_res code, const htp_method method)
Determine if a response should have a body. Follows the rules in RFC 2616 section 4.3.
void evhtp_send_reply_chunk_start (evhtp_request_t *request, evhtp_res code)
start a chunked response. If data already exists on the output buffer, this will be converted to the first chunk.
void evhtp_send_reply_chunk (evhtp_request_t *request, evbuf_t *buf)
send a chunk reply.
void evhtp_send_reply_chunk_end (evhtp_request_t *request)
call when all chunks have been sent and you wish to send the last bits. This will add the last 0CRLFCRCL and call send_reply_end().
void evhtp_unbind_socket (evhtp_t *htp)
stops the listening socket.
int evhtp_accept_socket (evhtp_t *htp, evutil_socket_t sock, int backlog)
create the listener plus setup various options with an already-bound socket.
int evhtp_bind_sockaddr (evhtp_t *htp, struct sockaddr *sa, size_t sin_len, int backlog)
bind to an already allocated sockaddr.
int evhtp_bind_socket (evhtp_t *htp, const char *baddr, uint16_t port, int backlog)
bind to a socket, optionally with specific protocol support formatting. The addr can be defined as one of the following: ipv6:<ipv6addr> for binding to an IPv6 address. unix:<named pipe>=""> for binding to a unix named socket ipv4:<ipv4addr> for binding to an ipv4 address Otherwise the addr is assumed to be ipv4.
void evhtp_callbacks_free (evhtp_callbacks_t *callbacks)
evhtp_callback_t * evhtp_callback_new (const char *path, evhtp_callback_type type, evhtp_callback_cb cb, void *arg)
creates a new evhtp_callback_t structure.
void evhtp_callback_free (evhtp_callback_t *callback)
frees information associated with a ainflwx callback.
int evhtp_callbacks_add_callback (evhtp_callbacks_t *cbs, evhtp_callback_t *cb)
Adds a evhtp_callback_t to the evhtp_callbacks_t list.
int evhtp_set_hook (evhtp_hooks_t **hooks, evhtp_hook_type type, evhtp_hook cb, void *arg)
sets a callback hook for either a connection or a path/regex .
int evhtp_unset_hook (evhtp_hooks_t **hooks, evhtp_hook_type type)
remove a specific hook from being called.
int evhtp_unset_all_hooks (evhtp_hooks_t **hooks)
removes all hooks.
evhtp_callback_t * evhtp_set_cb (evhtp_t *htp, const char *path, evhtp_callback_cb cb, void *arg)
sets a callback to be executed on a specific path
evhtp_callback_t * evhtp_get_cb (evhtp_t *htp, const char *path)
attempts to find the callback matching the exact string 'needle'. This is useful in cases where we want to get the original handle, but is not in scope.
static void _evhtp_thread_init (evthr_t *thr, void *arg)
static void _evhtp_thread_exit (evthr_t *thr, void *arg)
static int _evhtp_use_threads (evhtp_t *htp, evhtp_thread_init_cb init_cb, evhtp_thread_exit_cb exit_cb, int nthreads, void *arg)
int evhtp_use_threads (evhtp_t *htp, evhtp_thread_init_cb init_cb, int nthreads, void *arg)
Enable thread-pool support for an evhtp_t context. Connectios are distributed across 'nthreads'. An optional "on-start" callback can be set which allows you to manipulate the thread-specific inforation (such as the thread-specific event_base).
int evhtp_use_threads_wexit (evhtp_t *htp, evhtp_thread_init_cb init_cb, evhtp_thread_exit_cb exit_cb, int nthreads, void *arg)
Temporary function which will be renamed evhtp_use_threads in the future. evhtp_use_threads() has been noted as deprecated for now.
int evhtp_use_callback_locks (evhtp_t *htp)
creates a lock around callbacks and hooks, allowing for threaded applications to add/remove/modify hooks & callbacks in a thread-safe manner.
evhtp_callback_t * evhtp_set_regex_cb (evhtp_t *htp, const char *pattern, evhtp_callback_cb cb, void *arg)
sets a callback to be executed based on a regex pattern
evhtp_callback_t * evhtp_set_glob_cb (evhtp_t *htp, const char *pattern, evhtp_callback_cb cb, void *arg)
sets a callback to to be executed on simple glob/wildcard patterns this is useful if the app does not care about what was matched, but just that it matched. This is technically faster than regex.
void evhtp_set_gencb (evhtp_t *htp, evhtp_callback_cb cb, void *arg)
sets a callback which is called if no other callbacks are matched
void evhtp_set_pre_accept_cb (evhtp_t *htp, evhtp_pre_accept_cb cb, void *arg)
call a user-defined function before the connection is accepted.
void evhtp_set_post_accept_cb (evhtp_t *htp, evhtp_post_accept_cb cb, void *arg)
call a user-defined function right after a connection is accepted.
int evhtp_ssl_use_threads (void)
int evhtp_ssl_init (evhtp_t *htp, evhtp_ssl_cfg_t *cfg)
evbev_t * evhtp_connection_get_bev (evhtp_connection_t *connection)
returns the underlying connections bufferevent
evbev_t * evhtp_connection_take_ownership (evhtp_connection_t *connection)
let a user take ownership of the underlying bufferevent and free all other underlying resources.
evbev_t * evhtp_request_get_bev (evhtp_request_t *request)
returns the underlying requests bufferevent
evbev_t * evhtp_request_take_ownership (evhtp_request_t *request)
void evhtp_connection_set_bev (evhtp_connection_t *conn, evbev_t *bev)
Sets the connections underlying bufferevent.
void evhtp_request_set_bev (evhtp_request_t *request, evbev_t *bev)
sets the underlying bufferevent for a evhtp_request
void evhtp_request_set_keepalive (evhtp_request_t *request, int val)
evhtp_connection_t * evhtp_request_get_connection (evhtp_request_t *request)
returns the underlying evhtp_connection_t structure from a request
evhtp_proto evhtp_request_get_proto (evhtp_request_t *request)
void evhtp_connection_set_timeouts (evhtp_connection_t *c, const struct timeval *rtimeo, const struct timeval *wtimeo)
sets a connection-specific read/write timeout which overrides the global read/write settings.
void evhtp_connection_set_max_body_size (evhtp_connection_t *c, uint64_t len)
set a max body size for a specific connection, this will default to the size set by evhtp_set_max_body_size
void evhtp_request_set_max_body_size (evhtp_request_t *req, uint64_t len)
just calls evhtp_connection_set_max_body_size for the request.
void evhtp_connection_free (evhtp_connection_t *connection)
free's all connection related resources, this will also call your request fini hook and request fini hook.
void evhtp_request_free (evhtp_request_t *request)
void evhtp_set_timeouts (evhtp_t *htp, const struct timeval *r_timeo, const struct timeval *w_timeo)
set a read/write timeout on all things evhtp_t. When the timeout expires your error hook will be called with the libevent supplied event flags.
void evhtp_set_max_keepalive_requests (evhtp_t *htp, uint64_t num)
sets a maximum number of requests that a single connection can make.
void evhtp_set_bev_flags (evhtp_t *htp, int flags)
set bufferevent flags, defaults to BEV_OPT_CLOSE_ON_FREE
void evhtp_set_max_body_size (evhtp_t *htp, uint64_t len)
set a max body size to accept for an incoming request, this will default to unlimited.
void evhtp_disable_100_continue (evhtp_t *htp)
when a client sends an Expect: 100-continue, if this is function is called, evhtp will not send a HTTP/x.x continue response.
void evhtp_set_parser_flags (evhtp_t *htp, int flags)
during the request processing cycle, these flags will be used to for query argument parsing. i.e., what to parse and not to parse.
int evhtp_add_alias (evhtp_t *evhtp, const char *name)
Add an alias hostname for a virtual-host specific evhtp_t. This avoids having multiple evhtp_t virtual hosts with the same callback for the same vhost.
int evhtp_add_vhost (evhtp_t *evhtp, const char *name, evhtp_t *vhost)
add a virtual host.
evhtp_t * evhtp_new (evbase_t *evbase, void *arg)
creates a new evhtp_t instance
void evhtp_free (evhtp_t *evhtp)
evhtp_connection_t * evhtp_connection_new (evbase_t *evbase, const char *addr, uint16_t port)
allocate a new connection
evhtp_connection_t * evhtp_connection_new_dns (evbase_t *evbase, struct evdns_base *dns_base, const char *addr, uint16_t port)
allocate a new connection
evhtp_connection_t * evhtp_connection_ssl_new (evbase_t *evbase, const char *addr, uint16_t port, evhtp_ssl_ctx_t *ctx)
evhtp_request_t * evhtp_request_new (evhtp_callback_cb cb, void *arg)
allocate a new request
int evhtp_make_request (evhtp_connection_t *c, evhtp_request_t *r, htp_method meth, const char *uri)
make a client request
unsigned int evhtp_request_status (evhtp_request_t *r)
Variables
static htparse_hooks request_psets
callback definitions for request processing from libhtparse
static int session_id_context = 1
static int ssl_num_locks
static evhtp_mutex_t * ssl_locks
static int ssl_locks_initialized = 0
Macro Definition Documentation
#define HOOK_AVAIL (var, hook_name) (var->hooks && var->hooks->hook_name)
#define HOOK_FUNC (var, hook_name) (var->hooks->hook_name)
#define HOOK_ARGS (var, hook_name) var->hooks->hook_name ## _arg
#define HOOK_REQUEST_RUN (request, hook_name, ...)
Value:
do {                                       \
        if (HOOK_AVAIL(request, hook_name)) {                                                 \
            return HOOK_FUNC(request, hook_name) (request, __VA_ARGS__,                       \
                                                  HOOK_ARGS(request, hook_name));             \
        }                                                                                     \
                                                                                              \
        if (HOOK_AVAIL(evhtp_request_get_connection(request), hook_name)) {                   \
            return HOOK_FUNC(request->conn, hook_name) (request, __VA_ARGS__,                 \
                                                        HOOK_ARGS(request->conn, hook_name)); \
        }                                                                                     \
} while (0)
Referenced by _evhtp_body_hook(), _evhtp_chunk_new_hook(), _evhtp_header_hook(), _evhtp_headers_hook(), _evhtp_hostname_hook(), and _evhtp_path_hook().
#define HOOK_REQUEST_RUN_NARGS (request, hook_name)
Value:
do {                                       \
        if (HOOK_AVAIL(request, hook_name)) {                                                 \
            return HOOK_FUNC(request, hook_name) (request,                                    \
                                                  HOOK_ARGS(request, hook_name));             \
        }                                                                                     \
                                                                                              \
        if (HOOK_AVAIL(request->conn, hook_name)) {                                           \
            return HOOK_FUNC(request->conn, hook_name) (request,                              \
                                                        HOOK_ARGS(request->conn, hook_name)); \
        }                                                                                     \
} while (0);
Referenced by _evhtp_chunk_fini_hook(), _evhtp_chunks_fini_hook(), _evhtp_headers_start_hook(), and _evhtp_request_fini_hook().
#define HOOK_CONN_RUN (conn, hook_name, ...)
Value:
do {                         \
        if (conn->request) {                                                    \
            evhtp_request_t * request = conn->request;                          \
            if (HOOK_AVAIL(request, hook_name)) {                               \
                return HOOK_FUNC(conn, hook_name) (conn, __VA_ARGS__,           \
                                                   HOOK_ARGS(conn, hook_name)); \
            }                                                                   \
        }                                                                       \
                                                                                \
        if (HOOK_AVAIL(conn, hook_name)) {                                      \
            return HOOK_FUNC(conn, hook_name) (conn, __VA_ARGS__,               \
                                               HOOK_ARGS(conn, hook_name));     \
        }                                                                       \
} while (0);
Referenced by _evhtp_connection_error_hook().
#define _evhtp_lock (h)
Value:
do { \
        if (h->lock) {                                  \
            pthread_mutex_lock(h->lock);                \
        }                                               \
} while (0)
Referenced by _evhtp_request_parser_hostname(), _evhtp_request_parser_path(), evhtp_set_cb(), evhtp_set_glob_cb(), and evhtp_set_regex_cb().
#define _evhtp_unlock (h)
Value:
do { \
        if (h->lock) {                                  \
            pthread_mutex_unlock(h->lock);              \
        }                                               \
} while (0)
Referenced by _evhtp_request_parser_hostname(), _evhtp_request_parser_path(), evhtp_set_cb(), evhtp_set_glob_cb(), and evhtp_set_regex_cb().
#define _evhtp_is_http_11 (_major, _minor) (_major >= 1 && _minor >= 1)
helper macro to determine if http version is HTTP/1.0
Parameters
major the major version number
minor the minor version number
Returns
1 if HTTP/1.0, else 0
Referenced by _evhtp_protocol().
#define _evhtp_is_http_10 (_major, _minor) (_major >= 1 && _minor <= 0)
helper function to determine if http version is HTTP/1.1
Parameters
major the major version number
minor the minor version number
Returns
1 if HTTP/1.1, else 0
Referenced by _evhtp_protocol().
Enumeration Type Documentation
enum query_parser_state
Enumerator
s_query_start
s_query_separator
s_query_key
s_query_val
s_query_key_hex_1
s_query_key_hex_2
s_query_val_hex_1
s_query_val_hex_2
s_query_done
              {
     s_query_start = 0,
     s_query_separator,
     s_query_key,
     s_query_val,
     s_query_key_hex_1,
     s_query_key_hex_2,
     s_query_val_hex_1,
     s_query_val_hex_2,
     s_query_done
 } query_parser_state;
enum unscape_state
Enumerator
unscape_state_start
unscape_state_hex1
unscape_state_hex2
                    {
     unscape_state_start = 0,
     unscape_state_hex1,
     unscape_state_hex2
 };
Function Documentation
static int _evhtp_request_parser_start (htparser * p) static
References _evhtp_request_free(), _evhtp_request_new(), evhtp_type_client, evhtp_unlikely, and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     if (evhtp_unlikely(c->type == evhtp_type_client)) {
         return 0;
     }
     if (evhtp_unlikely(c->paused == 1)) {
         return -1;
     }
     if (c->request) {
         if (c->request->finished == 1) {
             _evhtp_request_free(c->request);
         } else {
             return -1;
         }
     }
     if (evhtp_unlikely(!(c->request = _evhtp_request_new(c)))) {
         return -1;
     }
     return 0;
 }
static int _evhtp_request_parser_host (htparser * p, const char * data, size_t len) static
References _evhtp_require_uri(), EVHTP_RES_FATAL, and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     evhtp_authority_t  * authority;
     if (_evhtp_require_uri(c) != 0) {
         return -1;
     }
     authority           = c->request->uri->authority;
     authority->hostname = malloc(len + 1);
     if (!authority->hostname) {
         c->request->status = EVHTP_RES_FATAL;
         return -1;
     }
     memcpy(authority->hostname, data, len);
     authority->hostname[len] = '\0';
     return 0;
 }
static int _evhtp_request_parser_port (htparser * p, const char * data, size_t len) static
References _evhtp_require_uri(), EVHTP_RES_FATAL, and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     evhtp_authority_t  * authority;
     char               * endptr;
     unsigned long        port;
     if (_evhtp_require_uri(c) != 0) {
         return -1;
     }
     authority = c->request->uri->authority;
     port      = strtoul(data, &endptr, 10);
     if (endptr - data != len || port > 65535) {
         c->request->status = EVHTP_RES_FATAL;
         return -1;
     }
     authority->port = port;
     return 0;
 }
static int _evhtp_request_parser_path (htparser * p, const char * data, size_t len) static
References _evhtp_lock, _evhtp_path_hook(), _evhtp_path_new(), _evhtp_request_set_callbacks(), _evhtp_require_uri(), _evhtp_unlock, EVHTP_RES_FATAL, EVHTP_RES_OK, evhtp_unlikely, htparser_get_method(), htparser_get_scheme(), and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     evhtp_path_t       * path;
     if (_evhtp_require_uri(c) != 0) {
         return -1;
     }
     if (evhtp_unlikely(!(path = _evhtp_path_new(data, len)))) {
         c->request->status = EVHTP_RES_FATAL;
         return -1;
     }
     c->request->uri->path   = path;
     c->request->uri->scheme = htparser_get_scheme(p);
     c->request->method      = htparser_get_method(p);
     _evhtp_lock(c->htp);
     {
         _evhtp_request_set_callbacks(c->request);
     }
     _evhtp_unlock(c->htp);
     if ((c->request->status = _evhtp_path_hook(c->request, path)) != EVHTP_RES_OK) {
         return -1;
     }
     return 0;
 }     /* _evhtp_request_parser_path */
static int _evhtp_request_parser_args (htparser * p, const char * data, size_t len) static
References evhtp_alloc_assert, EVHTP_PARSE_QUERY_FLAG_IGNORE_FRAGMENTS, evhtp_parse_query_wflags(), EVHTP_RES_ERROR, evhtp_type_client, evhtp_unlikely, and htparser_get_userdata().
{
     evhtp_connection_t * c   = htparser_get_userdata(p);
     evhtp_uri_t        * uri = c->request->uri;
     const char         * fragment;
     int                  ignore_fragment;
     if (c->type == evhtp_type_client) {
         /* as a client, technically we should never get here, but just in case
          * we return a 0 to the parser to continue.
          */
         return 0;
     }
     /* if the parser flags has the IGNORE_FRAGMENTS bit set, skip
      * the fragment parsing
      */
     ignore_fragment = (c->htp->parser_flags &
                        EVHTP_PARSE_QUERY_FLAG_IGNORE_FRAGMENTS);
     if (!ignore_fragment && (fragment = memchr(data, '#', len))) {
         /* Separate fragment from query according to RFC 3986.
          *
          * XXX: not happy about using strchr stuff, maybe this functionality
          * is more apt as part of evhtp_parse_query()
          */
         ptrdiff_t frag_offset;
         frag_offset = fragment - data;
         if (frag_offset < len) {
             size_t fraglen;
             /* Skip '#'. */
             fragment              += 1;
             frag_offset           += 1;
             fraglen                = len - frag_offset;
             uri->fragment          = malloc(fraglen + 1);
             evhtp_alloc_assert(uri->fragment);
             memcpy(uri->fragment, fragment, fraglen);
             uri->fragment[fraglen] = '\0';
             len -= fraglen + 1; /* Skip '#' + fragment string. */
         }
     }
     uri->query = evhtp_parse_query_wflags(data, len, c->htp->parser_flags);
     if (evhtp_unlikely(!uri->query)) {
         c->request->status = EVHTP_RES_ERROR;
         return -1;
     }
     uri->query_raw      = malloc(len + 1);
     evhtp_alloc_assert(uri->query_raw);
     memcpy(uri->query_raw, data, len);
     uri->query_raw[len] = '\0';
     return 0;
 } /* _evhtp_request_parser_args */
static int _evhtp_request_parser_header_key (htparser * p, const char * data, size_t len) static
References evhtp_alloc_assert, evhtp_header_key_add(), evhtp_header_t, EVHTP_RES_FATAL, and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     char               * key_s;
     evhtp_header_t     * hdr;
     key_s      = malloc(len + 1);
     evhtp_alloc_assert(key_s);
     key_s[len] = '\0';
     memcpy(key_s, data, len);
     if ((hdr = evhtp_header_key_add(c->request->headers_in, key_s, 0)) == NULL) {
         c->request->status = EVHTP_RES_FATAL;
         return -1;
     }
     hdr->k_heaped = 1;
     return 0;
 }
static int _evhtp_request_parser_header_val (htparser * p, const char * data, size_t len) static
References _evhtp_header_hook(), evhtp_alloc_assert, evhtp_header_t, evhtp_header_val_add(), EVHTP_RES_FATAL, EVHTP_RES_OK, evhtp_safe_free, and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     char               * val_s;
     evhtp_header_t     * header;
     val_s      = malloc(len + 1);
     evhtp_alloc_assert(val_s);
     val_s[len] = '\0';
     memcpy(val_s, data, len);
     if ((header = evhtp_header_val_add(c->request->headers_in, val_s, 0)) == NULL) {
         evhtp_safe_free(val_s, free);
         c->request->status = EVHTP_RES_FATAL;
         return -1;
     }
     header->v_heaped = 1;
     if ((c->request->status = _evhtp_header_hook(c->request, header)) != EVHTP_RES_OK) {
         return -1;
     }
     return 0;
 }
static int _evhtp_request_parser_hostname (htparser * p, const char * data, size_t len) static
References _evhtp_hostname_hook(), _evhtp_lock, _evhtp_request_find_vhost(), _evhtp_request_set_callbacks(), _evhtp_unlock, EVHTP_RES_OK, and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     evhtp_t            * evhtp;
     evhtp_t            * evhtp_vhost;
 #ifndef EVHTP_DISABLE_SSL
     if (c->vhost_via_sni == 1 && c->ssl != NULL) {
         /* use the SNI set hostname instead of the header hostname */
         const char * host;
         host = SSL_get_servername(c->ssl, TLSEXT_NAMETYPE_host_name);
         if ((c->request->status = _evhtp_hostname_hook(c->request, host)) != EVHTP_RES_OK) {
             return -1;
         }
         return 0;
     }
 #endif
     evhtp = c->htp;
     /* since this is called after _evhtp_request_parser_path(), which already
      * setup callbacks for the URI, we must now attempt to find callbacks which
      * are specific to this host.
      */
     _evhtp_lock(evhtp);
     {
         if ((evhtp_vhost = _evhtp_request_find_vhost(evhtp, data))) {
             _evhtp_lock(evhtp_vhost);
             {
                 /* if we found a match for the host, we must set the htp
                  * variables for both the connection and the request.
                  */
                 c->htp          = evhtp_vhost;
                 c->request->htp = evhtp_vhost;
                 _evhtp_request_set_callbacks(c->request);
             }
             _evhtp_unlock(evhtp_vhost);
         }
     }
     _evhtp_unlock(evhtp);
     if ((c->request->status = _evhtp_hostname_hook(c->request, data)) != EVHTP_RES_OK) {
         return -1;
     }
     return 0;
 } /* _evhtp_request_parser_hostname */
static int _evhtp_request_parser_headers (htparser * p) static
References _evhtp_headers_hook(), _evhtp_protocol(), evhtp_assert, evhtp_header_find(), evhtp_modp_uchartoa, EVHTP_RES_OK, evhtp_type_server, htparser_get_major(), htparser_get_minor(), htparser_get_userdata(), and htparser_should_keep_alive().
{
     evhtp_connection_t * c;
     c = htparser_get_userdata(p);
     evhtp_assert(c != NULL);
     /* XXX proto should be set with htparsers on_hdrs_begin hook */
     c->request->keepalive = htparser_should_keep_alive(p);
     c->request->proto     = _evhtp_protocol(htparser_get_major(p), htparser_get_minor(p));
     c->request->status    = _evhtp_headers_hook(c->request, c->request->headers_in);
     if (c->request->status != EVHTP_RES_OK) {
         return -1;
     }
     if (c->type == evhtp_type_server && c->htp->disable_100_cont == 0) {
         /* only send a 100 continue response if it hasn't been disabled via
          * evhtp_disable_100_continue.
          */
         if (!evhtp_header_find(c->request->headers_in, "Expect")) {
             return 0;
         }
         evbuffer_add_printf(bufferevent_get_output(c->bev),
                             "HTTP/%c.%c 100 Continue\r\n\r\n",
                             evhtp_modp_uchartoa(htparser_get_major(p)),
                             evhtp_modp_uchartoa(htparser_get_minor(p)));
     }
     return 0;
 }
static int _evhtp_request_parser_body (htparser * p, const char * data, size_t len) static
References _evhtp_body_hook(), evhtp_assert, EVHTP_RES_DATA_TOO_LONG, EVHTP_RES_OK, and htparser_get_userdata().
{
     evhtp_connection_t * c   = htparser_get_userdata(p);
     evbuf_t            * buf;
     int                  res = 0;
     if (c->max_body_size > 0 && c->body_bytes_read + len >= c->max_body_size) {
         c->error           = 1;
         c->request->status = EVHTP_RES_DATA_TOO_LONG;
         return -1;
     }
     buf = c->scratch_buf;
     evhtp_assert(buf != NULL);
     evbuffer_add(buf, data, len);
     if ((c->request->status = _evhtp_body_hook(c->request, buf)) != EVHTP_RES_OK) {
         res = -1;
     }
     if (evbuffer_get_length(buf)) {
         evbuffer_add_buffer(c->request->buffer_in, buf);
     }
     evbuffer_drain(buf, -1);
     c->body_bytes_read += len;
     return res;
 }
static int _evhtp_request_parser_fini (htparser * p) static
References _evhtp_should_parse_query_body(), evhtp_alloc_assert, evhtp_parse_query(), and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     if (c->paused == 1) {
         return -1;
     }
     /* check to see if we should use the body of the request as the query
      * arguments.
      */
     if (_evhtp_should_parse_query_body(c->request) == 1) {
         const char  * body;
         size_t        body_len;
         evhtp_uri_t * uri;
         evbuf_t     * buf_in;
         uri            = c->request->uri;
         buf_in         = c->request->buffer_in;
         body_len       = evbuffer_get_length(buf_in);
         body           = (const char *)evbuffer_pullup(buf_in, body_len);
         uri->query_raw = calloc(body_len + 1, 1);
         evhtp_alloc_assert(uri->query_raw);
         memcpy(uri->query_raw, body, body_len);
         uri->query     = evhtp_parse_query(body, body_len);
     }
     /*
      * XXX c->request should never be NULL, but we have found some path of
      * execution where this actually happens. We will check for now, but the bug
      * path needs to be tracked down.
      *
      */
     if (c->request && c->request->cb) {
         (c->request->cb)(c->request, c->request->cbarg);
     }
     if (c->paused == 1) {
         return -1;
     }
     return 0;
 } /* _evhtp_request_parser_fini */
static int _evhtp_request_parser_chunk_new (htparser * p) static
References _evhtp_chunk_new_hook(), EVHTP_RES_OK, htparser_get_content_length(), and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     if ((c->request->status = _evhtp_chunk_new_hook(c->request,
                                                     htparser_get_content_length(p))) != EVHTP_RES_OK) {
         return -1;
     }
     return 0;
 }
static int _evhtp_request_parser_chunk_fini (htparser * p) static
References _evhtp_chunk_fini_hook(), EVHTP_RES_OK, and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     if ((c->request->status = _evhtp_chunk_fini_hook(c->request)) != EVHTP_RES_OK) {
         return -1;
     }
     return 0;
 }
static int _evhtp_request_parser_chunks_fini (htparser * p) static
References _evhtp_chunks_fini_hook(), EVHTP_RES_OK, and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     if ((c->request->status = _evhtp_chunks_fini_hook(c->request)) != EVHTP_RES_OK) {
         return -1;
     }
     return 0;
 }
static int _evhtp_request_parser_headers_start (htparser * p) static
References _evhtp_headers_start_hook(), EVHTP_RES_OK, and htparser_get_userdata().
{
     evhtp_connection_t * c = htparser_get_userdata(p);
     if ((c->request->status = _evhtp_headers_start_hook(c->request)) != EVHTP_RES_OK) {
         return -1;
     }
     return 0;
 }
static void _evhtp_connection_readcb (evbev_t * bev, void * arg) static
References _evhtp_connection_error_hook(), evhtp_connection_free(), evhtp_connection_resume(), evhtp_request_pause(), EVHTP_RES_DATA_TOO_LONG, EVHTP_RES_OK, EVHTP_RES_PAUSE, evhtp_unlikely, htp_log_debug, htparse_error_none, htparser_get_error(), and htparser_run().
Referenced by _evhtp_connection_accept(), _evhtp_connection_eventcb(), _evhtp_connection_resumecb(), and _evhtp_connection_writecb().
{
     evhtp_connection_t * c = arg;
     void               * buf;
     size_t               nread;
     size_t               avail;
     htp_log_debug("enter sock = %d", c->sock);
     avail = evbuffer_get_length(bufferevent_get_input(bev));
     htp_log_debug("available bytes %zu", avail);
     if (evhtp_unlikely(avail == 0)) {
         return;
     }
     if (c->request) {
         c->request->status = EVHTP_RES_OK;
     }
     if (c->paused == 1) {
         return;
     }
     buf   = evbuffer_pullup(bufferevent_get_input(bev), avail);
     htp_log_debug("buffer is\n----\n%.*s\n-----", (int)avail, (const char *)buf);
     nread = htparser_run(c->parser, &request_psets, (const char *)buf, avail);
     htp_log_debug("nread = %zu", nread);
     if (evhtp_unlikely(c->owner != 1)) {
         /*
          * someone has taken the ownership of this connection, we still need to
          * drain the input buffer that had been read up to this point.
          */
         evbuffer_drain(bufferevent_get_input(bev), nread);
         evhtp_connection_free(c);
         return;
     }
     if (c->request) {
         switch (c->request->status) {
             case EVHTP_RES_DATA_TOO_LONG:
                 _evhtp_connection_error_hook(c, -1);
                 evhtp_connection_free(c);
                 return;
             default:
                 break;
         }
     }
     evbuffer_drain(bufferevent_get_input(bev), nread);
     if (c->request && c->request->status == EVHTP_RES_PAUSE) {
         evhtp_request_pause(c->request);
     } else if (htparser_get_error(c->parser) != htparse_error_none) {
         evhtp_connection_free(c);
     } else if (nread < avail) {
         /* we still have more data to read (piped request probably) */
         evhtp_connection_resume(c);
     }
 } /* _evhtp_connection_readcb */
static evhtp_connection_t * _evhtp_connection_new (evhtp_t * htp, evutil_socket_t sock, evhtp_type type) static
References evhtp_alloc_assert, evhtp_type_client, evhtp_type_server, htp_type_request, htp_type_response, htparser_init(), htparser_new(), and htparser_set_userdata().
Referenced by _evhtp_accept_cb(), evhtp_connection_new_dns(), and evhtp_connection_ssl_new().
{
     evhtp_connection_t * connection;
     htp_type             ptype;
     switch (type) {
         case evhtp_type_client:
             ptype = htp_type_response;
             break;
         case evhtp_type_server:
             ptype = htp_type_request;
             break;
         default:
             return NULL;
     }
     connection = calloc(sizeof(evhtp_connection_t), 1);
     evhtp_alloc_assert(connection);
     connection->scratch_buf = evbuffer_new();
     evhtp_alloc_assert(connection->scratch_buf);
     connection->error       = 0;
     connection->owner       = 1;
     connection->paused      = 0;
     connection->connected   = 0;
     connection->sock        = sock;
     connection->htp         = htp;
     connection->type        = type;
     connection->parser      = htparser_new();
     evhtp_alloc_assert(connection->parser);
     htparser_init(connection->parser, ptype);
     htparser_set_userdata(connection->parser, connection);
 #ifdef EVHTP_FUTURE_USE
     TAILQ_INIT(&connection->pending);
 #endif
     return connection;
 } /* _evhtp_connection_new */
static evhtp_uri_t * _evhtp_uri_new (void) static
create an overlay URI structure
Returns
evhtp_uri_t
References _evhtp_authority_new(), and _evhtp_uri_free().
Referenced by _evhtp_require_uri().
                      {
     evhtp_uri_t * uri;
     if (!(uri = calloc(sizeof(evhtp_uri_t), 1))) {
         return NULL;
     }
     uri->authority = _evhtp_authority_new();
     if (!uri->authority) {
         _evhtp_uri_free(uri);
         return NULL;
     }
     return uri;
 }
static void _evhtp_uri_free (evhtp_uri_t * uri) static
frees an overlay URI structure
Parameters
uri evhtp_uri_t
References _evhtp_authority_free(), _evhtp_path_free(), evhtp_query_free, evhtp_safe_free, and evhtp_unlikely.
Referenced by _evhtp_request_free(), and _evhtp_uri_new().
{
     if (evhtp_unlikely(uri == NULL)) {
         return;
     }
     evhtp_safe_free(uri->query, evhtp_query_free);
     evhtp_safe_free(uri->path, _evhtp_path_free);
     evhtp_safe_free(uri->authority, _evhtp_authority_free);
     evhtp_safe_free(uri->fragment, free);
     evhtp_safe_free(uri->query_raw, free);
     evhtp_safe_free(uri, free);
 }
static evhtp_authority_t * _evhtp_authority_new (void) static
create an authority structure
Returns
evhtp_authority_t
Referenced by _evhtp_uri_new().
{
     evhtp_authority_t * authority;
     if (!(authority = calloc(1, sizeof(*authority)))) {
         return NULL;
     }
     return authority;
 }
static void _evhtp_authority_free (evhtp_authority_t * authority) static
frees an authority structure
Parameters
authority evhtp_authority_t
References evhtp_safe_free.
Referenced by _evhtp_uri_free().
{
     if (authority == NULL) {
         return;
     }
     evhtp_safe_free(authority->username, free);
     evhtp_safe_free(authority->password, free);
     evhtp_safe_free(authority->hostname, free);
     evhtp_safe_free(authority, free);
 }
static evhtp_path_t * _evhtp_path_new (const char * data, size_t len) static
parses the path and file from an input buffer
in order to properly create a structure that can match both a path and a file, this will parse a string into what it considers a path, and a file.
if for example the input was "/a/b/c", the parser will consider "/a/b/" as the path, and "c" as the file.
Parameters
data raw input data (assumes a /path/[file] structure)
len length of the input data
Returns
evhtp_request_t * on success, NULL on error.
References evhtp_alloc_assert, evhtp_safe_free, and evhtp_unlikely.
Referenced by _evhtp_request_parser_path().
{
     evhtp_path_t * req_path;
     const char   * data_end = (const char *)(data + len);
     char         * path     = NULL;
     char         * file     = NULL;
     req_path = calloc(sizeof(evhtp_path_t), 1);
     evhtp_alloc_assert(req_path);
     if (evhtp_unlikely(len == 0)) {
         /*
          * odd situation here, no preceding "/", so just assume the path is "/"
          */
         path = strdup("/");
         evhtp_alloc_assert(path);
     } else if (*data != '/') {
         /* request like GET stupid HTTP/1.0, treat stupid as the file, and
          * assume the path is "/"
          */
         path = strdup("/");
         file = strndup(data, len);
         evhtp_alloc_assert(path);
         evhtp_alloc_assert(file);
     } else {
         if (data[len - 1] != '/') {
             /*
              * the last character in data is assumed to be a file, not the end of path
              * loop through the input data backwards until we find a "/"
              */
             size_t i;
             for (i = (len - 1); i != 0; i--) {
                 if (data[i] == '/') {
                     /*
                      * we have found a "/" representing the start of the file,
                      * and the end of the path
                      */
                     size_t path_len;
                     size_t file_len;
                     path_len = (size_t)(&data[i] - data) + 1;
                     file_len = (size_t)(data_end - &data[i + 1]);
                     /* check for overflow */
                     if ((const char *)(data + path_len) > data_end) {
                         evhtp_safe_free(req_path, free);
                         return NULL;
                     }
                     /* check for overflow */
                     if ((const char *)(&data[i + 1] + file_len) > data_end) {
                         evhtp_safe_free(req_path, free);
                         return NULL;
                     }
                     path = strndup(data, path_len);
                     file = strndup(&data[i + 1], file_len);
                     evhtp_alloc_assert(path);
                     evhtp_alloc_assert(file);
                     break;
                 }
             }
             if (i == 0 && data[i] == '/' && !file && !path) {
                 /* drops here if the request is something like GET /foo */
                 path = strdup("/");
                 evhtp_alloc_assert(path);
                 if (len > 1) {
                     file = strndup((const char *)(data + 1), len);
                     evhtp_alloc_assert(file);
                 }
             }
         } else {
             /* the last character is a "/", thus the request is just a path */
             path = strndup(data, len);
             evhtp_alloc_assert(path);
         }
     }
     if (len != 0) {
         req_path->full = strndup(data, len);
     } else {
         req_path->full = strdup("/");
     }
     evhtp_alloc_assert(req_path->full);
     req_path->path = path;
     req_path->file = file;
     return req_path;
 }     /* _evhtp_path_new */
static void _evhtp_path_free (evhtp_path_t * path) static
References evhtp_safe_free, and evhtp_unlikely.
Referenced by _evhtp_uri_free().
{
     if (evhtp_unlikely(path == NULL)) {
         return;
     }
     evhtp_safe_free(path->full, free);
     evhtp_safe_free(path->path, free);
     evhtp_safe_free(path->file, free);
     evhtp_safe_free(path->match_start, free);
     evhtp_safe_free(path->match_end, free);
     evhtp_safe_free(path, free);
 }
static void _evhtp_request_free (evhtp_request_t * request) static
frees all data in an evhtp_request_t along with calling finished hooks
Parameters
request the request structure
References _evhtp_request_fini_hook(), _evhtp_uri_free(), evhtp_headers_free, and evhtp_unlikely.
Referenced by _evhtp_connection_writecb(), _evhtp_request_new(), _evhtp_request_parser_start(), evhtp_connection_free(), and evhtp_request_free().
{
     if (evhtp_unlikely(request == NULL)) {
         return;
     }
     _evhtp_request_fini_hook(request);
     _evhtp_uri_free(request->uri);
     evhtp_headers_free(request->headers_in);
     evhtp_headers_free(request->headers_out);
     if (request->conn && request->conn->request == request) {
         request->conn->request = NULL;
     }
     if (request->buffer_in) {
         evbuffer_free(request->buffer_in);
     }
     if (request->buffer_out) {
         evbuffer_free(request->buffer_out);
     }
     free(request->hooks);
     free(request);
 }
static const char* status_code_to_str (evhtp_res code) static
References EVHTP_RES_200, EVHTP_RES_300, EVHTP_RES_400, EVHTP_RES_ACCEPTED, EVHTP_RES_BADGATEWAY, EVHTP_RES_BWEXEED, EVHTP_RES_CONFLICT, EVHTP_RES_CONTINUE, EVHTP_RES_CREATED, EVHTP_RES_ENTOOLARGE, EVHTP_RES_EXPECTFAIL, EVHTP_RES_FORBIDDEN, EVHTP_RES_FOUND, EVHTP_RES_GONE, EVHTP_RES_GWTIMEOUT, EVHTP_RES_IAMATEAPOT, EVHTP_RES_IMUSED, EVHTP_RES_LENREQ, EVHTP_RES_METHNALLOWED, EVHTP_RES_MOVEDPERM, EVHTP_RES_MSTATUS, EVHTP_RES_NACCEPTABLE, EVHTP_RES_NAUTHINFO, EVHTP_RES_NOCONTENT, EVHTP_RES_NOTFOUND, EVHTP_RES_NOTIMPL, EVHTP_RES_NOTMOD, EVHTP_RES_PARTIAL, EVHTP_RES_PAYREQ, EVHTP_RES_PRECONDFAIL, EVHTP_RES_PROCESSING, EVHTP_RES_PROXYAUTHREQ, EVHTP_RES_RANGENOTSC, EVHTP_RES_RSTCONTENT, EVHTP_RES_SEEOTHER, EVHTP_RES_SERVERR, EVHTP_RES_SERVUNAVAIL, EVHTP_RES_SWITCH_PROTO, EVHTP_RES_SWITCHPROXY, EVHTP_RES_TIMEOUT, EVHTP_RES_TMPREDIR, EVHTP_RES_UNAUTH, EVHTP_RES_UNSUPPORTED, EVHTP_RES_URI_TOOLONG, EVHTP_RES_URITOOLARGE, EVHTP_RES_USEPROXY, and EVHTP_RES_VERNSUPPORT.
Referenced by _evhtp_create_reply().
{
     switch (code) {
         case EVHTP_RES_200:
             return "OK";
         case EVHTP_RES_300:
             return "Redirect";
         case EVHTP_RES_400:
             return "Bad Request";
         case EVHTP_RES_NOTFOUND:
             return "Not Found";
         case EVHTP_RES_SERVERR:
             return "Internal Server Error";
         case EVHTP_RES_CONTINUE:
             return "Continue";
         case EVHTP_RES_FORBIDDEN:
             return "Forbidden";
         case EVHTP_RES_SWITCH_PROTO:
             return "Switching Protocols";
         case EVHTP_RES_MOVEDPERM:
             return "Moved Permanently";
         case EVHTP_RES_PROCESSING:
             return "Processing";
         case EVHTP_RES_URI_TOOLONG:
             return "URI Too Long";
         case EVHTP_RES_CREATED:
             return "Created";
         case EVHTP_RES_ACCEPTED:
             return "Accepted";
         case EVHTP_RES_NAUTHINFO:
             return "No Auth Info";
         case EVHTP_RES_NOCONTENT:
             return "No Content";
         case EVHTP_RES_RSTCONTENT:
             return "Reset Content";
         case EVHTP_RES_PARTIAL:
             return "Partial Content";
         case EVHTP_RES_MSTATUS:
             return "Multi-Status";
         case EVHTP_RES_IMUSED:
             return "IM Used";
         case EVHTP_RES_FOUND:
             return "Found";
         case EVHTP_RES_SEEOTHER:
             return "See Other";
         case EVHTP_RES_NOTMOD:
             return "Not Modified";
         case EVHTP_RES_USEPROXY:
             return "Use Proxy";
         case EVHTP_RES_SWITCHPROXY:
             return "Switch Proxy";
         case EVHTP_RES_TMPREDIR:
             return "Temporary Redirect";
         case EVHTP_RES_UNAUTH:
             return "Unauthorized";
         case EVHTP_RES_PAYREQ:
             return "Payment Required";
         case EVHTP_RES_METHNALLOWED:
             return "Not Allowed";
         case EVHTP_RES_NACCEPTABLE:
             return "Not Acceptable";
         case EVHTP_RES_PROXYAUTHREQ:
             return "Proxy Authentication Required";
         case EVHTP_RES_TIMEOUT:
             return "Request Timeout";
         case EVHTP_RES_CONFLICT:
             return "Conflict";
         case EVHTP_RES_GONE:
             return "Gone";
         case EVHTP_RES_LENREQ:
             return "Length Required";
         case EVHTP_RES_PRECONDFAIL:
             return "Precondition Failed";
         case EVHTP_RES_ENTOOLARGE:
             return "Entity Too Large";
         case EVHTP_RES_URITOOLARGE:
             return "Request-URI Too Long";
         case EVHTP_RES_UNSUPPORTED:
             return "Unsupported Media Type";
         case EVHTP_RES_RANGENOTSC:
             return "Requested Range Not Satisfiable";
         case EVHTP_RES_EXPECTFAIL:
             return "Expectation Failed";
         case EVHTP_RES_IAMATEAPOT:
             return "I'm a teapot";
         case EVHTP_RES_NOTIMPL:
             return "Not Implemented";
         case EVHTP_RES_BADGATEWAY:
             return "Bad Gateway";
         case EVHTP_RES_SERVUNAVAIL:
             return "Service Unavailable";
         case EVHTP_RES_GWTIMEOUT:
             return "Gateway Timeout";
         case EVHTP_RES_VERNSUPPORT:
             return "HTTP Version Not Supported";
         case EVHTP_RES_BWEXEED:
             return "Bandwidth Limit Exceeded";
     } /* switch */
     return "UNKNOWN";
 }     /* status_code_to_str */
static unsigned int _evhtp_quick_hash (const char * str) inline static
a weak hash function
Parameters
str a null terminated string
Returns
an unsigned integer hash of str
Referenced by evhtp_callback_new().
{
     unsigned int h = 0;
     for (; *str; str++) {
         h = 31 * h + *str;
     }
     return h;
 }
static evhtp_proto _evhtp_protocol (const char major, const char minor) inline static
returns the HTTP protocol version
Parameters
major the major version number
minor the minor version number
Returns
EVHTP_PROTO_10 if HTTP/1.0, EVHTP_PROTO_11 if HTTP/1.1, otherwise EVHTP_PROTO_INVALID
References _evhtp_is_http_10, _evhtp_is_http_11, EVHTP_PROTO_10, EVHTP_PROTO_11, and EVHTP_PROTO_INVALID.
Referenced by _evhtp_request_parser_headers().
{
     if (_evhtp_is_http_10(major, minor)) {
         return EVHTP_PROTO_10;
     }
     if (_evhtp_is_http_11(major, minor)) {
         return EVHTP_PROTO_11;
     }
     return EVHTP_PROTO_INVALID;
 }
static evhtp_res _evhtp_path_hook (evhtp_request_t * request, evhtp_path_t * path) inline static
runs the user-defined on_path hook for a request
Parameters
request the request structure
path the path structure
Returns
EVHTP_RES_OK on success, otherwise something else.
References EVHTP_RES_OK, and HOOK_REQUEST_RUN.
Referenced by _evhtp_request_parser_path().
{
     HOOK_REQUEST_RUN(request, on_path, path);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_header_hook (evhtp_request_t * request, evhtp_header_t * header) inline static
runs the user-defined on_header hook for a request
once a full key: value header has been parsed, this will call the hook
Parameters
request the request strucutre
header the header structure
Returns
EVHTP_RES_OK on success, otherwise something else.
References EVHTP_RES_OK, and HOOK_REQUEST_RUN.
Referenced by _evhtp_request_parser_header_val().
{
     HOOK_REQUEST_RUN(request, on_header, header);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_headers_hook (evhtp_request_t * request, evhtp_headers_t * headers) inline static
runs the user-defined on_Headers hook for a request after all headers have been parsed.
Parameters
request the request structure
headers the headers tailq structure
Returns
EVHTP_RES_OK on success, otherwise something else.
References EVHTP_RES_OK, and HOOK_REQUEST_RUN.
Referenced by _evhtp_request_parser_headers().
{
     HOOK_REQUEST_RUN(request, on_headers, headers);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_body_hook (evhtp_request_t * request, evbuf_t * buf) inline static
runs the user-defined on_body hook for requests containing a body. the data is stored in the request->buffer_in so the user may either leave it, or drain upon being called.
Parameters
request the request strucutre
buf a evbuffer containing body data
Returns
EVHTP_RES_OK on success, otherwise something else.
References EVHTP_RES_OK, and HOOK_REQUEST_RUN.
Referenced by _evhtp_request_parser_body().
{
     HOOK_REQUEST_RUN(request, on_read, buf);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_request_fini_hook (evhtp_request_t * request) inline static
runs the user-defined hook called just prior to a request been free()'d
Parameters
request therequest structure
Returns
EVHTP_RES_OK on success, otherwise treated as an error
References EVHTP_RES_OK, and HOOK_REQUEST_RUN_NARGS.
Referenced by _evhtp_request_free().
{
     HOOK_REQUEST_RUN_NARGS(request, on_request_fini);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_chunk_new_hook (evhtp_request_t * request, uint64_t len) inline static
References EVHTP_RES_OK, and HOOK_REQUEST_RUN.
Referenced by _evhtp_request_parser_chunk_new().
{
     HOOK_REQUEST_RUN(request, on_new_chunk, len);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_chunk_fini_hook (evhtp_request_t * request) inline static
References EVHTP_RES_OK, and HOOK_REQUEST_RUN_NARGS.
Referenced by _evhtp_request_parser_chunk_fini().
{
     HOOK_REQUEST_RUN_NARGS(request, on_chunk_fini);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_chunks_fini_hook (evhtp_request_t * request) inline static
References EVHTP_RES_OK, and HOOK_REQUEST_RUN_NARGS.
Referenced by _evhtp_request_parser_chunks_fini().
{
     HOOK_REQUEST_RUN_NARGS(request, on_chunks_fini);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_headers_start_hook (evhtp_request_t * request) inline static
References EVHTP_RES_OK, and HOOK_REQUEST_RUN_NARGS.
Referenced by _evhtp_request_parser_headers_start().
{
     HOOK_REQUEST_RUN_NARGS(request, on_headers_start);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_connection_fini_hook (evhtp_connection_t * connection) inline static
runs the user-definedhook called just prior to a connection being closed
Parameters
connection the connection structure
Returns
EVHTP_RES_OK on success, but pretty much ignored in any case.
References EVHTP_RES_OK.
Referenced by evhtp_connection_free().
{
     if (connection->hooks && connection->hooks->on_connection_fini) {
         return (connection->hooks->on_connection_fini)(connection,
                                                        connection->hooks->on_connection_fini_arg);
     }
     return EVHTP_RES_OK;
 }
static void _evhtp_error_hook (evhtp_request_t * request, evhtp_error_flags errtype) inline static
runs the user-defined hook when a connection error occurs
Parameters
request the request structure
errtype the error that ocurred
Referenced by _evhtp_connection_error_hook().
{
     if (request && request->hooks && request->hooks->on_error) {
         (*request->hooks->on_error)(request, errtype,
                                     request->hooks->on_error_arg);
     }
 }
static evhtp_res _evhtp_connection_error_hook (evhtp_connection_t * connection, evhtp_error_flags errtype) inline static
runs the user-defined hook when a connection error occurs
Parameters
connection the connection structure
errtype the error that ocurred
References _evhtp_error_hook(), EVHTP_RES_OK, and HOOK_CONN_RUN.
Referenced by _evhtp_connection_eventcb(), and _evhtp_connection_readcb().
{
     if (connection->request) {
         _evhtp_error_hook(connection->request, errtype);
     }
     HOOK_CONN_RUN(connection, on_connection_error, errtype);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_hostname_hook (evhtp_request_t * r, const char * hostname) inline static
References EVHTP_RES_OK, and HOOK_REQUEST_RUN.
Referenced by _evhtp_request_parser_hostname().
{
     HOOK_REQUEST_RUN(r, on_hostname, hostname);
     return EVHTP_RES_OK;
 }
static evhtp_res _evhtp_connection_write_hook (evhtp_connection_t * connection) inline static
References EVHTP_RES_OK.
Referenced by _evhtp_connection_writecb().
{
     if (connection->hooks && connection->hooks->on_write) {
         return (connection->hooks->on_write)(connection,
                                              connection->hooks->on_write_arg);
     }
     return EVHTP_RES_OK;
 }
static int _evhtp_glob_match2 (const char * pattern, size_t plen, const char * string, size_t str_len) static
Referenced by _evhtp_glob_match().
{
     while (plen) {
         switch (pattern[0]) {
             case '*':
                 while (pattern[1] == '*') {
                     pattern++;
                     plen--;
                 }
                 if (plen == 1) {
                     return 1;     /* match */
                 }
                 while (str_len) {
                     if (_evhtp_glob_match2(pattern + 1, plen - 1,
                                            string, str_len)) {
                         return 1; /* match */
                     }
                     string++;
                     str_len--;
                 }
                 return 0;         /* no match */
             default:
                 if (pattern[0] != string[0]) {
                     return 0;     /* no match */
                 }
                 string++;
                 str_len--;
                 break;
         } /* switch */
         pattern++;
         plen--;
         if (str_len == 0) {
             while (*pattern == '*') {
                 pattern++;
                 plen--;
             }
             break;
         }
     }
     if (plen == 0 && str_len == 0) {
         return 1;
     }
     return 0;
 } /* _evhtp_glob_match2 */
static int _evhtp_glob_match (const char * pattern, size_t pat_len, const char * string, size_t str_len) inline static
glob/wildcard type pattern matching.
Note: This code was derived from redis's (v2.6) stringmatchlen() function.
Parameters
pattern
string
Returns
References _evhtp_glob_match2(), and evhtp_unlikely.
Referenced by _evhtp_callback_find(), and _evhtp_request_find_vhost().
{
     if (evhtp_unlikely(!pattern || !string)) {
         return 0;
     }
     if (pat_len == 0) {
         pat_len = strlen(pattern);
     }
     if (str_len == 0) {
         str_len = strlen(string);
     }
     return _evhtp_glob_match2(pattern, pat_len, string, str_len);
 } /* _evhtp_glob_match */
static evhtp_callback_t* _evhtp_callback_find (evhtp_callbacks_t * cbs, const char * path, unsigned int * start_offset, unsigned int * end_offset) static
References _evhtp_glob_match(), evhtp_callback_type_glob, evhtp_callback_type_hash, evhtp_callback_type_regex, and evhtp_unlikely.
Referenced by _evhtp_request_set_callbacks().
{
 #ifndef EVHTP_DISABLE_REGEX
     regmatch_t         pmatch[28];
 #endif
     evhtp_callback_t * callback;
     if (evhtp_unlikely(cbs == NULL)) {
         return NULL;
     }
     TAILQ_FOREACH(callback, cbs, next) {
         switch (callback->type) {
             case evhtp_callback_type_hash:
                 if (strcmp(callback->val.path, path) == 0) {
                     *start_offset = 0;
                     *end_offset   = (unsigned int)strlen(path);
                     return callback;
                 }
                 break;
 #ifndef EVHTP_DISABLE_REGEX
             case evhtp_callback_type_regex:
                 if (regexec(callback->val.regex, path, callback->val.regex->re_nsub + 1, pmatch, 0) == 0) {
                     *start_offset = pmatch[callback->val.regex->re_nsub].rm_so;
                     *end_offset   = pmatch[callback->val.regex->re_nsub].rm_eo;
                     return callback;
                 }
                 break;
 #endif
             case evhtp_callback_type_glob:
             {
                 size_t path_len = strlen(path);
                 size_t glob_len = strlen(callback->val.glob);
                 if (_evhtp_glob_match(callback->val.glob, glob_len,
                                       path, path_len) == 1) {
                     *start_offset = 0;
                     *end_offset   = (unsigned int)path_len;
                     return callback;
                 }
             }
             default:
                 break;
         } /* switch */
     }
     return NULL;
 }         /* _evhtp_callback_find */
static evhtp_request_t* _evhtp_request_new (evhtp_connection_t * c) static
Creates a new evhtp_request_t.
Parameters
c
Returns
evhtp_request_t structure on success, otherwise NULL
References _evhtp_request_free(), evhtp_headers_t, EVHTP_RES_OK, and evhtp_unlikely.
Referenced by _evhtp_request_parser_start(), and evhtp_request_new().
{
     evhtp_request_t * req;
     uint8_t           error;
     if (evhtp_unlikely(!(req = calloc(sizeof(evhtp_request_t), 1)))) {
         return NULL;
     }
     error       = 1;
     req->conn   = c;
     req->htp    = c ? c->htp : NULL;
     req->status = EVHTP_RES_OK;
     do {
         if (evhtp_unlikely(!(req->buffer_in = evbuffer_new()))) {
             break;
         }
         if (evhtp_unlikely(!(req->buffer_out = evbuffer_new()))) {
             break;
         }
         if (evhtp_unlikely(!(req->headers_in = malloc(sizeof(evhtp_headers_t))))) {
             break;
         }
         if (evhtp_unlikely(!(req->headers_out = malloc(sizeof(evhtp_headers_t))))) {
             break;
         }
         TAILQ_INIT(req->headers_in);
         TAILQ_INIT(req->headers_out);
         error = 0;
     } while (0);
     if (error == 0) {
         return req;
     }
     _evhtp_request_free(req);
     return NULL;
 } /* _evhtp_request_new */
static evhtp_t* _evhtp_request_find_vhost (evhtp_t * evhtp, const char * name) inline static
References _evhtp_glob_match(), and evhtp_unlikely.
Referenced by _evhtp_request_parser_hostname(), and _evhtp_ssl_servername().
{
     evhtp_t       * evhtp_vhost;
     evhtp_alias_t * evhtp_alias;
     TAILQ_FOREACH(evhtp_vhost, &evhtp->vhosts, next_vhost) {
         if (evhtp_unlikely(evhtp_vhost->server_name == NULL)) {
             continue;
         }
         if (_evhtp_glob_match(evhtp_vhost->server_name, 0, name, 0) == 1) {
             return evhtp_vhost;
         }
         TAILQ_FOREACH(evhtp_alias, &evhtp_vhost->aliases, next) {
             if (evhtp_alias->alias == NULL) {
                 continue;
             }
             if (_evhtp_glob_match(evhtp_alias->alias, 0, name, 0) == 1) {
                 return evhtp_vhost;
             }
         }
     }
     return NULL;
 }
static int _evhtp_request_set_callbacks (evhtp_request_t * request) inline static
References _evhtp_callback_find(), cb, evhtp_alloc_assert, evhtp_unlikely, and hooks.
Referenced by _evhtp_request_parser_hostname(), and _evhtp_request_parser_path().
{
     evhtp_t            * evhtp;
     evhtp_connection_t * conn;
     evhtp_uri_t        * uri;
     evhtp_path_t       * path;
     evhtp_hooks_t      * hooks;
     evhtp_callback_t   * callback;
     evhtp_callback_cb    cb;
     void               * cbarg;
     if (request == NULL) {
         return -1;
     }
     if (evhtp_unlikely((evhtp = request->htp) == NULL)) {
         return -1;
     }
     if (evhtp_unlikely((conn = request->conn) == NULL)) {
         return -1;
     }
     if ((uri = request->uri) == NULL) {
         return -1;
     }
     if ((path = uri->path) == NULL) {
         return -1;
     }
     hooks    = NULL;
     callback = NULL;
     cb       = NULL;
     cbarg    = NULL;
     if ((callback = _evhtp_callback_find(evhtp->callbacks, path->full,
                                          &path->matched_soff, &path->matched_eoff))) {
         /* matched a callback using both path and file (/a/b/c/d) */
         cb    = callback->cb;
         cbarg = callback->cbarg;
         hooks = callback->hooks;
     } else if ((callback = _evhtp_callback_find(evhtp->callbacks, path->path,
                                                 &path->matched_soff, &path->matched_eoff))) {
         /* matched a callback using *just* the path (/a/b/c/) */
         cb    = callback->cb;
         cbarg = callback->cbarg;
         hooks = callback->hooks;
     } else {
         /* no callbacks found for either case, use defaults */
         cb    = evhtp->defaults.cb;
         cbarg = evhtp->defaults.cbarg;
         path->matched_soff = 0;
         path->matched_eoff = (unsigned int)strlen(path->full);
     }
     if (path->match_start == NULL) {
         path->match_start = calloc(strlen(path->full) + 1, 1);
         evhtp_alloc_assert(path->match_start);
     }
     if (path->match_end == NULL) {
         path->match_end = calloc(strlen(path->full) + 1, 1);
         evhtp_alloc_assert(path->match_end);
     }
     if (path->matched_soff != UINT_MAX /*ONIG_REGION_NOTPOS*/) {
         if (path->matched_eoff - path->matched_soff) {
             memcpy(path->match_start, (void *)(path->full + path->matched_soff),
                    path->matched_eoff - path->matched_soff);
         } else {
             memcpy(path->match_start, (void *)(path->full + path->matched_soff),
                    strlen((const char *)(path->full + path->matched_soff)));
         }
         memcpy(path->match_end,
                (void *)(path->full + path->matched_eoff),
                strlen(path->full) - path->matched_eoff);
     }
     if (hooks != NULL) {
         if (request->hooks == NULL) {
             request->hooks = malloc(sizeof(evhtp_hooks_t));
             evhtp_alloc_assert(request->hooks);
         }
         memcpy(request->hooks, hooks, sizeof(evhtp_hooks_t));
     }
     request->cb    = cb;
     request->cbarg = cbarg;
     return 0;
 } /* _evhtp_request_set_callbacks */
static int _evhtp_require_uri (evhtp_connection_t * c) static
References _evhtp_uri_new(), and evhtp_alloc_assert.
Referenced by _evhtp_request_parser_host(), _evhtp_request_parser_path(), and _evhtp_request_parser_port().
{
     if (c && c->request && !c->request->uri) {
         c->request->uri = _evhtp_uri_new();
         evhtp_alloc_assert(c->request->uri);
     }
     return 0;
 }
static int _evhtp_should_parse_query_body (evhtp_request_t * req) static
determines if the request body contains the query arguments. if the query is NULL and the contenet length of the body has never been drained, and the content-type is x-www-form-urlencoded, the function returns 1
Parameters
req
Returns
1 if evhtp can use the body as the query arguments, 0 otherwise.
References evhtp_kv_find(), and evhtp_request_content_len.
Referenced by _evhtp_request_parser_fini().
{
     const char * content_type;
     if (req == NULL) {
         return 0;
     }
     if (req->uri == NULL || req->uri->query != NULL) {
         return 0;
     }
     if (evhtp_request_content_len(req) == 0) {
         return 0;
     }
     if (evhtp_request_content_len(req) !=
         evbuffer_get_length(req->buffer_in)) {
         return 0;
     }
     content_type = evhtp_kv_find(req->headers_in, "content-type");
     if (content_type == NULL) {
         return 0;
     }
     if (strncasecmp(content_type, "application/x-www-form-urlencoded", 33)) {
         return 0;
     }
     return 1;
 }
static int _evhtp_create_headers (evhtp_header_t * header, void * arg) static
Referenced by _evhtp_create_reply(), and evhtp_make_request().
{
     evbuf_t * buf = arg;
     evbuffer_expand(buf, header->klen + 2 + header->vlen + 2);
     evbuffer_add(buf, header->key, header->klen);
     evbuffer_add(buf, ": ", 2);
     evbuffer_add(buf, header->val, header->vlen);
     evbuffer_add(buf, "\r\n", 2);
     return 0;
 }
static evbuf_t* _evhtp_create_reply (evhtp_request_t * request, evhtp_res code) static
References _evhtp_create_headers(), evhtp_assert, evhtp_header_find(), evhtp_header_new(), evhtp_headers_add_header(), evhtp_headers_for_each, evhtp_modp_sizetoa(), evhtp_modp_u32toa(), evhtp_modp_uchartoa, EVHTP_PROTO_10, EVHTP_PROTO_11, htparser_get_major(), htparser_get_minor(), htparser_get_multipart(), htparser_set_major(), htparser_set_minor(), and status_code_to_str().
Referenced by evhtp_send_reply(), and evhtp_send_reply_start().
{
     evbuf_t     * buf;
     const char  * content_type;
     char          res_buf[2048];
     int           sres;
     size_t        out_len;
     unsigned char major;
     unsigned char minor;
     char          out_buf[64];
     content_type = evhtp_header_find(request->headers_out, "Content-Type");
     out_len      = evbuffer_get_length(request->buffer_out);
     buf          = request->conn->scratch_buf;
     evhtp_assert(buf != NULL);
     evbuffer_drain(buf, -1);
     /*
      * buf          = evbuffer_new();
      * evhtp_alloc_assert(buf);
      */
     if (htparser_get_multipart(request->conn->parser) == 1) {
         goto check_proto;
     }
     if (out_len && request->chunked == 0) {
         /* add extra headers (like content-length/type) if not already present */
         if (!evhtp_header_find(request->headers_out, "Content-Length")) {
             /* convert the buffer_out length to a string and set
              * and add the new Content-Length header.
              */
             evhtp_modp_sizetoa(out_len, out_buf);
             evhtp_headers_add_header(request->headers_out,
                                      evhtp_header_new("Content-Length", out_buf, 0, 1));
         }
     }
 check_proto:
     /* add the proper keep-alive type headers based on http version */
     switch (request->proto) {
         case EVHTP_PROTO_11:
             if (request->keepalive == 0) {
                 /* protocol is HTTP/1.1 but client wanted to close */
                 evhtp_headers_add_header(request->headers_out,
                                          evhtp_header_new("Connection", "close", 0, 0));
             }
 #if 0
             if (!out_len && !evhtp_header_find(request->headers_out, "Content-Length")) {
                 evhtp_headers_add_header(request->headers_out,
                                          evhtp_header_new("Content-Length", "0", 0, 0));
             }
 #endif
             break;
         case EVHTP_PROTO_10:
             if (request->keepalive == 1) {
                 /* protocol is HTTP/1.0 and clients wants to keep established */
                 evhtp_headers_add_header(request->headers_out,
                                          evhtp_header_new("Connection", "keep-alive", 0, 0));
             }
             break;
         default:
             /* this sometimes happens when a response is made but paused before
              * the method has been parsed */
             htparser_set_major(request->conn->parser, 1);
             htparser_set_minor(request->conn->parser, 0);
             break;
     } /* switch */
     if (!content_type) {
         evhtp_headers_add_header(request->headers_out,
                                  evhtp_header_new("Content-Type", "text/plain", 0, 0));
     }
     /* attempt to add the status line into a temporary buffer and then use
      * evbuffer_add(). Using plain old snprintf() will be faster than
      * evbuffer_add_printf(). If the snprintf() fails, which it rarely should,
      * we fallback to using evbuffer_add_printf().
      */
     major = evhtp_modp_uchartoa(htparser_get_major(request->conn->parser));
     minor = evhtp_modp_uchartoa(htparser_get_minor(request->conn->parser));
     evhtp_modp_u32toa((uint32_t)code, out_buf);
     sres  = snprintf(res_buf, sizeof(res_buf), "HTTP/%c.%c %s %s\r\n",
                      major, minor, out_buf, status_code_to_str(code));
     if (sres >= sizeof(res_buf) || sres < 0) {
         /* failed to fit the whole thing in the res_buf, so just fallback to
          * using evbuffer_add_printf().
          */
         evbuffer_add_printf(buf, "HTTP/%c.%c %d %s\r\n",
                             major, minor,
                             code, status_code_to_str(code));
     } else {
         /* copy the res_buf using evbuffer_add() instead of add_printf() */
         evbuffer_add(buf, res_buf, sres);
     }
     evhtp_headers_for_each(request->headers_out, _evhtp_create_headers, buf);
     evbuffer_add(buf, "\r\n", 2);
     if (evbuffer_get_length(request->buffer_out)) {
         evbuffer_add_buffer(buf, request->buffer_out);
     }
     return buf;
 }     /* _evhtp_create_reply */
static void _evhtp_connection_resumecb (int fd, short events, void * arg) static
References _evhtp_connection_readcb(), evhtp_connection_free(), and EVHTP_RES_OK.
Referenced by _evhtp_connection_accept().
{
     evhtp_connection_t * c = arg;
     c->paused = 0;
     if (c->request) {
         c->request->status = EVHTP_RES_OK;
     }
     if (c->free_connection == 1) {
         evhtp_connection_free(c);
         return;
     }
     /* XXX this is a hack to show a potential fix for issues/86, the main indea
      * is that you call resume AFTER you have sent the reply (not BEFORE).
      *
      * When it has been decided this is a proper fix, the pause bit should be
      * changed to a state-type flag.
      */
     if (evbuffer_get_length(bufferevent_get_output(c->bev))) {
         bufferevent_enable(c->bev, EV_WRITE);
         c->waiting = 1;
     } else {
         bufferevent_enable(c->bev, EV_READ | EV_WRITE);
         _evhtp_connection_readcb(c->bev, c);
     }
 }
static void _evhtp_connection_writecb (evbev_t * bev, void * arg) static
References _evhtp_connection_readcb(), _evhtp_connection_write_hook(), _evhtp_request_free(), evhtp_connection_free(), evhtp_unlikely, htp_log_debug, htp_type_request, htparser_init(), and htparser_set_userdata().
Referenced by _evhtp_connection_accept(), and _evhtp_connection_eventcb().
{
     evhtp_connection_t * c = arg;
     htp_log_debug("c->request = %p", c->request);
     if (evhtp_unlikely(c->request == NULL)) {
         return;
     }
     _evhtp_connection_write_hook(c);
     if (evhtp_unlikely(c->paused == 1)) {
         return;
     }
     if (evhtp_unlikely(c->waiting == 1)) {
         c->waiting = 0;
         bufferevent_enable(bev, EV_READ);
         if (evbuffer_get_length(bufferevent_get_input(bev))) {
             _evhtp_connection_readcb(bev, arg);
         }
         return;
     }
     if (c->request->finished == 0 || evbuffer_get_length(bufferevent_get_output(bev))) {
         return;
     }
     /*
      * if there is a set maximum number of keepalive requests configured, check
      * to make sure we are not over it. If we have gone over the max we set the
      * keepalive bit to 0, thus closing the connection.
      */
     if (c->htp->max_keepalive_requests) {
         if (++c->num_requests >= c->htp->max_keepalive_requests) {
             c->request->keepalive = 0;
         }
     }
     if (c->request->keepalive == 1) {
         _evhtp_request_free(c->request);
         c->keepalive       = 1;
         c->request         = NULL;
         c->body_bytes_read = 0;
         if (c->htp->parent && c->vhost_via_sni == 0) {
             /* this request was servied by a virtual host evhtp_t structure
              * which was *NOT* found via SSL SNI lookup. In this case we want to
              * reset our connections evhtp_t structure back to the original so
              * that subsequent requests can have a different Host: header.
              */
             evhtp_t * orig_htp = c->htp->parent;
             c->htp = orig_htp;
         }
         htparser_init(c->parser, htp_type_request);
         htparser_set_userdata(c->parser, c);
         return;
     } else {
         evhtp_connection_free(c);
         return;
     }
     return;
 } /* _evhtp_connection_writecb */
static void _evhtp_connection_eventcb (evbev_t * bev, short events, void * arg) static
References _evhtp_connection_error_hook(), _evhtp_connection_readcb(), _evhtp_connection_writecb(), evhtp_connection_free(), evhtp_likely, and evhtp_type_client.
Referenced by _evhtp_connection_accept(), evhtp_connection_new_dns(), and evhtp_connection_ssl_new().
{
     evhtp_connection_t * c = arg;
     if (c->hooks && c->hooks->on_event) {
         (c->hooks->on_event)(c, events, c->hooks->on_event_arg);
     }
     if ((events & BEV_EVENT_CONNECTED)) {
         if (evhtp_likely(c->type == evhtp_type_client)) {
             c->connected = 1;
             bufferevent_setcb(bev,
                               _evhtp_connection_readcb,
                               _evhtp_connection_writecb,
                               _evhtp_connection_eventcb, c);
         }
         return;
     }
 #ifndef EVHTP_DISABLE_SSL
     if (c->ssl && !(events & BEV_EVENT_EOF)) {
         /* XXX need to do better error handling for SSL specific errors */
         c->error = 1;
         if (c->request) {
             c->request->error = 1;
         }
     }
 #endif
     if (events == (BEV_EVENT_EOF | BEV_EVENT_READING)) {
         if (errno == EAGAIN) {
             /* libevent will sometimes recv again when it's not actually ready,
              * this results in a 0 return value, and errno will be set to EAGAIN
              * (try again). This does not mean there is a hard socket error, but
              * simply needs to be read again.
              *
              * but libevent will disable the read side of the bufferevent
              * anyway, so we must re-enable it.
              */
             bufferevent_enable(bev, EV_READ);
             errno = 0;
             return;
         }
     }
     c->error     = 1;
     c->connected = 0;
     _evhtp_connection_error_hook(c, events);
     if (c->paused == 1) {
         /* we are currently paused, so we don't want to free just yet, let's
          * wait till the next loop.
          */
         c->free_connection = 1;
     } else {
         evhtp_connection_free((evhtp_connection_t *)arg);
     }
 } /* _evhtp_connection_eventcb */
static int _evhtp_run_pre_accept (evhtp_t * htp, evhtp_connection_t * conn) static
References args, evhtp_likely, and EVHTP_RES_OK.
Referenced by _evhtp_connection_accept().
{
     void    * args;
     evhtp_res res;
     if (evhtp_likely(htp->defaults.pre_accept == NULL)) {
         return 0;
     }
     args = htp->defaults.pre_accept_cbarg;
     res  = htp->defaults.pre_accept(conn, args);
     if (res != EVHTP_RES_OK) {
         return -1;
     }
     return 0;
 }
static int _evhtp_connection_accept (evbase_t * evbase, evhtp_connection_t * connection) static
References _evhtp_connection_eventcb(), _evhtp_connection_readcb(), _evhtp_connection_resumecb(), _evhtp_connection_writecb(), _evhtp_run_pre_accept(), evhtp_connection_set_timeouts(), and htp_log_debug.
Referenced by _evhtp_accept_cb(), and _evhtp_run_in_thread().
{
     struct timeval * c_recv_timeo;
     struct timeval * c_send_timeo;
     if (_evhtp_run_pre_accept(connection->htp, connection) < 0) {
         evutil_closesocket(connection->sock);
         return -1;
     }
 #ifndef EVHTP_DISABLE_SSL
     if (connection->htp->ssl_ctx != NULL) {
         connection->ssl = SSL_new(connection->htp->ssl_ctx);
         connection->bev = bufferevent_openssl_socket_new(evbase,
                                                          connection->sock,
                                                          connection->ssl,
                                                          BUFFEREVENT_SSL_ACCEPTING,
                                                          connection->htp->bev_flags);
         SSL_set_app_data(connection->ssl, connection);
         goto end;
     }
 #endif
     connection->bev = bufferevent_socket_new(evbase,
                                              connection->sock,
                                              connection->htp->bev_flags);
     htp_log_debug("enter sock=%d\n", connection->sock);
 #ifndef EVHTP_DISABLE_SSL
 end:
 #endif
     if (connection->recv_timeo.tv_sec || connection->recv_timeo.tv_usec) {
         c_recv_timeo = &connection->recv_timeo;
     } else if (connection->htp->recv_timeo.tv_sec ||
                connection->htp->recv_timeo.tv_usec) {
         c_recv_timeo = &connection->htp->recv_timeo;
     } else {
         c_recv_timeo = NULL;
     }
     if (connection->send_timeo.tv_sec || connection->send_timeo.tv_usec) {
         c_send_timeo = &connection->send_timeo;
     } else if (connection->htp->send_timeo.tv_sec ||
                connection->htp->send_timeo.tv_usec) {
         c_send_timeo = &connection->htp->send_timeo;
     } else {
         c_send_timeo = NULL;
     }
     evhtp_connection_set_timeouts(connection, c_recv_timeo, c_send_timeo);
     connection->resume_ev = event_new(evbase, -1, EV_READ | EV_PERSIST,
                                       _evhtp_connection_resumecb, connection);
     event_add(connection->resume_ev, NULL);
     bufferevent_enable(connection->bev, EV_READ);
     bufferevent_setcb(connection->bev,
                       _evhtp_connection_readcb,
                       _evhtp_connection_writecb,
                       _evhtp_connection_eventcb, connection);
     return 0;
 }     /* _evhtp_connection_accept */
static void _evhtp_default_request_cb (evhtp_request_t * request, void * arg) static
References evhtp_header_new(), evhtp_headers_add_header(), EVHTP_RES_NOTFOUND, and evhtp_send_reply().
Referenced by evhtp_new().
{
     evhtp_headers_add_header(request->headers_out,
                              evhtp_header_new("Content-Length", "0", 0, 0));
     evhtp_send_reply(request, EVHTP_RES_NOTFOUND);
 }
static int _evhtp_run_post_accept (evhtp_t * htp, evhtp_connection_t * connection) static
References args, evhtp_likely, and EVHTP_RES_OK.
Referenced by _evhtp_accept_cb(), and _evhtp_run_in_thread().
{
     void    * args;
     evhtp_res res;
     if (evhtp_likely(htp->defaults.post_accept == NULL)) {
         return 0;
     }
     args = htp->defaults.post_accept_cbarg;
     res  = htp->defaults.post_accept(connection, args);
     if (res != EVHTP_RES_OK) {
         return -1;
     }
     return 0;
 }
static void _evhtp_run_in_thread (evthr_t * thr, void * arg, void * shared) static
References _evhtp_connection_accept(), _evhtp_run_post_accept(), evhtp_connection_free(), and evthr_get_base().
Referenced by _evhtp_accept_cb().
{
     evhtp_t            * htp        = shared;
     evhtp_connection_t * connection = arg;
     connection->evbase = evthr_get_base(thr);
     connection->thread = thr;
     if (_evhtp_connection_accept(connection->evbase, connection) < 0) {
         evhtp_connection_free(connection);
         return;
     }
     if (_evhtp_run_post_accept(htp, connection) < 0) {
         evhtp_connection_free(connection);
         return;
     }
 }
static void _evhtp_accept_cb (evserv_t * serv, int fd, struct sockaddr * s, int sl, void * arg) static
References _evhtp_connection_accept(), _evhtp_connection_new(), _evhtp_run_in_thread(), _evhtp_run_post_accept(), evhtp_alloc_assert, evhtp_connection_free(), evhtp_type_server, evhtp_unlikely, evthr_pool_defer(), EVTHR_RES_OK, and htp_log_debug.
Referenced by evhtp_accept_socket().
{
     evhtp_t            * htp = arg;
     evhtp_connection_t * connection;
     if (evhtp_unlikely(!(connection = _evhtp_connection_new(htp, fd, evhtp_type_server)))) {
         return;
     }
     htp_log_debug("fd = %d, conn = %p", fd, connection);
     connection->saddr = malloc(sl);
     evhtp_alloc_assert(connection->saddr);
     memcpy(connection->saddr, s, sl);
 #ifndef EVHTP_DISABLE_EVTHR
     if (htp->thr_pool != NULL) {
         if (evthr_pool_defer(htp->thr_pool,
                              _evhtp_run_in_thread, connection) != EVTHR_RES_OK) {
             evutil_closesocket(connection->sock);
             evhtp_connection_free(connection);
             return;
         }
         return;
     }
 #endif
     connection->evbase = htp->evbase;
     if (_evhtp_connection_accept(htp->evbase, connection) < 0) {
         evhtp_connection_free(connection);
         return;
     }
     if (_evhtp_run_post_accept(htp, connection) < 0) {
         evhtp_connection_free(connection);
         return;
     }
 } /* _evhtp_accept_cb */
static unsigned long _evhtp_ssl_get_thread_id (void) static
Referenced by evhtp_ssl_use_threads().
{
 #ifndef WIN32
     return (unsigned long)pthread_self();
 #else
     return (unsigned long)(pthread_self().p);
 #endif
 }
static void _evhtp_ssl_thread_lock (int mode, int type, const char * file, int line) static
References ssl_locks, and ssl_num_locks.
Referenced by evhtp_ssl_use_threads().
{
     if (type < ssl_num_locks) {
         if (mode & CRYPTO_LOCK) {
             pthread_mutex_lock(&(ssl_locks[type]));
         } else {
             pthread_mutex_unlock(&(ssl_locks[type]));
         }
     }
 }
static void _evhtp_ssl_delete_scache_ent (evhtp_ssl_ctx_t * ctx, evhtp_ssl_sess_t * sess) static
Referenced by evhtp_ssl_init().
{
     evhtp_t         * htp;
     evhtp_ssl_cfg_t * cfg;
     unsigned char   * sid;
     unsigned int      slen;
     htp  = (evhtp_t *)SSL_CTX_get_app_data(ctx);
     cfg  = htp->ssl_cfg;
     sid  = sess->session_id;
     slen = sess->session_id_length;
     if (cfg->scache_del) {
         (cfg->scache_del)(htp, sid, slen);
     }
 }
static int _evhtp_ssl_add_scache_ent (evhtp_ssl_t * ssl, evhtp_ssl_sess_t * sess) static
Referenced by evhtp_ssl_init().
{
     evhtp_connection_t * connection;
     evhtp_ssl_cfg_t    * cfg;
     unsigned char      * sid;
     int                  slen;
     connection = (evhtp_connection_t *)SSL_get_app_data(ssl);
     cfg        = connection->htp->ssl_cfg;
     sid        = sess->session_id;
     slen       = sess->session_id_length;
     SSL_set_timeout(sess, cfg->scache_timeout);
     if (cfg->scache_add) {
         return (cfg->scache_add)(connection, sid, slen, sess);
     }
     return 0;
 }
static evhtp_ssl_sess_t* _evhtp_ssl_get_scache_ent (evhtp_ssl_t * ssl, unsigned char * sid, int sid_len, int * copy) static
Referenced by evhtp_ssl_init().
{
     evhtp_connection_t * connection;
     evhtp_ssl_cfg_t    * cfg;
     evhtp_ssl_sess_t   * sess;
     connection = (evhtp_connection_t * )SSL_get_app_data(ssl);
     cfg        = connection->htp->ssl_cfg;
     sess       = NULL;
     if (cfg->scache_get) {
         sess = (cfg->scache_get)(connection, sid, sid_len);
     }
     *copy = 0;
     return sess;
 }
static int _evhtp_ssl_servername (evhtp_ssl_t * ssl, int * unused, void * arg) static
References _evhtp_request_find_vhost().
Referenced by evhtp_accept_socket().
{
     const char         * sname;
     evhtp_connection_t * connection;
     evhtp_t            * evhtp;
     evhtp_t            * evhtp_vhost;
     if (!(sname = SSL_get_servername(ssl, TLSEXT_NAMETYPE_host_name))) {
         return SSL_TLSEXT_ERR_NOACK;
     }
     if (!(connection = SSL_get_app_data(ssl))) {
         return SSL_TLSEXT_ERR_NOACK;
     }
     if (!(evhtp = connection->htp)) {
         return SSL_TLSEXT_ERR_NOACK;
     }
     if ((evhtp_vhost = _evhtp_request_find_vhost(evhtp, sname))) {
         connection->htp           = evhtp_vhost;
         connection->vhost_via_sni = 1;
         SSL_set_SSL_CTX(ssl, evhtp_vhost->ssl_ctx);
         SSL_set_options(ssl, SSL_CTX_get_options(ssl->ctx));
         if ((SSL_get_verify_mode(ssl) == SSL_VERIFY_NONE) ||
             (SSL_num_renegotiations(ssl) == 0)) {
             SSL_set_verify(ssl, SSL_CTX_get_verify_mode(ssl->ctx),
                            SSL_CTX_get_verify_callback(ssl->ctx));
         }
         return SSL_TLSEXT_ERR_OK;
     }
     return SSL_TLSEXT_ERR_NOACK;
 } /* _evhtp_ssl_servername */
htp_method evhtp_request_get_method (evhtp_request_t * r)
returns the htp_method enum version of the request method.
Parameters
r
Returns
htp_method enum
References evhtp_assert, and htparser_get_method().
Referenced by print_path().
{
     evhtp_assert(r != NULL);
     evhtp_assert(r->conn != NULL);
     evhtp_assert(r->conn->parser != NULL);
     return htparser_get_method(r->conn->parser);
 }
void evhtp_connection_pause (evhtp_connection_t * c)
pauses a connection (disables reading)
Parameters
c a evhtp_connection_t * structure
References evhtp_assert.
Referenced by evhtp_request_pause().
{
     evhtp_assert(c != NULL);
     c->paused = 1;
     bufferevent_disable(c->bev, EV_READ | EV_WRITE);
     return;
 }
void evhtp_connection_resume (evhtp_connection_t * c)
resumes a connection (enables reading) and activates resume event.
Parameters
c
References evhtp_assert.
Referenced by _evhtp_connection_readcb(), and evhtp_request_resume().
{
     evhtp_assert(c != NULL);
     c->paused = 0;
     event_active(c->resume_ev, EV_WRITE, 1);
     return;
 }
void evhtp_request_pause (evhtp_request_t * request)
Wrapper around evhtp_connection_pause.
See also
evhtp_connection_pause
Parameters
request
References evhtp_assert, evhtp_connection_pause(), and EVHTP_RES_PAUSE.
Referenced by _evhtp_connection_readcb(), app_process_request(), and frontend_cb().
{
     evhtp_assert(request != NULL);
     request->status = EVHTP_RES_PAUSE;
     evhtp_connection_pause(request->conn);
 }
void evhtp_request_resume (evhtp_request_t * request)
Wrapper around evhtp_connection_resume.
See also
evhtp_connection_resume
Parameters
request
References evhtp_assert, and evhtp_connection_resume().
Referenced by backend_cb(), redis_get_srcport_cb(), and resume_request_timer().
{
     evhtp_assert(request != NULL);
     evhtp_connection_resume(request->conn);
 }
evhtp_header_t* evhtp_header_key_add (evhtp_headers_t * headers, const char * key, char kalloc)
creates a new evhtp_header_t, sets only the key, and adds to the evhtp_headers TAILQ
Parameters
headers the evhtp_headers_t TAILQ (evhtp_kv_t)
key a null terminated string
kalloc if 1 the string will be copied, otherwise assigned
Returns
an evhtp_header_t pointer or NULL on error
References evhtp_header_new(), evhtp_header_t, and evhtp_headers_add_header().
Referenced by _evhtp_request_parser_header_key().
{
     evhtp_header_t * header;
     if (!(header = evhtp_header_new(key, NULL, kalloc, 0))) {
         return NULL;
     }
     evhtp_headers_add_header(headers, header);
     return header;
 }
evhtp_header_t* evhtp_header_val_add (evhtp_headers_t * headers, const char * val, char valloc)
finds the last header in the headers tailq and adds the value
Parameters
headers the evhtp_headers_t TAILQ (evhtp_kv_t)
val a null terminated string
valloc if 1 the string will be copied, otherwise assigned
Returns
an evhtp_header_t pointer or NULL on error
References evhtp_header_t, and evhtp_headers_s.
Referenced by _evhtp_request_parser_header_val().
{
     evhtp_header_t * header;
     if (!headers || !val) {
         return NULL;
     }
     if (!(header = TAILQ_LAST(headers, evhtp_headers_s))) {
         return NULL;
     }
     if (header->val != NULL) {
         return NULL;
     }
     header->vlen = strlen(val);
     if (valloc == 1) {
         header->val = malloc(header->vlen + 1);
         header->val[header->vlen] = '\0';
         memcpy(header->val, val, header->vlen);
     } else {
         header->val = (char *)val;
     }
     header->v_heaped = valloc;
     return header;
 }
evhtp_kvs_t* evhtp_kvs_new (void)
creates an empty list of key/values
Returns
References evhtp_alloc_assert.
                     {
     evhtp_kvs_t * kvs;
     kvs = malloc(sizeof(evhtp_kvs_t));
     evhtp_alloc_assert(kvs);
     TAILQ_INIT(kvs);
     return kvs;
 }
evhtp_kv_t* evhtp_kv_new (const char * key, const char * val, char kalloc, char valloc)
Allocates a new key/value structure.
Parameters
key null terminated string
val null terminated string
kalloc if set to 1, the key will be copied, if 0 no copy is done.
valloc if set to 1, the val will be copied, if 0 no copy is done.
Returns
evhtp_kv_t * on success, NULL on error.
References evhtp_alloc_assert, and evhtp_safe_free.
Referenced by evhtp_kvs_add_kvs(), and evhtp_parse_query_wflags().
{
     evhtp_kv_t * kv;
     kv           = malloc(sizeof(evhtp_kv_t));
     evhtp_alloc_assert(kv);
     kv->k_heaped = kalloc;
     kv->v_heaped = valloc;
     kv->klen     = 0;
     kv->vlen     = 0;
     kv->key      = NULL;
     kv->val      = NULL;
     if (key != NULL) {
         kv->klen = strlen(key);
         if (kalloc == 1) {
             char * s;
             if (!(s = malloc(kv->klen + 1))) {
                 evhtp_safe_free(kv, free);
                 return NULL;
             }
             memcpy(s, key, kv->klen);
             s[kv->klen] = '\0';
             kv->key     = s;
         } else {
             kv->key = (char *)key;
         }
     }
     if (val != NULL) {
         kv->vlen = strlen(val);
         if (valloc == 1) {
             char * s = malloc(kv->vlen + 1);
             s[kv->vlen] = '\0';
             memcpy(s, val, kv->vlen);
             kv->val     = s;
         } else {
             kv->val = (char *)val;
         }
     }
     return kv;
 }     /* evhtp_kv_new */
void evhtp_kv_free (evhtp_kv_t * kv)
frees resources allocated for a single key/value
Parameters
kv
References evhtp_safe_free, and evhtp_unlikely.
Referenced by evhtp_kv_rm_and_free(), and evhtp_kvs_free().
{
     if (evhtp_unlikely(kv == NULL)) {
         return;
     }
     if (kv->k_heaped) {
         evhtp_safe_free(kv->key, free);
     }
     if (kv->v_heaped) {
         evhtp_safe_free(kv->val, free);
     }
     evhtp_safe_free(kv, free);
 }
void evhtp_kv_rm_and_free (evhtp_kvs_t * kvs, evhtp_kv_t * kv)
free's resources associated with 'kv' if ONLY found within the key/value list
Parameters
kvs
kv
References evhtp_kv_free(), and evhtp_unlikely.
Referenced by evhtp_send_reply_chunk_start().
{
     if (evhtp_unlikely(kvs == NULL || kv == NULL)) {
         return;
     }
     TAILQ_REMOVE(kvs, kv, next);
     evhtp_kv_free(kv);
 }
void evhtp_kvs_free (evhtp_kvs_t * kvs)
frees a the list of key/values, and all underlying entries
Parameters
kvs
References evhtp_kv_free(), evhtp_safe_free, and evhtp_unlikely.
{
     evhtp_kv_t * kv;
     evhtp_kv_t * save;
     if (evhtp_unlikely(kvs == NULL)) {
         return;
     }
     for (kv = TAILQ_FIRST(kvs); kv != NULL; kv = save) {
         save = TAILQ_NEXT(kv, next);
         TAILQ_REMOVE(kvs, kv, next);
         evhtp_safe_free(kv, evhtp_kv_free);
     }
     evhtp_safe_free(kvs, free);
 }
int evhtp_kvs_for_each (evhtp_kvs_t * kvs, evhtp_kvs_iterator cb, void * arg)
callback iterator which executes 'cb' for every entry in 'kvs'
Parameters
kvs
cb
arg
Returns
References cb.
Referenced by query_test().
{
     evhtp_kv_t * kv;
     if (kvs == NULL || cb == NULL) {
         return -1;
     }
     TAILQ_FOREACH(kv, kvs, next) {
         int res;
         if ((res = cb(kv, arg))) {
             return res;
         }
     }
     return 0;
 }
const char* evhtp_kv_find (evhtp_kvs_t * kvs, const char * key)
find the string value of 'key' from the key/value list 'kvs'
Parameters
kvs
key
Returns
NULL if not found
References evhtp_unlikely.
Referenced by _evhtp_should_parse_query_body(), and query_test().
{
     evhtp_kv_t * kv;
     if (evhtp_unlikely(kvs == NULL || key == NULL)) {
         return NULL;
     }
     TAILQ_FOREACH(kv, kvs, next) {
         if (strcasecmp(kv->key, key) == 0) {
             return kv->val;
         }
     }
     return NULL;
 }
evhtp_kv_t* evhtp_kvs_find_kv (evhtp_kvs_t * kvs, const char * key)
find the evhtp_kv_t reference 'key' from the k/val list 'kvs'
Parameters
kvs
key
Returns
References evhtp_unlikely.
Referenced by query_test().
{
     evhtp_kv_t * kv;
     if (evhtp_unlikely(kvs == NULL || key == NULL)) {
         return NULL;
     }
     TAILQ_FOREACH(kv, kvs, next) {
         if (strcasecmp(kv->key, key) == 0) {
             return kv;
         }
     }
     return NULL;
 }
void evhtp_kvs_add_kv (evhtp_kvs_t * kvs, evhtp_kv_t * kv)
appends a key/val structure to a evhtp_kvs_t tailq
Parameters
kvs an evhtp_kvs_t structure
kv an evhtp_kv_t structure
References evhtp_unlikely.
Referenced by evhtp_kvs_add_kvs(), and evhtp_parse_query_wflags().
{
     if (evhtp_unlikely(kvs == NULL || kv == NULL)) {
         return;
     }
     TAILQ_INSERT_TAIL(kvs, kv, next);
 }
void evhtp_kvs_add_kvs (evhtp_kvs_t * dst, evhtp_kvs_t * src)
appends all key/val structures from src tailq onto dst tailq
Parameters
dst an evhtp_kvs_t structure
src an evhtp_kvs_t structure
References evhtp_kv_new(), and evhtp_kvs_add_kv().
{
     if (dst == NULL || src == NULL) {
         return;
     }
     evhtp_kv_t * kv;
     TAILQ_FOREACH(kv, src, next) {
         evhtp_kvs_add_kv(dst, evhtp_kv_new(kv->key,
                                            kv->val,
                                            kv->k_heaped,
                                            kv->v_heaped));
     }
 }
static int evhtp_is_hex_query_char (unsigned char ch) inline static
Referenced by evhtp_parse_query_wflags().
{
     switch (ch) {
         case 'a': case 'A':
         case 'b': case 'B':
         case 'c': case 'C':
         case 'd': case 'D':
         case 'e': case 'E':
         case 'f': case 'F':
         case '0':
         case '1':
         case '2':
         case '3':
         case '4':
         case '5':
         case '6':
         case '7':
         case '8':
         case '9':
             return 1;
         default:
             return 0;
     } /* switch */
 }
int evhtp_unescape_string (unsigned char ** out, unsigned char * str, size_t str_len)
Unescapes strings like '%7B1,%202,%203%7D' would become '{1, 2, 3}'.
Parameters
out double pointer where output is stored. This is allocated by the user.
str the string to unescape
str_len the length of the string to unescape
Returns
0 on success, -1 on error
References unscape_state_hex1, unscape_state_hex2, and unscape_state_start.
{
     unsigned char    * optr;
     unsigned char    * sptr;
     unsigned char      d;
     unsigned char      ch;
     unsigned char      c;
     size_t             i;
     enum unscape_state state;
     if (out == NULL || *out == NULL) {
         return -1;
     }
     state = unscape_state_start;
     optr  = *out;
     sptr  = str;
     d     = 0;
     for (i = 0; i < str_len; i++) {
         ch = *sptr++;
         switch (state) {
             case unscape_state_start:
                 if (ch == '%') {
                     state = unscape_state_hex1;
                     break;
                 }
                 *optr++ = ch;
                 break;
             case unscape_state_hex1:
                 if (ch >= '0' && ch <= '9') {
                     d     = (unsigned char)(ch - '0');
                     state = unscape_state_hex2;
                     break;
                 }
                 c = (unsigned char)(ch | 0x20);
                 if (c >= 'a' && c <= 'f') {
                     d     = (unsigned char)(c - 'a' + 10);
                     state = unscape_state_hex2;
                     break;
                 }
                 state   = unscape_state_start;
                 *optr++ = ch;
                 break;
             case unscape_state_hex2:
                 state   = unscape_state_start;
                 if (ch >= '0' && ch <= '9') {
                     ch      = (unsigned char)((d << 4) + ch - '0');
                     *optr++ = ch;
                     break;
                 }
                 c = (unsigned char)(ch | 0x20);
                 if (c >= 'a' && c <= 'f') {
                     ch      = (unsigned char)((d << 4) + c - 'a' + 10);
                     *optr++ = ch;
                     break;
                 }
                 break;
         } /* switch */
     }
     return 0;
 }         /* evhtp_unescape_string */
evhtp_query_t* evhtp_parse_query_wflags (const char * query, size_t len, int flags)
Parses the query portion of the uri into a set of key/values.
Parses query arguments like "?herp=&foo=bar;blah=baz&a=%3"
Parameters
query data containing the uri query arguments
len size of the data
flags parse query flags to alter 'strictness' (see EVHTP_PARSE_QUERY_FLAG_*)
Returns
evhtp_query_t * on success, NULL on error
References evhtp_alloc_assert, evhtp_is_hex_query_char(), evhtp_kv_new(), evhtp_kvs_add_kv(), EVHTP_PARSE_QUERY_FLAG_ALLOW_EMPTY_VALS, EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS, EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX, EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP, evhtp_query_free, evhtp_query_new, evhtp_query_t, evhtp_safe_free, s_query_key, s_query_key_hex_1, s_query_key_hex_2, s_query_start, s_query_val, s_query_val_hex_1, and s_query_val_hex_2.
Referenced by _evhtp_request_parser_args(), evhtp_parse_query(), and query_test().
{
     evhtp_query_t    * query_args;
     query_parser_state state;
     size_t             key_idx;
     size_t             val_idx;
     unsigned char      ch;
     size_t             i;
     if (len > (SIZE_MAX - (len + 2))) {
         return NULL;
     }
     query_args = evhtp_query_new();
     state      = s_query_start;
     key_idx    = 0;
     val_idx    = 0;
 #ifdef EVHTP_HAS_C99
     char   key_buf[len + 1];
     char   val_buf[len + 1];
 #else
     char * key_buf;
     char * val_buf;
     key_buf = malloc(len + 1);
     evhtp_alloc_assert(key_buf);
     val_buf = malloc(len + 1);
     evhtp_alloc_assert(val_buf);
 #endif
     for (i = 0; i < len; i++) {
         ch = query[i];
         if (key_idx >= len || val_idx >= len) {
             goto error;
         }
         switch (state) {
             case s_query_start:
                 key_idx    = 0;
                 val_idx    = 0;
                 key_buf[0] = '\0';
                 val_buf[0] = '\0';
                 state      = s_query_key;
             /* Fall through. */
             case s_query_key:
                 switch (ch) {
                     case '=':
                         state = s_query_val;
                         break;
                     case '%':
                         key_buf[key_idx++] = ch;
                         key_buf[key_idx]   = '\0';
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX)) {
                             state = s_query_key_hex_1;
                         }
                         break;
                     case ';':
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP)) {
                             key_buf[key_idx++] = ch;
                             key_buf[key_idx]   = '\0';
                             break;
                         }
                     /* otherwise we fallthrough */
                     case '&':
                         /* in this state, we have a NULL value */
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS)) {
                             goto error;
                         }
                         /* insert the key with value of NULL and set the
                          * state back to parsing s_query_key.
                          */
                         evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, NULL, 1, 1));
                         key_idx            = 0;
                         val_idx            = 0;
                         key_buf[0]         = '\0';
                         val_buf[0]         = '\0';
                         state              = s_query_key;
                         break;
                     default:
                         key_buf[key_idx++] = ch;
                         key_buf[key_idx]   = '\0';
                         break;
                 } /* switch */
                 break;
             case s_query_key_hex_1:
                 if (!evhtp_is_hex_query_char(ch)) {
                     /* not hex, so we treat as a normal key */
                     if ((key_idx + 2) >= len) {
                         /* we need to insert \%<ch>, but not enough space */
                         goto error;
                     }
                     key_buf[key_idx - 1] = '%';
                     key_buf[key_idx++]   = ch;
                     key_buf[key_idx]     = '\0';
                     state = s_query_key;
                     break;
                 }
                 key_buf[key_idx++] = ch;
                 key_buf[key_idx]   = '\0';
                 state = s_query_key_hex_2;
                 break;
             case s_query_key_hex_2:
                 if (!evhtp_is_hex_query_char(ch)) {
                     goto error;
                 }
                 key_buf[key_idx++] = ch;
                 key_buf[key_idx]   = '\0';
                 state = s_query_key;
                 break;
             case s_query_val:
                 switch (ch) {
                     case ';':
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP)) {
                             val_buf[val_idx++] = ch;
                             val_buf[val_idx]   = '\0';
                             break;
                         }
                     case '&':
                         evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, val_buf, 1, 1));
                         key_idx            = 0;
                         val_idx            = 0;
                         key_buf[0]         = '\0';
                         val_buf[0]         = '\0';
                         state              = s_query_key;
                         break;
                     case '%':
                         val_buf[val_idx++] = ch;
                         val_buf[val_idx]   = '\0';
                         if (!(flags & EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX)) {
                             state = s_query_val_hex_1;
                         }
                         break;
                     default:
                         val_buf[val_idx++] = ch;
                         val_buf[val_idx]   = '\0';
                         break;
                 }     /* switch */
                 break;
             case s_query_val_hex_1:
                 if (!evhtp_is_hex_query_char(ch)) {
                     /* not really a hex val */
                     if ((val_idx + 2) >= len) {
                         /* we need to insert \%<ch>, but not enough space */
                         goto error;
                     }
                     if (val_idx == 0) {
                         goto error;
                     }
                     val_buf[val_idx - 1] = '%';
                     val_buf[val_idx++]   = ch;
                     val_buf[val_idx]     = '\0';
                     state = s_query_val;
                     break;
                 }
                 val_buf[val_idx++] = ch;
                 val_buf[val_idx]   = '\0';
                 state = s_query_val_hex_2;
                 break;
             case s_query_val_hex_2:
                 if (!evhtp_is_hex_query_char(ch)) {
                     goto error;
                 }
                 val_buf[val_idx++] = ch;
                 val_buf[val_idx]   = '\0';
                 state = s_query_val;
                 break;
             default:
                 /* bad state */
                 goto error;
         }       /* switch */
     }
     if (key_idx) {
         do {
             if (val_idx) {
                 evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, val_buf, 1, 1));
                 break;
             }
             if (state >= s_query_val) {
                 if (!(flags & EVHTP_PARSE_QUERY_FLAG_ALLOW_EMPTY_VALS)) {
                     goto error;
                 }
                 evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, "", 1, 1));
                 break;
             }
             if (!(flags & EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS)) {
                 goto error;
             }
             evhtp_kvs_add_kv(query_args, evhtp_kv_new(key_buf, NULL, 1, 0));
         } while (0);
     }
 #ifndef EVHTP_HAS_C99
     evhtp_safe_free(key_buf, free);
     evhtp_safe_free(val_buf, free);
 #endif
     return query_args;
 error:
 #ifndef EVHTP_HAS_C99
     evhtp_safe_free(key_buf, free);
     evhtp_safe_free(val_buf, free);
 #endif
     evhtp_query_free(query_args);
     return NULL;
 }     /* evhtp_parse_query */
evhtp_query_t* evhtp_parse_query (const char * query, size_t len)
Parses the query portion of the uri into a set of key/values in a strict manner.
Parses query arguments like "?herp=derp&foo=bar&blah=baz"
Parameters
query data containing the uri query arguments
len size of the data
Returns
evhtp_query_t * on success, NULL on error
References EVHTP_PARSE_QUERY_FLAG_STRICT, and evhtp_parse_query_wflags().
Referenced by _evhtp_request_parser_fini().
{
     return evhtp_parse_query_wflags(query, len,
                                     EVHTP_PARSE_QUERY_FLAG_STRICT);
 }
void evhtp_send_reply_start (evhtp_request_t * request, evhtp_res code)
References _evhtp_create_reply(), evhtp_connection_free(), and evhtp_request_get_connection().
Referenced by evhtp_send_reply_chunk_start(), and issue161cb().
{
     evhtp_connection_t * c;
     evbuf_t            * reply_buf;
     c = evhtp_request_get_connection(request);
     if (!(reply_buf = _evhtp_create_reply(request, code))) {
         evhtp_connection_free(c);
         return;
     }
     bufferevent_write_buffer(c->bev, reply_buf);
     evbuffer_drain(reply_buf, -1);
     /* evbuffer_free(reply_buf); */
 }
void evhtp_send_reply_body (evhtp_request_t * request, evbuf_t * buf)
Referenced by evhtp_send_reply_chunk(), and issue161cb().
{
     evhtp_connection_t * c;
     c = request->conn;
     bufferevent_write_buffer(c->bev, buf);
 }
void evhtp_send_reply_end (evhtp_request_t * request)
Referenced by evhtp_send_reply_chunk_end(), and issue161cb().
{
     request->finished = 1;
 }
void evhtp_send_reply (evhtp_request_t * request, evhtp_res code)
generates all the right information for a reply to be sent to the client
Parameters
request
code HTTP return status code
References _evhtp_create_reply(), evhtp_connection_free(), evhtp_connection_get_bev(), and evhtp_request_get_connection().
Referenced by _evhtp_default_request_cb(), _req_cb(), backend_cb(), create_callback(), dynamic_cb(), redis_get_srcport_cb(), response_cb(), test_500_cb(), test_bar_cb(), test_default_cb(), test_foo_cb(), test_glob_cb(), test_max_body(), test_pause_cb(), test_regex(), and testcb().
{
     evhtp_connection_t * c;
     evbuf_t            * reply_buf;
     struct bufferevent * bev;
     c = evhtp_request_get_connection(request);
     request->finished = 1;
     if (!(reply_buf = _evhtp_create_reply(request, code))) {
         evhtp_connection_free(request->conn);
         return;
     }
     bev = evhtp_connection_get_bev(c);
     bufferevent_lock(bev);
     {
         bufferevent_write_buffer(bev, reply_buf);
     }
     bufferevent_unlock(bev);
     evbuffer_drain(reply_buf, -1);
     /* evbuffer_free(reply_buf); */
 }
int evhtp_response_needs_body (const evhtp_res code, const htp_method method)
Determine if a response should have a body. Follows the rules in RFC 2616 section 4.3.
Returns
1 if the response MUST have a body; 0 if the response MUST NOT have a body.
References EVHTP_RES_NOCONTENT, EVHTP_RES_NOTMOD, and htp_method_HEAD.
Referenced by evhtp_send_reply_chunk_start().
{
     return code != EVHTP_RES_NOCONTENT &&
            code != EVHTP_RES_NOTMOD &&
            (code < 100 || code >= 200) &&
            method != htp_method_HEAD;
 }
void evhtp_send_reply_chunk_start (evhtp_request_t * request, evhtp_res code)
start a chunked response. If data already exists on the output buffer, this will be converted to the first chunk.
Parameters
request
code
References evhtp_header_new(), evhtp_header_t, evhtp_headers_add_header(), evhtp_headers_find_header, evhtp_kv_rm_and_free(), EVHTP_PROTO_10, EVHTP_PROTO_11, evhtp_response_needs_body(), and evhtp_send_reply_start().
Referenced by test_chunking().
{
     evhtp_header_t * content_len;
     if (evhtp_response_needs_body(code, request->method)) {
         content_len = evhtp_headers_find_header(request->headers_out, "Content-Length");
         switch (request->proto) {
             case EVHTP_PROTO_11:
                 /*
                  * prefer HTTP/1.1 chunked encoding to closing the connection;
                  * note RFC 2616 section 4.4 forbids it with Content-Length:
                  * and it's not necessary then anyway.
                  */
                 evhtp_kv_rm_and_free(request->headers_out, content_len);
                 request->chunked = 1;
                 break;
             case EVHTP_PROTO_10:
                 /*
                  * HTTP/1.0 can be chunked as long as the Content-Length header
                  * is set to 0
                  */
                 evhtp_kv_rm_and_free(request->headers_out, content_len);
 #if 0
                 evhtp_headers_add_header(request->headers_out,
                                          evhtp_header_new("Content-Length", "0", 0, 0));
 #endif
                 request->chunked = 1;
                 break;
             default:
                 request->chunked = 0;
                 break;
         } /* switch */
     } else {
         request->chunked = 0;
     }
     if (request->chunked == 1) {
         evhtp_headers_add_header(request->headers_out,
                                  evhtp_header_new("Transfer-Encoding", "chunked", 0, 0));
         /*
          * if data already exists on the output buffer, we automagically convert
          * it to the first chunk.
          */
         if (evbuffer_get_length(request->buffer_out) > 0) {
             char lstr[128];
             int  sres;
             sres = snprintf(lstr, sizeof(lstr), "%x\r\n",
                             (unsigned)evbuffer_get_length(request->buffer_out));
             if (sres >= sizeof(lstr) || sres < 0) {
                 /* overflow condition, shouldn't ever get here, but lets
                  * terminate the connection asap */
                 goto end;
             }
             evbuffer_prepend(request->buffer_out, lstr, strlen(lstr));
             evbuffer_add(request->buffer_out, "\r\n", 2);
         }
     }
 end:
     evhtp_send_reply_start(request, code);
 } /* evhtp_send_reply_chunk_start */
void evhtp_send_reply_chunk (evhtp_request_t * request, evbuf_t * buf)
send a chunk reply.
Parameters
request
buf
References evhtp_send_reply_body().
Referenced by test_chunking().
{
     evbuf_t * output;
     if (evbuffer_get_length(buf) == 0) {
         return;
     }
     output = bufferevent_get_output(request->conn->bev);
     if (request->chunked == 1) {
         evbuffer_add_printf(output, "%x\r\n",
                             (unsigned)evbuffer_get_length(buf));
     }
     evhtp_send_reply_body(request, buf);
     if (request->chunked) {
         evbuffer_add(output, "\r\n", 2);
     }
     bufferevent_flush(request->conn->bev, EV_WRITE, BEV_FLUSH);
 }
void evhtp_send_reply_chunk_end (evhtp_request_t * request)
call when all chunks have been sent and you wish to send the last bits. This will add the last 0CRLFCRCL and call send_reply_end().
Parameters
request
References evhtp_request_get_bev(), and evhtp_send_reply_end().
Referenced by test_chunking().
{
     if (request->chunked == 1) {
         evbuffer_add(bufferevent_get_output(evhtp_request_get_bev(request)),
                      "0\r\n\r\n", 5);
     }
     evhtp_send_reply_end(request);
 }
void evhtp_unbind_socket (evhtp_t * htp)
stops the listening socket.
Parameters
htp
References evhtp_safe_free.
Referenced by main().
{
     evhtp_safe_free(htp->server, evconnlistener_free);
 }
int evhtp_accept_socket (evhtp_t * htp, evutil_socket_t sock, int backlog)
create the listener plus setup various options with an already-bound socket.
Parameters
htp
sock
backlog
Returns
0 on success, -1 on error (check errno)
References _evhtp_accept_cb(), _evhtp_ssl_servername(), and evhtp_assert.
Referenced by evhtp_bind_sockaddr().
{
     int on = 1;
     evhtp_assert(htp != NULL);
     if (sock == -1) {
         return -1;
     }
 #if defined SO_REUSEPORT
     if (htp->enable_reuseport) {
         setsockopt(sock, SOL_SOCKET, SO_REUSEPORT, (void *)&on, sizeof(on));
     }
 #endif
 #if defined TCP_NODELAY
     if (htp->enable_nodelay == 1) {
         setsockopt(sock, IPPROTO_TCP, TCP_NODELAY, (void *)&on, sizeof(on));
     }
 #endif
 #if defined TCP_DEFER_ACCEPT
     if (htp->enable_defer_accept == 1) {
         setsockopt(sock, IPPROTO_TCP, TCP_DEFER_ACCEPT, (void *)&on, sizeof(on));
     }
 #endif
     htp->server = evconnlistener_new(htp->evbase, _evhtp_accept_cb, htp,
                                      LEV_OPT_CLOSE_ON_FREE | LEV_OPT_REUSEABLE,
                                      backlog, sock);
     if (htp->server == NULL) {
         return -1;
     }
 #ifndef EVHTP_DISABLE_SSL
     if (htp->ssl_ctx != NULL) {
         /* if ssl is enabled and we have virtual hosts, set our servername
          * callback. We do this here because we want to make sure that this gets
          * set after all potential virtualhosts have been set, not just after
          * ssl_init.
          */
         if (TAILQ_FIRST(&htp->vhosts) != NULL) {
             SSL_CTX_set_tlsext_servername_callback(htp->ssl_ctx,
                                                    _evhtp_ssl_servername);
         }
     }
 #endif
     return 0;
 } /* evhtp_accept_socket */
int evhtp_bind_sockaddr (evhtp_t * htp, struct sockaddr * , size_t sin_len, int backlog)
bind to an already allocated sockaddr.
Parameters
htp s
sin_len
backlog
Returns
References evhtp_accept_socket(), and evhtp_errno_assert.
Referenced by evhtp_bind_socket().
{
 #ifndef WIN32
     signal(SIGPIPE, SIG_IGN);
 #endif
     evutil_socket_t fd;
     int             on = 1;
     fd = socket(sa->sa_family, SOCK_STREAM, 0);
     evhtp_errno_assert(fd != -1);
     evutil_make_socket_closeonexec(fd);
     evutil_make_socket_nonblocking(fd);
     setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, (void *)&on, sizeof(on));
     setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (void *)&on, sizeof(on));
     if (sa->sa_family == AF_INET6) {
         int rc;
         rc = setsockopt(fd, IPPROTO_IPV6, IPV6_V6ONLY, &on, sizeof(on));
         evhtp_errno_assert(rc != -1);
     }
     if (bind(fd, sa, sin_len) == -1) {
         return -1;
     }
     return evhtp_accept_socket(htp, fd, backlog);
 } /* evhtp_bind_sockaddr */
int evhtp_bind_socket (evhtp_t * htp, const char * addr, uint16_t port, int backlog)
bind to a socket, optionally with specific protocol support formatting. The addr can be defined as one of the following: ipv6:<ipv6addr> for binding to an IPv6 address. unix:<named pipe>=""> for binding to a unix named socket ipv4:<ipv4addr> for binding to an ipv4 address Otherwise the addr is assumed to be ipv4.
Parameters
htp
addr
port
backlog
Returns
References evhtp_bind_sockaddr().
Referenced by main().
{
 #ifndef NO_SYS_UN
     struct sockaddr_un  sun;
 #endif
     struct sockaddr_in6 sin6;
     struct sockaddr_in  sin;
     struct sockaddr   * sa;
     size_t              sin_len;
     memset(&sin, 0, sizeof(sin));
     if (!strncmp(baddr, "ipv6:", 5)) {
         memset(&sin6, 0, sizeof(sin6));
         baddr           += 5;
         sin_len          = sizeof(struct sockaddr_in6);
         sin6.sin6_port   = htons(port);
         sin6.sin6_family = AF_INET6;
         evutil_inet_pton(AF_INET6, baddr, &sin6.sin6_addr);
         sa = (struct sockaddr *)&sin6;
     } else if (!strncmp(baddr, "unix:", 5)) {
 #ifndef NO_SYS_UN
         baddr += 5;
         if (strlen(baddr) >= sizeof(sun.sun_path)) {
             return -1;
         }
         memset(&sun, 0, sizeof(sun));
         sin_len        = sizeof(struct sockaddr_un);
         sun.sun_family = AF_UNIX;
         strncpy(sun.sun_path, baddr, strlen(baddr));
         sa = (struct sockaddr *)&sun;
 #else
         return -1;
 #endif
     } else {
         if (!strncmp(baddr, "ipv4:", 5)) {
             baddr += 5;
         }
         sin_len             = sizeof(struct sockaddr_in);
         sin.sin_family      = AF_INET;
         sin.sin_port        = htons(port);
         sin.sin_addr.s_addr = inet_addr(baddr);
         sa = (struct sockaddr *)&sin;
     }
     return evhtp_bind_sockaddr(htp, sa, sin_len, backlog);
 } /* evhtp_bind_socket */
void evhtp_callbacks_free (evhtp_callbacks_t * callbacks)
References evhtp_callback_free(), evhtp_safe_free, and TAILQ_FOREACH_SAFE.
Referenced by evhtp_free().
{
     evhtp_callback_t * callback;
     evhtp_callback_t * tmp;
     if (callbacks == NULL) {
         return;
     }
     TAILQ_FOREACH_SAFE(callback, callbacks, next, tmp) {
         TAILQ_REMOVE(callbacks, callback, next);
         evhtp_safe_free(callback, evhtp_callback_free);
     }
     evhtp_safe_free(callbacks, free);
 }
evhtp_callback_t* evhtp_callback_new (const char * path, evhtp_callback_type type, evhtp_callback_cb cb, void * arg)
creates a new evhtp_callback_t structure.
All callbacks are stored in this structure which define what the final function to be called after all parsing is done. A callback can be either a static string or a regular expression.
Parameters
path can either be a static path (/path/to/resource/) or a POSIX compatible regular expression (^/resource/(.*))
type informs the function what type of of information is is contained within the path argument. This can either be callback_type_path, or callback_type_regex.
cb the callback function to be invoked
arg optional argument which is passed when the callback is executed.
Returns
0 on success, -1 on error.
References _evhtp_quick_hash(), cb, evhtp_alloc_assert, evhtp_callback_type_glob, evhtp_callback_type_hash, evhtp_callback_type_regex, and evhtp_safe_free.
Referenced by evhtp_set_cb(), evhtp_set_glob_cb(), and evhtp_set_regex_cb().
{
     evhtp_callback_t * hcb;
     hcb        = calloc(sizeof(evhtp_callback_t), 1);
     evhtp_alloc_assert(hcb);
     hcb->type  = type;
     hcb->cb    = cb;
     hcb->cbarg = arg;
     switch (type) {
         case evhtp_callback_type_hash:
             hcb->hash      = _evhtp_quick_hash(path);
             hcb->val.path  = strdup(path);
             break;
 #ifndef EVHTP_DISABLE_REGEX
         case evhtp_callback_type_regex:
             hcb->val.regex = malloc(sizeof(regex_t));
             if (regcomp(hcb->val.regex, (char *)path, REG_EXTENDED) != 0) {
                 evhtp_safe_free(hcb->val.regex, free);
                 evhtp_safe_free(hcb, free);
                 return NULL;
             }
             break;
 #endif
         case evhtp_callback_type_glob:
             hcb->val.glob = strdup(path);
             break;
         default:
             evhtp_safe_free(hcb, free);
             return NULL;
     } /* switch */
     return hcb;
 }
void evhtp_callback_free (evhtp_callback_t * callback)
frees information associated with a ainflwx callback.
Parameters
callback
References evhtp_callback_type_glob, evhtp_callback_type_hash, evhtp_callback_type_regex, and evhtp_safe_free.
Referenced by evhtp_callbacks_free(), evhtp_set_cb(), evhtp_set_glob_cb(), and evhtp_set_regex_cb().
{
     if (callback == NULL) {
         return;
     }
     switch (callback->type) {
         case evhtp_callback_type_hash:
             evhtp_safe_free(callback->val.path, free);
             break;
         case evhtp_callback_type_glob:
             evhtp_safe_free(callback->val.glob, free);
             break;
 #ifndef EVHTP_DISABLE_REGEX
         case evhtp_callback_type_regex:
             regfree(callback->val.regex);
             evhtp_safe_free(callback->val.regex, free);
             break;
 #endif
     }
     if (callback->hooks) {
         evhtp_safe_free(callback->hooks, free);
     }
     evhtp_safe_free(callback, free);
     return;
 }
int evhtp_callbacks_add_callback (evhtp_callbacks_t * cbs, evhtp_callback_t * cb)
Adds a evhtp_callback_t to the evhtp_callbacks_t list.
Parameters
cbs an allocated evhtp_callbacks_t structure
cb an initialized evhtp_callback_t structure
Returns
0 on success, -1 on error
Referenced by evhtp_set_cb(), evhtp_set_glob_cb(), and evhtp_set_regex_cb().
{
     TAILQ_INSERT_TAIL(cbs, cb, next);
     return 0;
 }
int evhtp_set_hook (evhtp_hooks_t ** hooks, evhtp_hook_type type, evhtp_hook cb, void * arg)
sets a callback hook for either a connection or a path/regex .
A user may set a variety of hooks either per-connection, or per-callback. This allows the developer to hook into various parts of the request processing cycle.
a per-connection hook can be set at any time, but it is recommended to set these during either a pre-accept phase, or post-accept phase. This allows a developer to set hooks before any other hooks are called.
a per-callback hook works differently. In this mode a developer can setup a set of hooks prior to starting the event loop for specific callbacks. For example if you wanted to hook something ONLY for a callback set by evhtp_set_cb or evhtp_set_regex_cb this is the method of doing so.
per-callback example:
evhtp_callback_t * cb = evhtp_set_regex_cb(htp, "/anything/(.*)", default_cb, NULL);
evhtp_set_hook(&cb->hooks, evhtp_hook_on_headers, anything_headers_cb, NULL);
evhtp_set_hook(&cb->hooks, evhtp_hook_on_fini, anything_fini_cb, NULL);
With the above example, once libevhtp has determined that it has a user-defined callback for /anything/.*; anything_headers_cb will be executed after all headers have been parsed, and anything_fini_cb will be executed before the request is free()'d.
The same logic applies to per-connection hooks, but it should be noted that if a per-callback hook is set, the per-connection hook will be ignored.
Parameters
hooks double pointer to the evhtp_hooks_t structure
type the hook type
cb the callback to be executed.
arg optional argument which is passed when the callback is executed
Returns
0 on success, -1 on error (if hooks is NULL, it is allocated)
References evhtp_hook_on_chunk_complete, evhtp_hook_on_chunks_complete, evhtp_hook_on_conn_error, evhtp_hook_on_connection_fini, evhtp_hook_on_error, evhtp_hook_on_event, evhtp_hook_on_header, evhtp_hook_on_headers, evhtp_hook_on_headers_start, evhtp_hook_on_hostname, evhtp_hook_on_new_chunk, evhtp_hook_on_path, evhtp_hook_on_read, evhtp_hook_on_request_fini, and evhtp_hook_on_write.
Referenced by evhtp_unset_hook(), main(), pause_init_cb(), and set_my_connection_handlers().
{
     if (*hooks == NULL) {
         if (!(*hooks = calloc(sizeof(evhtp_hooks_t), 1))) {
             return -1;
         }
     }
     switch (type) {
         case evhtp_hook_on_headers_start:
             (*hooks)->on_headers_start        = (evhtp_hook_headers_start_cb)cb;
             (*hooks)->on_headers_start_arg    = arg;
             break;
         case evhtp_hook_on_header:
             (*hooks)->on_header = (evhtp_hook_header_cb)cb;
             (*hooks)->on_header_arg           = arg;
             break;
         case evhtp_hook_on_headers:
             (*hooks)->on_headers              = (evhtp_hook_headers_cb)cb;
             (*hooks)->on_headers_arg          = arg;
             break;
         case evhtp_hook_on_path:
             (*hooks)->on_path = (evhtp_hook_path_cb)cb;
             (*hooks)->on_path_arg             = arg;
             break;
         case evhtp_hook_on_read:
             (*hooks)->on_read = (evhtp_hook_read_cb)cb;
             (*hooks)->on_read_arg             = arg;
             break;
         case evhtp_hook_on_request_fini:
             (*hooks)->on_request_fini         = (evhtp_hook_request_fini_cb)cb;
             (*hooks)->on_request_fini_arg     = arg;
             break;
         case evhtp_hook_on_connection_fini:
             (*hooks)->on_connection_fini      = (evhtp_hook_connection_fini_cb)cb;
             (*hooks)->on_connection_fini_arg  = arg;
             break;
         case evhtp_hook_on_conn_error:
             (*hooks)->on_connection_error     = (evhtp_hook_conn_err_cb)cb;
             (*hooks)->on_connection_error_arg = arg;
             break;
         case evhtp_hook_on_error:
             (*hooks)->on_error = (evhtp_hook_err_cb)cb;
             (*hooks)->on_error_arg            = arg;
             break;
         case evhtp_hook_on_new_chunk:
             (*hooks)->on_new_chunk            = (evhtp_hook_chunk_new_cb)cb;
             (*hooks)->on_new_chunk_arg        = arg;
             break;
         case evhtp_hook_on_chunk_complete:
             (*hooks)->on_chunk_fini           = (evhtp_hook_chunk_fini_cb)cb;
             (*hooks)->on_chunk_fini_arg       = arg;
             break;
         case evhtp_hook_on_chunks_complete:
             (*hooks)->on_chunks_fini          = (evhtp_hook_chunks_fini_cb)cb;
             (*hooks)->on_chunks_fini_arg      = arg;
             break;
         case evhtp_hook_on_hostname:
             (*hooks)->on_hostname             = (evhtp_hook_hostname_cb)cb;
             (*hooks)->on_hostname_arg         = arg;
             break;
         case evhtp_hook_on_write:
             (*hooks)->on_write = (evhtp_hook_write_cb)cb;
             (*hooks)->on_write_arg            = arg;
             break;
         case evhtp_hook_on_event:
             (*hooks)->on_event = (evhtp_hook_event_cb)cb;
             (*hooks)->on_event_arg            = arg;
             break;
         default:
             return -1;
     }     /* switch */
     return 0;
 }         /* evhtp_set_hook */
int evhtp_unset_hook (evhtp_hooks_t ** hooks, evhtp_hook_type type)
remove a specific hook from being called.
Parameters
hooks
type
Returns
References evhtp_set_hook().
Referenced by evhtp_unset_all_hooks().
{
     return evhtp_set_hook(hooks, type, NULL, NULL);
 }
int evhtp_unset_all_hooks (evhtp_hooks_t ** hooks)
removes all hooks.
Parameters
hooks
Returns
References evhtp_hook_on_chunk_complete, evhtp_hook_on_chunks_complete, evhtp_hook_on_conn_error, evhtp_hook_on_connection_fini, evhtp_hook_on_error, evhtp_hook_on_event, evhtp_hook_on_header, evhtp_hook_on_headers, evhtp_hook_on_headers_start, evhtp_hook_on_hostname, evhtp_hook_on_new_chunk, evhtp_hook_on_path, evhtp_hook_on_read, evhtp_hook_on_request_fini, evhtp_hook_on_write, and evhtp_unset_hook().
Referenced by evhtp_connection_take_ownership().
{
     int res = 0;
     if (evhtp_unset_hook(hooks, evhtp_hook_on_headers_start)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_header)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_headers)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_path)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_read)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_request_fini)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_connection_fini)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_conn_error)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_error)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_new_chunk)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_chunk_complete)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_chunks_complete)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_hostname)) {
         res -= 1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_write)) {
         return -1;
     }
     if (evhtp_unset_hook(hooks, evhtp_hook_on_event)) {
         return -1;
     }
     return res;
 } /* evhtp_unset_all_hooks */
evhtp_callback_t* evhtp_set_cb (evhtp_t * htp, const char * path, evhtp_callback_cb cb, void * arg)
sets a callback to be executed on a specific path
Parameters
htp the initialized evhtp_t
path the path to match
cb the function to be executed
arg user-defined argument passed to the callback
Returns
evhtp_callback_t * on success, NULL on error.
References _evhtp_lock, _evhtp_unlock, evhtp_callback_free(), evhtp_callback_new(), evhtp_callback_type_hash, evhtp_callbacks_add_callback(), and evhtp_safe_free.
Referenced by create_callback(), and main().
{
     evhtp_callback_t * hcb;
     _evhtp_lock(htp);
     if (htp->callbacks == NULL) {
         if (!(htp->callbacks = calloc(sizeof(evhtp_callbacks_t), 1))) {
             _evhtp_unlock(htp);
             return NULL;
         }
         TAILQ_INIT(htp->callbacks);
     }
     if (!(hcb = evhtp_callback_new(path, evhtp_callback_type_hash, cb, arg))) {
         _evhtp_unlock(htp);
         return NULL;
     }
     if (evhtp_callbacks_add_callback(htp->callbacks, hcb)) {
         evhtp_safe_free(hcb, evhtp_callback_free);
         _evhtp_unlock(htp);
         return NULL;
     }
     _evhtp_unlock(htp);
     return hcb;
 }
evhtp_callback_t* evhtp_get_cb (evhtp_t * htp, const char * needle)
attempts to find the callback matching the exact string 'needle'. This is useful in cases where we want to get the original handle, but is not in scope.
with pattern based callbacks, this does not attempt to find a callback that would match the string if the pattern matcher was executed.
Meaning: evhtp_set_glob_cb(htp, "/foo/bar*", ....);
Calling evhtp_get_cb(htp, "/foo/bar/baz");
Will return NULL since it's not the exact pattern set
Calling evhtp_get_cb(htp, "/foo/bar*");
Is the correct usage.
Parameters
htp
needle
Returns
NULL if callback is not not found
{
     evhtp_callback_t * callback;
     TAILQ_FOREACH(callback, htp->callbacks, next) {
         if (strcmp(callback->val.path, path) == 0) {
             return callback;
         }
     }
     return NULL;
 }
static void _evhtp_thread_init (evthr_t * thr, void * arg) static
Referenced by _evhtp_use_threads().
{
     evhtp_t * htp = (evhtp_t *)arg;
     if (htp->thread_init_cb) {
         htp->thread_init_cb(htp, thr, htp->thread_cbarg);
     }
 }
static void _evhtp_thread_exit (evthr_t * thr, void * arg) static
Referenced by _evhtp_use_threads().
{
     evhtp_t * htp = (evhtp_t *)arg;
     if (htp->thread_exit_cb) {
         htp->thread_exit_cb(htp, thr, htp->thread_cbarg);
     }
 }
static int _evhtp_use_threads (evhtp_t * htp, evhtp_thread_init_cb init_cb, evhtp_thread_exit_cb exit_cb, int nthreads, void * arg) static
References _evhtp_thread_exit(), _evhtp_thread_init(), evhtp_ssl_use_threads(), evthr_pool_start(), and evthr_pool_wexit_new().
Referenced by evhtp_use_threads(), and evhtp_use_threads_wexit().
{
     if (htp == NULL) {
         return -1;
     }
     htp->thread_cbarg   = arg;
     htp->thread_init_cb = init_cb;
     htp->thread_exit_cb = exit_cb;
 #ifndef EVHTP_DISABLE_SSL
     evhtp_ssl_use_threads();
 #endif
     if (!(htp->thr_pool = evthr_pool_wexit_new(nthreads,
                                                _evhtp_thread_init,
                                                _evhtp_thread_exit, htp))) {
         return -1;
     }
     evthr_pool_start(htp->thr_pool);
     return 0;
 }
int evhtp_use_threads (evhtp_t * , evhtp_thread_init_cb , int nthreads, void *)
Enable thread-pool support for an evhtp_t context. Connectios are distributed across 'nthreads'. An optional "on-start" callback can be set which allows you to manipulate the thread-specific inforation (such as the thread-specific event_base).
Parameters
htp
init_cb
exit_cb
nthreads
arg
Returns
References _evhtp_use_threads().
Referenced by main().
{
     return _evhtp_use_threads(htp, init_cb, NULL, nthreads, arg);
 }
int evhtp_use_threads_wexit (evhtp_t * htp, evhtp_thread_init_cb init_cb, evhtp_thread_exit_cb exit_cb, int nthreads, void * arg)
Temporary function which will be renamed evhtp_use_threads in the future. evhtp_use_threads() has been noted as deprecated for now.
References _evhtp_use_threads().
{
     return _evhtp_use_threads(htp, init_cb, exit_cb, nthreads, arg);
 }
int evhtp_use_callback_locks (evhtp_t * htp)
creates a lock around callbacks and hooks, allowing for threaded applications to add/remove/modify hooks & callbacks in a thread-safe manner.
Parameters
htp
Returns
0 on success, -1 on error
{
     if (htp == NULL) {
         return -1;
     }
     if (!(htp->lock = malloc(sizeof(pthread_mutex_t)))) {
         return -1;
     }
     return pthread_mutex_init(htp->lock, NULL);
 }
evhtp_callback_t* evhtp_set_regex_cb (evhtp_t * htp, const char * pattern, evhtp_callback_cb cb, void * arg)
sets a callback to be executed based on a regex pattern
Parameters
htp the initialized evhtp_t
pattern a POSIX compat regular expression
cb the function to be executed
arg user-defined argument passed to the callback
Returns
evhtp_callback_t * on success, NULL on error
References _evhtp_lock, _evhtp_unlock, evhtp_callback_free(), evhtp_callback_new(), evhtp_callback_type_regex, evhtp_callbacks_add_callback(), and evhtp_safe_free.
Referenced by main().
{
     evhtp_callback_t * hcb;
     _evhtp_lock(htp);
     if (htp->callbacks == NULL) {
         if (!(htp->callbacks = calloc(sizeof(evhtp_callbacks_t), 1))) {
             _evhtp_unlock(htp);
             return NULL;
         }
         TAILQ_INIT(htp->callbacks);
     }
     if (!(hcb = evhtp_callback_new(pattern, evhtp_callback_type_regex, cb, arg))) {
         _evhtp_unlock(htp);
         return NULL;
     }
     if (evhtp_callbacks_add_callback(htp->callbacks, hcb)) {
         evhtp_safe_free(hcb, evhtp_callback_free);
         _evhtp_unlock(htp);
         return NULL;
     }
     _evhtp_unlock(htp);
     return hcb;
 }
evhtp_callback_t* evhtp_set_glob_cb (evhtp_t * htp, const char * pattern, evhtp_callback_cb cb, void * arg)
sets a callback to to be executed on simple glob/wildcard patterns this is useful if the app does not care about what was matched, but just that it matched. This is technically faster than regex.
Parameters
htp
pattern wildcard pattern, the '*' can be set at either or both the front or end.
cb
arg
Returns
References _evhtp_lock, _evhtp_unlock, evhtp_callback_free(), evhtp_callback_new(), evhtp_callback_type_glob, evhtp_callbacks_add_callback(), and evhtp_safe_free.
Referenced by main().
{
     evhtp_callback_t * hcb;
     _evhtp_lock(htp);
     if (htp->callbacks == NULL) {
         if (!(htp->callbacks = calloc(sizeof(evhtp_callbacks_t), 1))) {
             _evhtp_unlock(htp);
             return NULL;
         }
         TAILQ_INIT(htp->callbacks);
     }
     if (!(hcb = evhtp_callback_new(pattern, evhtp_callback_type_glob, cb, arg))) {
         _evhtp_unlock(htp);
         return NULL;
     }
     if (evhtp_callbacks_add_callback(htp->callbacks, hcb)) {
         evhtp_safe_free(hcb, evhtp_callback_free);
         _evhtp_unlock(htp);
         return NULL;
     }
     _evhtp_unlock(htp);
     return hcb;
 }
void evhtp_set_gencb (evhtp_t * htp, evhtp_callback_cb cb, void * arg)
sets a callback which is called if no other callbacks are matched
Parameters
htp the initialized evhtp_t
cb the function to be executed
arg user-defined argument passed to the callback
References cb.
Referenced by evhtp_new(), and main().
{
     htp->defaults.cb    = cb;
     htp->defaults.cbarg = arg;
 }
void evhtp_set_pre_accept_cb (evhtp_t * htp, evhtp_pre_accept_cb , void * arg)
call a user-defined function before the connection is accepted.
Parameters
htp
evhtp_pre_accept_cb
arg
Returns
References cb.
Referenced by main().
{
     htp->defaults.pre_accept       = cb;
     htp->defaults.pre_accept_cbarg = arg;
 }
void evhtp_set_post_accept_cb (evhtp_t * htp, evhtp_post_accept_cb , void * arg)
call a user-defined function right after a connection is accepted.
Parameters
htp
evhtp_post_accept_cb
arg
Returns
References cb.
Referenced by main().
{
     htp->defaults.post_accept       = cb;
     htp->defaults.post_accept_cbarg = arg;
 }
int evhtp_ssl_use_threads (void)
References _evhtp_ssl_get_thread_id(), _evhtp_ssl_thread_lock(), ssl_locks, ssl_locks_initialized, and ssl_num_locks.
Referenced by _evhtp_use_threads().
{
     int i;
     if (ssl_locks_initialized == 1) {
         return 0;
     }
     ssl_locks_initialized = 1;
     ssl_num_locks         = CRYPTO_num_locks();
     ssl_locks = malloc(ssl_num_locks * sizeof(evhtp_mutex_t));
     for (i = 0; i < ssl_num_locks; i++) {
         pthread_mutex_init(&(ssl_locks[i]), NULL);
     }
     CRYPTO_set_id_callback(_evhtp_ssl_get_thread_id);
     CRYPTO_set_locking_callback(_evhtp_ssl_thread_lock);
     return 0;
 }
int evhtp_ssl_init (evhtp_t * htp, evhtp_ssl_cfg_t * cfg)
References _evhtp_ssl_add_scache_ent(), _evhtp_ssl_delete_scache_ent(), _evhtp_ssl_get_scache_ent(), evhtp_alloc_assert, evhtp_ssl_scache_type_builtin, evhtp_ssl_scache_type_disabled, evhtp_ssl_scache_type_internal, evhtp_ssl_scache_type_user, and session_id_context.
Referenced by main().
{
 #ifdef EVHTP_ENABLE_FUTURE_STUFF
     evhtp_ssl_scache_init init_cb = NULL;
     evhtp_ssl_scache_add  add_cb  = NULL;
     evhtp_ssl_scache_get  get_cb  = NULL;
     evhtp_ssl_scache_del  del_cb  = NULL;
 #endif
     long                  cache_mode;
     if (cfg == NULL || htp == NULL || cfg->pemfile == NULL) {
         return -1;
     }
     SSL_library_init();
     SSL_load_error_strings();
     RAND_poll();
 #if OPENSSL_VERSION_NUMBER < 0x10000000L
     STACK_OF(SSL_COMP) * comp_methods = SSL_COMP_get_compression_methods();
     sk_SSL_COMP_zero(comp_methods);
 #endif
     htp->ssl_cfg = cfg;
     htp->ssl_ctx = SSL_CTX_new(SSLv23_server_method());
     evhtp_alloc_assert(htp->ssl_ctx);
 #if OPENSSL_VERSION_NUMBER >= 0x10000000L
     SSL_CTX_set_options(htp->ssl_ctx, SSL_MODE_RELEASE_BUFFERS | SSL_OP_NO_COMPRESSION);
     SSL_CTX_set_timeout(htp->ssl_ctx, cfg->ssl_ctx_timeout);
 #endif
     SSL_CTX_set_options(htp->ssl_ctx, cfg->ssl_opts);
 #ifndef OPENSSL_NO_ECDH
     if (cfg->named_curve != NULL) {
         EC_KEY * ecdh = NULL;
         int      nid  = 0;
         nid  = OBJ_sn2nid(cfg->named_curve);
         if (nid == 0) {
             fprintf(stderr, "ECDH initialization failed: unknown curve %s\n", cfg->named_curve);
         }
         ecdh = EC_KEY_new_by_curve_name(nid);
         if (ecdh == NULL) {
             fprintf(stderr, "ECDH initialization failed for curve %s\n", cfg->named_curve);
         }
         SSL_CTX_set_tmp_ecdh(htp->ssl_ctx, ecdh);
         EC_KEY_free(ecdh);
     }
 #endif /* OPENSSL_NO_ECDH */
 #ifndef OPENSSL_NO_DH
     if (cfg->dhparams != NULL) {
         FILE * fh;
         DH   * dh;
         fh = fopen(cfg->dhparams, "r");
         if (fh != NULL) {
             dh = PEM_read_DHparams(fh, NULL, NULL, NULL);
             if (dh != NULL) {
                 SSL_CTX_set_tmp_dh(htp->ssl_ctx, dh);
                 DH_free(dh);
             } else {
                 fprintf(stderr, "DH initialization failed: unable to parse file %s\n", cfg->dhparams);
             }
             fclose(fh);
         } else {
             fprintf(stderr, "DH initialization failed: unable to open file %s\n", cfg->dhparams);
         }
     }
 #endif /* OPENSSL_NO_DH */
     if (cfg->ciphers != NULL) {
         SSL_CTX_set_cipher_list(htp->ssl_ctx, cfg->ciphers);
     }
     SSL_CTX_load_verify_locations(htp->ssl_ctx, cfg->cafile, cfg->capath);
     X509_STORE_set_flags(SSL_CTX_get_cert_store(htp->ssl_ctx), cfg->store_flags);
     SSL_CTX_set_verify(htp->ssl_ctx, cfg->verify_peer, cfg->x509_verify_cb);
     if (cfg->x509_chk_issued_cb != NULL) {
         htp->ssl_ctx->cert_store->check_issued = cfg->x509_chk_issued_cb;
     }
     if (cfg->verify_depth) {
         SSL_CTX_set_verify_depth(htp->ssl_ctx, cfg->verify_depth);
     }
     switch (cfg->scache_type) {
         case evhtp_ssl_scache_type_disabled:
             cache_mode = SSL_SESS_CACHE_OFF;
             break;
 #ifdef EVHTP_ENABLE_FUTURE_STUFF
         case evhtp_ssl_scache_type_user:
             cache_mode = SSL_SESS_CACHE_SERVER |
                          SSL_SESS_CACHE_NO_INTERNAL |
                          SSL_SESS_CACHE_NO_INTERNAL_LOOKUP;
             init_cb    = cfg->scache_init;
             add_cb     = cfg->scache_add;
             get_cb     = cfg->scache_get;
             del_cb     = cfg->scache_del;
             break;
         case evhtp_ssl_scache_type_builtin:
             cache_mode = SSL_SESS_CACHE_SERVER |
                          SSL_SESS_CACHE_NO_INTERNAL |
                          SSL_SESS_CACHE_NO_INTERNAL_LOOKUP;
             init_cb    = _evhtp_ssl_builtin_init;
             add_cb     = _evhtp_ssl_builtin_add;
             get_cb     = _evhtp_ssl_builtin_get;
             del_cb     = _evhtp_ssl_builtin_del;
             break;
 #endif
         case evhtp_ssl_scache_type_internal:
         default:
             cache_mode = SSL_SESS_CACHE_SERVER;
             break;
     }     /* switch */
     SSL_CTX_use_certificate_file(htp->ssl_ctx, cfg->pemfile, SSL_FILETYPE_PEM);
     SSL_CTX_use_PrivateKey_file(htp->ssl_ctx,
                                 cfg->privfile ? cfg->privfile : cfg->pemfile, SSL_FILETYPE_PEM);
     SSL_CTX_set_session_id_context(htp->ssl_ctx,
                                    (void *)&session_id_context,
                                    sizeof(session_id_context));
     SSL_CTX_set_app_data(htp->ssl_ctx, htp);
     SSL_CTX_set_session_cache_mode(htp->ssl_ctx, cache_mode);
     if (cache_mode != SSL_SESS_CACHE_OFF) {
         SSL_CTX_sess_set_cache_size(htp->ssl_ctx,
                                     cfg->scache_size ? cfg->scache_size : 1024);
         if (cfg->scache_type == evhtp_ssl_scache_type_builtin ||
             cfg->scache_type == evhtp_ssl_scache_type_user) {
             SSL_CTX_sess_set_new_cb(htp->ssl_ctx, _evhtp_ssl_add_scache_ent);
             SSL_CTX_sess_set_get_cb(htp->ssl_ctx, _evhtp_ssl_get_scache_ent);
             SSL_CTX_sess_set_remove_cb(htp->ssl_ctx, _evhtp_ssl_delete_scache_ent);
             if (cfg->scache_init) {
                 cfg->args = (cfg->scache_init)(htp);
             }
         }
     }
     return 0;
 }     /* evhtp_use_ssl */
evbev_t* evhtp_connection_get_bev (evhtp_connection_t * conn)
returns the underlying connections bufferevent
Parameters
conn
Returns
bufferevent on success, otherwise NULL
Referenced by evhtp_connection_take_ownership(), evhtp_request_get_bev(), and evhtp_send_reply().
{
     return connection->bev;
 }
evbev_t* evhtp_connection_take_ownership (evhtp_connection_t * connection)
let a user take ownership of the underlying bufferevent and free all other underlying resources.
Warning: this will free all evhtp_connection/request structures, remove all associated hooks and reset the bufferevent to defaults, i.e., disable EV_READ, and set all callbacks to NULL.
Parameters
connection
Returns
underlying connections bufferevent.
References evhtp_connection_get_bev(), evhtp_connection_set_bev(), and evhtp_unset_all_hooks().
Referenced by evhtp_request_take_ownership(), and test_ownership().
{
     evbev_t * bev = evhtp_connection_get_bev(connection);
     if (connection->hooks) {
         evhtp_unset_all_hooks(&connection->hooks);
     }
     if (connection->request && connection->request->hooks) {
         evhtp_unset_all_hooks(&connection->request->hooks);
     }
     evhtp_connection_set_bev(connection, NULL);
     connection->owner = 0;
     bufferevent_disable(bev, EV_READ);
     bufferevent_setcb(bev, NULL, NULL, NULL, NULL);
     return bev;
 }
evbev_t* evhtp_request_get_bev (evhtp_request_t * request)
returns the underlying requests bufferevent
Parameters
request
Returns
bufferevent on success, otherwise NULL
References evhtp_connection_get_bev().
Referenced by evhtp_send_reply_chunk_end().
{
     return evhtp_connection_get_bev(request->conn);
 }
evbev_t* evhtp_request_take_ownership (evhtp_request_t * request)
References evhtp_connection_take_ownership(), and evhtp_request_get_connection().
{
     return evhtp_connection_take_ownership(evhtp_request_get_connection(request));
 }
void evhtp_connection_set_bev (evhtp_connection_t * conn, evbev_t * bev)
Sets the connections underlying bufferevent.
Parameters
conn
bev
Referenced by evhtp_connection_take_ownership(), and evhtp_request_set_bev().
{
     conn->bev = bev;
 }
void evhtp_request_set_bev (evhtp_request_t * request, evbev_t * bev)
sets the underlying bufferevent for a evhtp_request
Parameters
request
bev
References evhtp_connection_set_bev().
{
     evhtp_connection_set_bev(request->conn, bev);
 }
void evhtp_request_set_keepalive (evhtp_request_t * request, int val)
Referenced by issue161cb().
{
     request->keepalive = (val > 0) ? 1 : 0;
 }
evhtp_connection_t* evhtp_request_get_connection (evhtp_request_t * request)
returns the underlying evhtp_connection_t structure from a request
Parameters
request
Returns
evhtp_connection_t on success, otherwise NULL
Referenced by app_process_request(), evhtp_request_take_ownership(), evhtp_send_reply(), evhtp_send_reply_start(), get_request_thr(), and test_ownership().
{
     return request->conn;
 }
evhtp_proto evhtp_request_get_proto (evhtp_request_t * request)
Referenced by issue161cb().
{
     return request->proto;
 }
void evhtp_connection_set_timeouts (evhtp_connection_t * conn, const struct timeval * r, const struct timeval * w) inline
sets a connection-specific read/write timeout which overrides the global read/write settings.
Parameters
conn
r timeval for read
w timeval for write
References evhtp_unlikely.
Referenced by _evhtp_connection_accept().
{
     if (evhtp_unlikely(c == NULL)) {
         return;
     }
     bufferevent_set_timeouts(c->bev, rtimeo, wtimeo);
 }
void evhtp_connection_set_max_body_size (evhtp_connection_t * conn, uint64_t len)
set a max body size for a specific connection, this will default to the size set by evhtp_set_max_body_size
Parameters
conn
len
Referenced by evhtp_request_set_max_body_size().
{
     if (len == 0) {
         c->max_body_size = c->htp->max_body_size;
     } else {
         c->max_body_size = len;
     }
 }
void evhtp_request_set_max_body_size (evhtp_request_t * request, uint64_t len)
just calls evhtp_connection_set_max_body_size for the request.
Parameters
request
len
References evhtp_connection_set_max_body_size().
Referenced by set_max_body().
{
     evhtp_connection_set_max_body_size(req->conn, len);
 }
void evhtp_connection_free (evhtp_connection_t * connection)
free's all connection related resources, this will also call your request fini hook and request fini hook.
Parameters
connection
References _evhtp_connection_fini_hook(), _evhtp_request_free(), evhtp_safe_free, and evhtp_unlikely.
Referenced by _evhtp_accept_cb(), _evhtp_connection_eventcb(), _evhtp_connection_readcb(), _evhtp_connection_resumecb(), _evhtp_connection_writecb(), _evhtp_run_in_thread(), evhtp_connection_new_dns(), evhtp_send_reply(), and evhtp_send_reply_start().
{
     if (evhtp_unlikely(connection == NULL)) {
         return;
     }
     _evhtp_connection_fini_hook(connection);
     evhtp_safe_free(connection->request, _evhtp_request_free);
     evhtp_safe_free(connection->parser, free);
     evhtp_safe_free(connection->hooks, free);
     evhtp_safe_free(connection->saddr, free);
     evhtp_safe_free(connection->scratch_buf, evbuffer_free);
     if (connection->resume_ev) {
         evhtp_safe_free(connection->resume_ev, event_free);
     }
     if (connection->bev) {
 #ifdef LIBEVENT_HAS_SHUTDOWN
         bufferevent_shutdown(connection->bev, _evhtp_shutdown_eventcb);
 #else
 #ifndef EVHTP_DISABLE_SSL
         if (connection->ssl != NULL) {
             SSL_set_shutdown(connection->ssl, SSL_RECEIVED_SHUTDOWN);
             SSL_shutdown(connection->ssl);
         }
 #endif
         bufferevent_free(connection->bev);
 #endif
     }
     evhtp_safe_free(connection, free);
 }     /* evhtp_connection_free */
void evhtp_request_free (evhtp_request_t * request)
References _evhtp_request_free().
{
     _evhtp_request_free(request);
 }
void evhtp_set_timeouts (evhtp_t * htp, const struct timeval * r, const struct timeval * w)
set a read/write timeout on all things evhtp_t. When the timeout expires your error hook will be called with the libevent supplied event flags.
Parameters
htp the base evhtp_t struct
r read-timeout in timeval
w write-timeout in timeval.
{
     if (r_timeo != NULL) {
         htp->recv_timeo = *r_timeo;
     }
     if (w_timeo != NULL) {
         htp->send_timeo = *w_timeo;
     }
 }
void evhtp_set_max_keepalive_requests (evhtp_t * htp, uint64_t num)
sets a maximum number of requests that a single connection can make.
Parameters
htp
num
Referenced by main().
{
     htp->max_keepalive_requests = num;
 }
void evhtp_set_bev_flags (evhtp_t * htp, int flags)
set bufferevent flags, defaults to BEV_OPT_CLOSE_ON_FREE
bufferevent flags which will be used for bev sockets.
Parameters
htp
flags
{
     htp->bev_flags = flags;
 }
void evhtp_set_max_body_size (evhtp_t * htp, uint64_t len)
set a max body size to accept for an incoming request, this will default to unlimited.
Parameters
htp
len
{
     htp->max_body_size = len;
 }
void evhtp_disable_100_continue (evhtp_t * htp)
when a client sends an Expect: 100-continue, if this is function is called, evhtp will not send a HTTP/x.x continue response.
Parameters
htp
{
     htp->disable_100_cont = 1;
 }
void evhtp_set_parser_flags (evhtp_t * htp, int flags)
during the request processing cycle, these flags will be used to for query argument parsing. i.e., what to parse and not to parse.
SEE: EVHTP_PARSE_QUERY_* stuff.
For example, if you do not wish for the streaming parser attempting the act of fragment parsing: evhtp_set_parser_flags(htp, EVHTP_PARSE_QUERY_FLAG_IGNORE_FRAGMENTS);
Parameters
htp
flags
Referenced by main().
{
     htp->parser_flags = flags;
 }
int evhtp_add_alias (evhtp_t * evhtp, const char * name)
Add an alias hostname for a virtual-host specific evhtp_t. This avoids having multiple evhtp_t virtual hosts with the same callback for the same vhost.
Parameters
evhtp
name
Returns
References evhtp_alloc_assert, and evhtp_unlikely.
Referenced by main().
{
     evhtp_alias_t * alias;
     if (evhtp_unlikely(evhtp == NULL || name == NULL)) {
         return -1;
     }
     if (!(alias = calloc(sizeof(evhtp_alias_t), 1))) {
         return -1;
     }
     alias->alias = strdup(name);
     evhtp_alloc_assert(alias->alias);
     TAILQ_INSERT_TAIL(&evhtp->aliases, alias, next);
     return 0;
 }
int evhtp_add_vhost (evhtp_t * evhtp, const char * name, evhtp_t * vhost)
add a virtual host.
add an evhtp_t structure (with its own callbacks) to a base evhtp_t structure for virtual hosts. It should be noted that if you enable SSL on the base evhtp_t and your version of OpenSSL supports SNI, the SNI hostname will always take precedence over the Host header value.
NOTE: If SSL is being used and the vhost was found via SNI, the Host: header will NOT be used to find a matching vhost.
Also, any hooks which are set prior to finding a vhost that are hooks which are after the host hook, they are overwritten by the callbacks and hooks set for the vhost specific evhtp_t structure.
Parameters
evhtp
name
vhost
Returns
Referenced by main().
{
     if (evhtp == NULL || name == NULL || vhost == NULL) {
         return -1;
     }
     if (TAILQ_FIRST(&vhost->vhosts) != NULL) {
         /* vhosts cannot have secondary vhosts defined */
         return -1;
     }
     if (!(vhost->server_name = strdup(name))) {
         return -1;
     }
     /* set the parent of this vhost so when the request has been completely
      * serviced, the vhost can be reset to the original evhtp structure.
      *
      * This allows for a keep-alive connection to make multiple requests with
      * different Host: values.
      */
     vhost->parent                 = evhtp;
     /* inherit various flags from the parent evhtp structure */
     vhost->bev_flags              = evhtp->bev_flags;
     vhost->max_body_size          = evhtp->max_body_size;
     vhost->max_keepalive_requests = evhtp->max_keepalive_requests;
     vhost->recv_timeo             = evhtp->recv_timeo;
     vhost->send_timeo             = evhtp->send_timeo;
     TAILQ_INSERT_TAIL(&evhtp->vhosts, vhost, next_vhost);
     return 0;
 }
evhtp_t* evhtp_new (evbase_t * evbase, void * arg)
creates a new evhtp_t instance
Parameters
evbase the initialized event base
arg user-defined argument which is evhtp_t specific
Returns
a new evhtp_t structure or NULL on error
References _evhtp_default_request_cb(), evhtp_alloc_assert, evhtp_assert, EVHTP_PARSE_QUERY_FLAG_LENIENT, and evhtp_set_gencb().
Referenced by main().
{
     evhtp_t * htp;
     evhtp_assert(evbase != NULL);
     htp               = calloc(sizeof(evhtp_t), 1);
     evhtp_alloc_assert(htp);
     htp->arg          = arg;
     htp->evbase       = evbase;
     htp->bev_flags    = BEV_OPT_CLOSE_ON_FREE;
     /* default to lenient argument parsing */
     htp->parser_flags = EVHTP_PARSE_QUERY_FLAG_LENIENT;
     TAILQ_INIT(&htp->vhosts);
     TAILQ_INIT(&htp->aliases);
     evhtp_set_gencb(htp, _evhtp_default_request_cb, (void *)htp);
     return htp;
 }
void evhtp_free (evhtp_t * evhtp)
References evhtp_callbacks_free(), evhtp_safe_free, evthr_pool_free(), evthr_pool_stop(), and TAILQ_FOREACH_SAFE.
Referenced by main().
{
     evhtp_alias_t * evhtp_alias, * tmp;
     if (evhtp == NULL) {
         return;
     }
 #ifndef EVHTP_DISABLE_EVTHR
     if (evhtp->thr_pool) {
         evthr_pool_stop(evhtp->thr_pool);
         evthr_pool_free(evhtp->thr_pool);
     }
 #endif
 #ifndef EVHTP_DISABLE_SSL
     if (evhtp->ssl_ctx) {
         SSL_CTX_free(evhtp->ssl_ctx);
     }
 #endif
     if (evhtp->server_name) {
         evhtp_safe_free(evhtp->server_name, free);
     }
     if (evhtp->callbacks) {
         evhtp_safe_free(evhtp->callbacks, evhtp_callbacks_free);
     }
     TAILQ_FOREACH_SAFE(evhtp_alias, &evhtp->aliases, next, tmp) {
         if (evhtp_alias->alias != NULL) {
             evhtp_safe_free(evhtp_alias->alias, free);
         }
         TAILQ_REMOVE(&evhtp->aliases, evhtp_alias, next);
         evhtp_safe_free(evhtp_alias, free);
     }
 #ifndef EVHTP_DISABLE_SSL
     if (evhtp->ssl_ctx) {
         SSL_CTX_free(evhtp->ssl_ctx);
     }
 #endif
     evhtp_safe_free(evhtp, free);
 } /* evhtp_free */
evhtp_connection_t* evhtp_connection_new (evbase_t * evbase, const char * addr, uint16_t port)
allocate a new connection
References evhtp_connection_new_dns().
Referenced by main(), and make_request().
{
     return evhtp_connection_new_dns(evbase, NULL, addr, port);
 }
evhtp_connection_t* evhtp_connection_new_dns (evbase_t * evbase, struct evdns_base * dns_base, const char * addr, uint16_t port)
allocate a new connection
References _evhtp_connection_eventcb(), _evhtp_connection_new(), evhtp_assert, evhtp_connection_free(), and evhtp_type_client.
Referenced by evhtp_connection_new().
{
     evhtp_connection_t * conn;
     int                  err;
     evhtp_assert(evbase != NULL);
     if (!(conn = _evhtp_connection_new(NULL, -1, evhtp_type_client))) {
         return NULL;
     }
     conn->evbase = evbase;
     conn->bev    = bufferevent_socket_new(evbase, -1, BEV_OPT_CLOSE_ON_FREE);
     if (conn->bev == NULL) {
         evhtp_connection_free(conn);
         return NULL;
     }
     bufferevent_enable(conn->bev, EV_READ);
     bufferevent_setcb(conn->bev, NULL, NULL,
                       _evhtp_connection_eventcb, conn);
     if (dns_base != NULL) {
         err = bufferevent_socket_connect_hostname(conn->bev, dns_base,
                                                   AF_UNSPEC, addr, port);
     } else {
         struct sockaddr_in  sin4;
         struct sockaddr_in6 sin6;
         struct sockaddr   * sin;
         int                 salen;
         if (inet_pton(AF_INET, addr, &sin4.sin_addr)) {
             sin4.sin_family = AF_INET;
             sin4.sin_port   = htons(port);
             sin = (struct sockaddr *)&sin4;
             salen           = sizeof(sin4);
         } else if (inet_pton(AF_INET6, addr, &sin6.sin6_addr)) {
             sin6.sin6_family = AF_INET6;
             sin6.sin6_port   = htons(port);
             sin = (struct sockaddr *)&sin6;
             salen = sizeof(sin6);
         } else {
             /* Not a valid IP. */
             evhtp_connection_free(conn);
             return NULL;
         }
         err = bufferevent_socket_connect(conn->bev, sin, salen);
     }
     /* not needed since any of the bufferevent errors will go straight to
      * the eventcb
      */
     if (err) {
         return NULL;
     }
     return conn;
 } /* evhtp_connection_new_dns */
evhtp_connection_t* evhtp_connection_ssl_new (evbase_t * evbase, const char * addr, uint16_t port, evhtp_ssl_ctx_t * ctx)
References _evhtp_connection_eventcb(), _evhtp_connection_new(), evhtp_assert, and evhtp_type_client.
{
     evhtp_connection_t * conn;
     struct sockaddr_in   sin;
     evhtp_assert(evbase != NULL);
     if (!(conn = _evhtp_connection_new(NULL, -1, evhtp_type_client))) {
         return NULL;
     }
     sin.sin_family      = AF_INET;
     sin.sin_addr.s_addr = inet_addr(addr);
     sin.sin_port        = htons(port);
     conn->ssl           = SSL_new(ctx);
     conn->evbase        = evbase;
     conn->bev           = bufferevent_openssl_socket_new(evbase, -1, conn->ssl,
                                                          BUFFEREVENT_SSL_CONNECTING, BEV_OPT_CLOSE_ON_FREE);
     bufferevent_enable(conn->bev, EV_READ);
     bufferevent_setcb(conn->bev, NULL, NULL,
                       _evhtp_connection_eventcb, conn);
     bufferevent_socket_connect(conn->bev,
                                (struct sockaddr *)&sin, sizeof(sin));
     return conn;
 }
evhtp_request_t* evhtp_request_new (evhtp_callback_cb cb, void * arg)
allocate a new request
References _evhtp_request_new(), cb, evhtp_alloc_assert, and EVHTP_PROTO_11.
Referenced by main(), and make_request().
{
     evhtp_request_t * r;
     r        = _evhtp_request_new(NULL);
     evhtp_alloc_assert(r);
     r->cb    = cb;
     r->cbarg = arg;
     r->proto = EVHTP_PROTO_11;
     return r;
 }
int evhtp_make_request (evhtp_connection_t * c, evhtp_request_t * r, htp_method meth, const char * uri)
make a client request
References _evhtp_create_headers(), evhtp_headers_for_each, EVHTP_PROTO_10, EVHTP_PROTO_11, and htparser_get_methodstr_m().
Referenced by main(), and make_request().
{
     evbuf_t * obuf;
     char    * proto;
     obuf       = bufferevent_get_output(c->bev);
     r->conn    = c;
     c->request = r;
     switch (r->proto) {
         case EVHTP_PROTO_10:
             proto = "1.0";
             break;
         case EVHTP_PROTO_11:
         default:
             proto = "1.1";
             break;
     }
     evbuffer_add_printf(obuf, "%s %s HTTP/%s\r\n",
                         htparser_get_methodstr_m(meth), uri, proto);
     evhtp_headers_for_each(r->headers_out, _evhtp_create_headers, obuf);
     evbuffer_add_reference(obuf, "\r\n", 2, NULL, NULL);
     if (evbuffer_get_length(r->buffer_out)) {
         evbuffer_add_buffer(obuf, r->buffer_out);
     }
     return 0;
 }
unsigned int evhtp_request_status (evhtp_request_t * r)
References htparser_get_status().
{
     return htparser_get_status(r->conn->parser);
 }
Variable Documentation
htparse_hooks request_psets static
Initial value:
= {
    .on_msg_begin       = _evhtp_request_parser_start,
    .method             = NULL,
    .scheme             = NULL,
    .host               = _evhtp_request_parser_host,
    .port               = _evhtp_request_parser_port,
    .path               = _evhtp_request_parser_path,
    .args               = _evhtp_request_parser_args,
    .uri                = NULL,
    .on_hdrs_begin      = _evhtp_request_parser_headers_start,
    .hdr_key            = _evhtp_request_parser_header_key,
    .hdr_val            = _evhtp_request_parser_header_val,
    .hostname           = _evhtp_request_parser_hostname,
    .on_hdrs_complete   = _evhtp_request_parser_headers,
    .on_new_chunk       = _evhtp_request_parser_chunk_new,
    .on_chunk_complete  = _evhtp_request_parser_chunk_fini,
    .on_chunks_complete = _evhtp_request_parser_chunks_fini,
    .body               = _evhtp_request_parser_body,
    .on_msg_complete    = _evhtp_request_parser_fini
}
callback definitions for request processing from libhtparse
int session_id_context = 1 static
Referenced by evhtp_ssl_init().
int ssl_num_locks static
Referenced by _evhtp_ssl_thread_lock(), and evhtp_ssl_use_threads().
evhtp_mutex_t* ssl_locks static
Referenced by _evhtp_ssl_thread_lock(), and evhtp_ssl_use_threads().
int ssl_locks_initialized = 0 static
Referenced by evhtp_ssl_use_threads().