Libevhtp: evthr.c File Reference
evthr.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>
#include <limits.h>
#include <errno.h>
#include <fcntl.h>
#include <sys/syscall.h>
#include <sys/ioctl.h>
#include <sys/queue.h>
#include <unistd.h>
#include <pthread.h>
#include <event2/event.h>
#include <event2/thread.h>
#include "evhtp-internal.h"
#include "evthr.h"
Macros
#define _GNU_SOURCE
#define _evthr_read(thr, cmd, sock) (recv(sock, cmd, sizeof(evthr_cmd_t), 0) == sizeof(evthr_cmd_t)) ? 1 : 0
Typedefs
typedef struct evthr_pool_slist evthr_pool_slist_t
Functions
struct evthr_cmd __attribute__ ((packed))
TAILQ_HEAD (evthr_pool_slist, evthr)
static void _evthr_read_cmd (evutil_socket_t sock, short which, void *args)
static void * _evthr_loop (void *args)
evthr_res evthr_defer (evthr_t *thread, evthr_cb cb, void *arg)
evthr_res evthr_stop (evthr_t *thread)
evbase_t * evthr_get_base (evthr_t *thr)
void evthr_set_aux (evthr_t *thr, void *aux)
void * evthr_get_aux (evthr_t *thr)
int evthr_set_initcb (evthr_t *thr, evthr_init_cb cb)
int evthr_set_exitcb (evthr_t *thr, evthr_exit_cb cb)
static evthr_t * _evthr_new (evthr_init_cb init_cb, evthr_exit_cb exit_cb, void *args)
evthr_t * evhtr_new (evthr_init_cb init_cb, void *args)
evthr_t * evthr_wexit_new (evthr_init_cb init_cb, evthr_exit_cb exit_cb, void *args)
int evthr_start (evthr_t *thread)
void evthr_free (evthr_t *thread)
void evthr_pool_free (evthr_pool_t *pool)
evthr_res evthr_pool_stop (evthr_pool_t *pool)
evthr_res evthr_pool_defer (evthr_pool_t *pool, evthr_cb cb, void *arg)
static evthr_pool_t * _evthr_pool_new (int nthreads, evthr_init_cb init_cb, evthr_exit_cb exit_cb, void *shared)
evthr_pool_t * evthr_pool_new (int nthreads, evthr_init_cb init_cb, void *shared)
evthr_pool_t * evthr_pool_wexit_new (int nthreads, evthr_init_cb init_cb, evthr_exit_cb exit_cb, void *shared)
int evthr_pool_start (evthr_pool_t *pool)
Variables
uint8_t stop
void * args
evthr_cb cb
struct evthr_pool __attribute__
Macro Definition Documentation
#define _GNU_SOURCE
#define _evthr_read (thr, cmd, sock) (recv(sock, cmd, sizeof(evthr_cmd_t), 0) == sizeof(evthr_cmd_t)) ? 1 : 0
Referenced by _evthr_read_cmd().
Typedef Documentation
typedef struct evthr_pool_slist evthr_pool_slist_t
Function Documentation
struct evthr_cmd __attribute__ ((packed))
TAILQ_HEAD (evthr_pool_slist , evthr)
static void _evthr_read_cmd (evutil_socket_t sock, short which, void * args) static
References _evthr_read, evhtp_likely, and evhtp_unlikely.
Referenced by _evthr_loop().
{
     evthr_t   * thread;
     evthr_cmd_t cmd;
     int         stopped;
     if (!(thread = (evthr_t *)args)) {
         return;
     }
     stopped = 0;
     if (evhtp_likely(_evthr_read(thread, &cmd, sock) == 1)) {
         stopped = cmd.stop;
         if (evhtp_likely(cmd.cb != NULL)) {
             (cmd.cb)(thread, cmd.args, thread->arg);
         }
     }
     if (evhtp_unlikely(stopped == 1)) {
         event_base_loopbreak(thread->evbase);
     }
     return;
 } /* _evthr_read_cmd */
static void* _evthr_loop (void * args) static
References _evthr_read_cmd().
Referenced by evthr_start().
{
     evthr_t * thread;
     if (!(thread = (evthr_t *)args)) {
         return NULL;
     }
     if (thread == NULL || thread->thr == NULL) {
         pthread_exit(NULL);
     }
     thread->evbase = event_base_new();
     thread->event  = event_new(thread->evbase, thread->rdr,
                                EV_READ | EV_PERSIST, _evthr_read_cmd, args);
     event_add(thread->event, NULL);
 #ifdef EVTHR_SHARED_PIPE
     if (thread->pool_rdr > 0) {
         thread->shared_pool_ev = event_new(thread->evbase, thread->pool_rdr,
                                            EV_READ | EV_PERSIST, _evthr_read_cmd, args);
         event_add(thread->shared_pool_ev, NULL);
     }
 #endif
     pthread_mutex_lock(&thread->lock);
     if (thread->init_cb != NULL) {
         (thread->init_cb)(thread, thread->arg);
     }
     pthread_mutex_unlock(&thread->lock);
     event_base_loop(thread->evbase, 0);
     pthread_mutex_lock(&thread->lock);
     if (thread->exit_cb != NULL) {
         (thread->exit_cb)(thread, thread->arg);
     }
     pthread_mutex_unlock(&thread->lock);
     if (thread->err == 1) {
         fprintf(stderr, "FATAL ERROR!\n");
     }
     pthread_exit(NULL);
 } /* _evthr_loop */
evthr_res evthr_defer (evthr_t * thread, evthr_cb cb, void * arg)
References cb, EVTHR_RES_OK, and EVTHR_RES_RETRY.
Referenced by evthr_pool_defer().
{
     evthr_cmd_t cmd = {
         .cb   = cb,
         .args = arg,
         .stop = 0
     };
     if (send(thread->wdr, &cmd, sizeof(cmd), 0) <= 0) {
         return EVTHR_RES_RETRY;
     }
     return EVTHR_RES_OK;
 }
evthr_res evthr_stop (evthr_t * thread)
References EVTHR_RES_OK, and EVTHR_RES_RETRY.
Referenced by evthr_pool_stop().
{
     evthr_cmd_t cmd = {
         .cb   = NULL,
         .args = NULL,
         .stop = 1
     };
     if (send(thread->wdr, &cmd, sizeof(evthr_cmd_t), 0) < 0) {
         return EVTHR_RES_RETRY;
     }
     pthread_join(*thread->thr, NULL);
     return EVTHR_RES_OK;
 }
evbase_t* evthr_get_base (evthr_t * thr)
Referenced by _evhtp_run_in_thread(), app_init_thread(), and frontend_cb().
{
     return thr ? thr->evbase : NULL;
 }
void evthr_set_aux (evthr_t * thr, void * aux)
Referenced by app_init_thread(), and init_thread_cb().
{
     if (thr) {
         thr->aux = aux;
     }
 }
void* evthr_get_aux (evthr_t * thr)
Referenced by app_process_request(), and frontend_cb().
{
     return thr ? thr->aux : NULL;
 }
int evthr_set_initcb (evthr_t * thr, evthr_init_cb cb)
References cb.
Referenced by _evthr_new().
{
     if (thr == NULL) {
         return -1;
     }
     thr->init_cb = cb;
     return 01;
 }
int evthr_set_exitcb (evthr_t * thr, evthr_exit_cb cb)
References cb.
Referenced by _evthr_new().
{
     if (thr == NULL) {
         return -1;
     }
     thr->exit_cb = cb;
     return 0;
 }
static evthr_t* _evthr_new (evthr_init_cb init_cb, evthr_exit_cb exit_cb, void * args) static
References args, evthr_free(), evthr_set_exitcb(), and evthr_set_initcb().
Referenced by evhtr_new(), and evthr_wexit_new().
{
     evthr_t * thread;
     int       fds[2];
     if (evutil_socketpair(AF_UNIX, SOCK_STREAM, 0, fds) == -1) {
         return NULL;
     }
     evutil_make_socket_nonblocking(fds[0]);
     evutil_make_socket_nonblocking(fds[1]);
     if (!(thread = calloc(sizeof(evthr_t), 1))) {
         return NULL;
     }
     thread->thr = malloc(sizeof(pthread_t));
     thread->arg = args;
     thread->rdr = fds[0];
     thread->wdr = fds[1];
     evthr_set_initcb(thread, init_cb);
     evthr_set_exitcb(thread, exit_cb);
     if (pthread_mutex_init(&thread->lock, NULL)) {
         evthr_free(thread);
         return NULL;
     }
     return thread;
 } /* evthr_new */
evthr_t* evhtr_new (evthr_init_cb init_cb, void * args)
References _evthr_new().
{
     return _evthr_new(init_cb, NULL, args);
 }
evthr_t* evthr_wexit_new (evthr_init_cb init_cb, evthr_exit_cb exit_cb, void * args)
References _evthr_new().
Referenced by _evthr_pool_new().
{
     return _evthr_new(init_cb, exit_cb, args);
 }
int evthr_start (evthr_t * thread)
References _evthr_loop().
Referenced by evthr_pool_start().
{
     if (thread == NULL || thread->thr == NULL) {
         return -1;
     }
     if (pthread_create(thread->thr, NULL, _evthr_loop, (void *)thread)) {
         return -1;
     }
     return 0;
 }
void evthr_free (evthr_t * thread)
Referenced by _evthr_new(), and evthr_pool_free().
{
     if (thread == NULL) {
         return;
     }
     if (thread->rdr > 0) {
         close(thread->rdr);
     }
     if (thread->wdr > 0) {
         close(thread->wdr);
     }
     if (thread->thr) {
         free(thread->thr);
     }
     if (thread->event) {
         event_free(thread->event);
     }
     if (thread->evbase) {
         event_base_free(thread->evbase);
     }
     free(thread);
 } /* evthr_free */
void evthr_pool_free (evthr_pool_t * pool)
References evthr_free(), and TAILQ_FOREACH_SAFE.
Referenced by _evthr_pool_new(), and evhtp_free().
{
     evthr_t * thread;
     evthr_t * save;
     if (pool == NULL) {
         return;
     }
     TAILQ_FOREACH_SAFE(thread, &pool->threads, next, save) {
         TAILQ_REMOVE(&pool->threads, thread, next);
         evthr_free(thread);
     }
     free(pool);
 }
evthr_res evthr_pool_stop (evthr_pool_t * pool)
References EVTHR_RES_FATAL, EVTHR_RES_OK, evthr_stop(), and TAILQ_FOREACH_SAFE.
Referenced by evhtp_free().
{
     evthr_t * thr;
     evthr_t * save;
     if (pool == NULL) {
         return EVTHR_RES_FATAL;
     }
     TAILQ_FOREACH_SAFE(thr, &pool->threads, next, save) {
         evthr_stop(thr);
     }
     return EVTHR_RES_OK;
 }
evthr_res evthr_pool_defer (evthr_pool_t * pool, evthr_cb cb, void * arg)
References cb, evhtp_unlikely, evthr_defer(), EVTHR_RES_FATAL, EVTHR_RES_NOCB, EVTHR_RES_OK, and EVTHR_RES_RETRY.
Referenced by _evhtp_accept_cb().
{
 #ifdef EVTHR_SHARED_PIPE
     evthr_cmd_t cmd = {
         .cb   = cb,
         .args = arg,
         .stop = 0
     };
     if (evhtp_unlikely(send(pool->wdr, &cmd, sizeof(cmd), 0) == -1)) {
         return EVTHR_RES_RETRY;
     }
     return EVTHR_RES_OK;
 #else
     evthr_t * thr = NULL;
     if (pool == NULL) {
         return EVTHR_RES_FATAL;
     }
     if (cb == NULL) {
         return EVTHR_RES_NOCB;
     }
     thr = TAILQ_FIRST(&pool->threads);
     TAILQ_REMOVE(&pool->threads, thr, next);
     TAILQ_INSERT_TAIL(&pool->threads, thr, next);
     return evthr_defer(thr, cb, arg);
 #endif
 } /* evthr_pool_defer */
static evthr_pool_t* _evthr_pool_new (int nthreads, evthr_init_cb init_cb, evthr_exit_cb exit_cb, void * shared) static
References evthr_pool_free(), and evthr_wexit_new().
Referenced by evthr_pool_new(), and evthr_pool_wexit_new().
{
     evthr_pool_t * pool;
     int            i;
 #ifdef EVTHR_SHARED_PIPE
     int fds[2];
 #endif
     if (nthreads == 0) {
         return NULL;
     }
     if (!(pool = calloc(sizeof(evthr_pool_t), 1))) {
         return NULL;
     }
     pool->nthreads = nthreads;
     TAILQ_INIT(&pool->threads);
 #ifdef EVTHR_SHARED_PIPE
     if (evutil_socketpair(AF_UNIX, SOCK_DGRAM, 0, fds) == -1) {
         return NULL;
     }
     evutil_make_socket_nonblocking(fds[0]);
     evutil_make_socket_nonblocking(fds[1]);
     pool->rdr = fds[0];
     pool->wdr = fds[1];
 #endif
     for (i = 0; i < nthreads; i++) {
         evthr_t * thread;
         if (!(thread = evthr_wexit_new(init_cb, exit_cb, shared))) {
             evthr_pool_free(pool);
             return NULL;
         }
 #ifdef EVTHR_SHARED_PIPE
         thread->pool_rdr = fds[0];
 #endif
         TAILQ_INSERT_TAIL(&pool->threads, thread, next);
     }
     return pool;
 } /* _evthr_pool_new */
evthr_pool_t* evthr_pool_new (int nthreads, evthr_init_cb init_cb, void * shared)
References _evthr_pool_new().
{
     return _evthr_pool_new(nthreads, init_cb, NULL, shared);
 }
evthr_pool_t* evthr_pool_wexit_new (int nthreads, evthr_init_cb init_cb, evthr_exit_cb exit_cb, void * shared)
References _evthr_pool_new().
Referenced by _evhtp_use_threads().
{
     return _evthr_pool_new(nthreads, init_cb, exit_cb, shared);
 }
int evthr_pool_start (evthr_pool_t * pool)
References evthr_start().
Referenced by _evhtp_use_threads().
{
     evthr_t * evthr = NULL;
     if (pool == NULL) {
         return -1;
     }
     TAILQ_FOREACH(evthr, &pool->threads, next) {
         if (evthr_start(evthr) < 0) {
             return -1;
         }
         usleep(5000);
     }
     return 0;
 }
Variable Documentation
uint8_t stop
void* args
Referenced by _evhtp_run_post_accept(), _evhtp_run_pre_accept(), and _evthr_new().
evthr_cb cb
Referenced by _evhtp_request_set_callbacks(), evhtp_callback_new(), evhtp_kvs_for_each(), evhtp_request_new(), evhtp_set_gencb(), evhtp_set_post_accept_cb(), evhtp_set_pre_accept_cb(), evthr_defer(), evthr_pool_defer(), evthr_set_exitcb(), and evthr_set_initcb().
struct evthr_pool __attribute__