Libevhtp: evthr.h File Reference
evthr.h File Reference
#include <pthread.h>
#include <event2/event.h>
#include <evhtp-config.h>
Typedefs
typedef struct event_base evbase_t
typedef struct event ev_t
typedef enum evthr_res evthr_res
typedef void(* evthr_cb) (evthr_t *thr, void *cmd_arg, void *shared)
typedef void(* evthr_init_cb) (evthr_t *thr, void *shared)
typedef void(* evthr_exit_cb) (evthr_t *thr, void *shared)
Enumerations
enum evthr_res {
EVTHR_RES_OK = 0, EVTHR_RES_BACKLOG, EVTHR_RES_RETRY, EVTHR_RES_NOCB,
EVTHR_RES_FATAL
}
Functions
EVHTP_EXPORT evthr_t * evthr_new (evthr_init_cb, void *) DEPRECATED("will take on the syntax of evthr_wexit_new")
EVHTP_EXPORT evbase_t * evthr_get_base (evthr_t *thr)
EVHTP_EXPORT void evthr_set_aux (evthr_t *thr, void *aux)
EVHTP_EXPORT void * evthr_get_aux (evthr_t *thr)
EVHTP_EXPORT int evthr_start (evthr_t *evthr)
EVHTP_EXPORT evthr_res evthr_stop (evthr_t *evthr)
EVHTP_EXPORT evthr_res evthr_defer (evthr_t *evthr, evthr_cb cb, void *)
EVHTP_EXPORT void evthr_free (evthr_t *evthr)
EVHTP_EXPORT evthr_pool_t * evthr_pool_new (int nthreads, evthr_init_cb, void *) DEPRECATED("will take on the syntax of evthr_pool_wexit_new")
EVHTP_EXPORT int evthr_pool_start (evthr_pool_t *pool)
EVHTP_EXPORT evthr_res evthr_pool_stop (evthr_pool_t *pool)
EVHTP_EXPORT evthr_res evthr_pool_defer (evthr_pool_t *pool, evthr_cb cb, void *arg)
EVHTP_EXPORT void evthr_pool_free (evthr_pool_t *pool)
EVHTP_EXPORT evthr_t * evthr_wexit_new (evthr_init_cb, evthr_exit_cb, void *shared)
EVHTP_EXPORT evthr_pool_t * evthr_pool_wexit_new (int nthreads, evthr_init_cb, evthr_exit_cb, void *)
Typedef Documentation
typedef struct event_base evbase_t
typedef struct event ev_t
typedef enum evthr_res evthr_res
typedef void(* evthr_cb) (evthr_t *thr, void *cmd_arg, void *shared)
typedef void(* evthr_init_cb) (evthr_t *thr, void *shared)
typedef void(* evthr_exit_cb) (evthr_t *thr, void *shared)
Enumeration Type Documentation
enum evthr_res
Enumerator
EVTHR_RES_OK
EVTHR_RES_BACKLOG
EVTHR_RES_RETRY
EVTHR_RES_NOCB
EVTHR_RES_FATAL
                {
     EVTHR_RES_OK = 0,
     EVTHR_RES_BACKLOG,
     EVTHR_RES_RETRY,
     EVTHR_RES_NOCB,
     EVTHR_RES_FATAL
 };
Function Documentation
EVHTP_EXPORT evthr_t* evthr_new (evthr_init_cb , void *)
EVHTP_EXPORT evbase_t* evthr_get_base (evthr_t * thr)
Referenced by _evhtp_run_in_thread(), app_init_thread(), and frontend_cb().
{
     return thr ? thr->evbase : NULL;
 }
EVHTP_EXPORT void evthr_set_aux (evthr_t * thr, void * aux)
Referenced by app_init_thread(), and init_thread_cb().
{
     if (thr) {
         thr->aux = aux;
     }
 }
EVHTP_EXPORT void* evthr_get_aux (evthr_t * thr)
Referenced by app_process_request(), and frontend_cb().
{
     return thr ? thr->aux : NULL;
 }
EVHTP_EXPORT int evthr_start (evthr_t * evthr)
References _evthr_loop().
Referenced by evthr_pool_start().
{
     if (thread == NULL || thread->thr == NULL) {
         return -1;
     }
     if (pthread_create(thread->thr, NULL, _evthr_loop, (void *)thread)) {
         return -1;
     }
     return 0;
 }
EVHTP_EXPORT evthr_res evthr_stop (evthr_t * evthr)
References EVTHR_RES_OK, and EVTHR_RES_RETRY.
Referenced by evthr_pool_stop().
{
     evthr_cmd_t cmd = {
         .cb   = NULL,
         .args = NULL,
         .stop = 1
     };
     if (send(thread->wdr, &cmd, sizeof(evthr_cmd_t), 0) < 0) {
         return EVTHR_RES_RETRY;
     }
     pthread_join(*thread->thr, NULL);
     return EVTHR_RES_OK;
 }
EVHTP_EXPORT evthr_res evthr_defer (evthr_t * evthr, evthr_cb cb, void *)
References cb, EVTHR_RES_OK, and EVTHR_RES_RETRY.
Referenced by evthr_pool_defer().
{
     evthr_cmd_t cmd = {
         .cb   = cb,
         .args = arg,
         .stop = 0
     };
     if (send(thread->wdr, &cmd, sizeof(cmd), 0) <= 0) {
         return EVTHR_RES_RETRY;
     }
     return EVTHR_RES_OK;
 }
EVHTP_EXPORT void evthr_free (evthr_t * evthr)
Referenced by _evthr_new(), and evthr_pool_free().
{
     if (thread == NULL) {
         return;
     }
     if (thread->rdr > 0) {
         close(thread->rdr);
     }
     if (thread->wdr > 0) {
         close(thread->wdr);
     }
     if (thread->thr) {
         free(thread->thr);
     }
     if (thread->event) {
         event_free(thread->event);
     }
     if (thread->evbase) {
         event_base_free(thread->evbase);
     }
     free(thread);
 } /* evthr_free */
EVHTP_EXPORT evthr_pool_t* evthr_pool_new (int nthreads, evthr_init_cb , void *)
References _evthr_pool_new().
{
     return _evthr_pool_new(nthreads, init_cb, NULL, shared);
 }
EVHTP_EXPORT int evthr_pool_start (evthr_pool_t * pool)
References evthr_start().
Referenced by _evhtp_use_threads().
{
     evthr_t * evthr = NULL;
     if (pool == NULL) {
         return -1;
     }
     TAILQ_FOREACH(evthr, &pool->threads, next) {
         if (evthr_start(evthr) < 0) {
             return -1;
         }
         usleep(5000);
     }
     return 0;
 }
EVHTP_EXPORT evthr_res evthr_pool_stop (evthr_pool_t * pool)
References EVTHR_RES_FATAL, EVTHR_RES_OK, evthr_stop(), and TAILQ_FOREACH_SAFE.
Referenced by evhtp_free().
{
     evthr_t * thr;
     evthr_t * save;
     if (pool == NULL) {
         return EVTHR_RES_FATAL;
     }
     TAILQ_FOREACH_SAFE(thr, &pool->threads, next, save) {
         evthr_stop(thr);
     }
     return EVTHR_RES_OK;
 }
EVHTP_EXPORT evthr_res evthr_pool_defer (evthr_pool_t * pool, evthr_cb cb, void * arg)
References cb, evhtp_unlikely, evthr_defer(), EVTHR_RES_FATAL, EVTHR_RES_NOCB, EVTHR_RES_OK, and EVTHR_RES_RETRY.
Referenced by _evhtp_accept_cb().
{
 #ifdef EVTHR_SHARED_PIPE
     evthr_cmd_t cmd = {
         .cb   = cb,
         .args = arg,
         .stop = 0
     };
     if (evhtp_unlikely(send(pool->wdr, &cmd, sizeof(cmd), 0) == -1)) {
         return EVTHR_RES_RETRY;
     }
     return EVTHR_RES_OK;
 #else
     evthr_t * thr = NULL;
     if (pool == NULL) {
         return EVTHR_RES_FATAL;
     }
     if (cb == NULL) {
         return EVTHR_RES_NOCB;
     }
     thr = TAILQ_FIRST(&pool->threads);
     TAILQ_REMOVE(&pool->threads, thr, next);
     TAILQ_INSERT_TAIL(&pool->threads, thr, next);
     return evthr_defer(thr, cb, arg);
 #endif
 } /* evthr_pool_defer */
EVHTP_EXPORT void evthr_pool_free (evthr_pool_t * pool)
References evthr_free(), and TAILQ_FOREACH_SAFE.
Referenced by _evthr_pool_new(), and evhtp_free().
{
     evthr_t * thread;
     evthr_t * save;
     if (pool == NULL) {
         return;
     }
     TAILQ_FOREACH_SAFE(thread, &pool->threads, next, save) {
         TAILQ_REMOVE(&pool->threads, thread, next);
         evthr_free(thread);
     }
     free(pool);
 }
EVHTP_EXPORT evthr_t* evthr_wexit_new (evthr_init_cb , evthr_exit_cb , void * shared)
References _evthr_new().
Referenced by _evthr_pool_new().
{
     return _evthr_new(init_cb, exit_cb, args);
 }
EVHTP_EXPORT evthr_pool_t* evthr_pool_wexit_new (int nthreads, evthr_init_cb , evthr_exit_cb , void *)
References _evthr_pool_new().
Referenced by _evhtp_use_threads().
{
     return _evthr_pool_new(nthreads, init_cb, exit_cb, shared);
 }