Libevhtp: htparse.h File Reference
htparse.h File Reference
#include "evhtp-config.h"
Classes
struct htparse_hooks
Typedefs
typedef enum htp_scheme htp_scheme
typedef enum htp_method htp_method
typedef enum htp_type htp_type
typedef enum htpparse_error htpparse_error
typedef int(* htparse_hook) (htparser *)
typedef int(* htparse_data_hook) (htparser *, const char *, size_t)
Enumerations
enum htp_type { htp_type_request = 0, htp_type_response }
enum htp_scheme {
htp_scheme_none = 0, htp_scheme_ftp, htp_scheme_http, htp_scheme_https,
htp_scheme_nfs, htp_scheme_unknown
}
enum htp_method {
htp_method_GET = 0, htp_method_HEAD, htp_method_POST, htp_method_PUT,
htp_method_DELETE, htp_method_MKCOL, htp_method_COPY, htp_method_MOVE,
htp_method_OPTIONS, htp_method_PROPFIND, htp_method_PROPPATCH, htp_method_LOCK,
htp_method_UNLOCK, htp_method_TRACE, htp_method_CONNECT, htp_method_PATCH,
htp_method_UNKNOWN
}
enum htpparse_error {
htparse_error_none = 0, htparse_error_too_big, htparse_error_inval_method, htparse_error_inval_reqline,
htparse_error_inval_schema, htparse_error_inval_proto, htparse_error_inval_ver, htparse_error_inval_hdr,
htparse_error_inval_chunk_sz, htparse_error_inval_chunk, htparse_error_inval_state, htparse_error_user,
htparse_error_status, htparse_error_generic
}
Functions
EVHTP_EXPORT size_t htparser_run (htparser *, htparse_hooks *, const char *, size_t)
EVHTP_EXPORT int htparser_should_keep_alive (htparser *p)
EVHTP_EXPORT htp_scheme htparser_get_scheme (htparser *)
EVHTP_EXPORT htp_method htparser_get_method (htparser *)
EVHTP_EXPORT const char * htparser_get_methodstr (htparser *)
EVHTP_EXPORT const char * htparser_get_methodstr_m (htp_method)
EVHTP_EXPORT void htparser_set_major (htparser *, unsigned char)
EVHTP_EXPORT void htparser_set_minor (htparser *, unsigned char)
EVHTP_EXPORT unsigned char htparser_get_major (htparser *)
EVHTP_EXPORT unsigned char htparser_get_minor (htparser *)
EVHTP_EXPORT unsigned char htparser_get_multipart (htparser *)
EVHTP_EXPORT unsigned int htparser_get_status (htparser *)
EVHTP_EXPORT uint64_t htparser_get_content_length (htparser *)
EVHTP_EXPORT uint64_t htparser_get_content_pending (htparser *)
EVHTP_EXPORT uint64_t htparser_get_total_bytes_read (htparser *)
EVHTP_EXPORT htpparse_error htparser_get_error (htparser *)
EVHTP_EXPORT const char * htparser_get_strerror (htparser *)
EVHTP_EXPORT void * htparser_get_userdata (htparser *)
EVHTP_EXPORT void htparser_set_userdata (htparser *, void *)
EVHTP_EXPORT void htparser_init (htparser *, htp_type)
EVHTP_EXPORT htparser * htparser_new (void)
Typedef Documentation
typedef enum htp_scheme htp_scheme
typedef enum htp_method htp_method
typedef enum htp_type htp_type
typedef enum htpparse_error htpparse_error
typedef int(* htparse_hook) (htparser *)
typedef int(* htparse_data_hook) (htparser *, const char *, size_t)
Enumeration Type Documentation
enum htp_type
Enumerator
htp_type_request
htp_type_response
               {
     htp_type_request = 0,
     htp_type_response
 };
enum htp_scheme
Enumerator
htp_scheme_none
htp_scheme_ftp
htp_scheme_http
htp_scheme_https
htp_scheme_nfs
htp_scheme_unknown
                 {
     htp_scheme_none = 0,
     htp_scheme_ftp,
     htp_scheme_http,
     htp_scheme_https,
     htp_scheme_nfs,
     htp_scheme_unknown
 };
enum htp_method
Enumerator
htp_method_GET
htp_method_HEAD
htp_method_POST
htp_method_PUT
htp_method_DELETE
htp_method_MKCOL
htp_method_COPY
htp_method_MOVE
htp_method_OPTIONS
htp_method_PROPFIND
htp_method_PROPPATCH
htp_method_LOCK
htp_method_UNLOCK
htp_method_TRACE
htp_method_CONNECT
htp_method_PATCH
htp_method_UNKNOWN
                 {
     htp_method_GET = 0,
     htp_method_HEAD,
     htp_method_POST,
     htp_method_PUT,
     htp_method_DELETE,
     htp_method_MKCOL,
     htp_method_COPY,
     htp_method_MOVE,
     htp_method_OPTIONS,
     htp_method_PROPFIND,
     htp_method_PROPPATCH,
     htp_method_LOCK,
     htp_method_UNLOCK,
     htp_method_TRACE,
     htp_method_CONNECT, /* RFC 2616 */
     htp_method_PATCH,   /* RFC 5789 */
     htp_method_UNKNOWN,
 };
enum htpparse_error
Enumerator
htparse_error_none
htparse_error_too_big
htparse_error_inval_method
htparse_error_inval_reqline
htparse_error_inval_schema
htparse_error_inval_proto
htparse_error_inval_ver
htparse_error_inval_hdr
htparse_error_inval_chunk_sz
htparse_error_inval_chunk
htparse_error_inval_state
htparse_error_user
htparse_error_status
htparse_error_generic
                     {
     htparse_error_none = 0,
     htparse_error_too_big,
     htparse_error_inval_method,
     htparse_error_inval_reqline,
     htparse_error_inval_schema,
     htparse_error_inval_proto,
     htparse_error_inval_ver,
     htparse_error_inval_hdr,
     htparse_error_inval_chunk_sz,
     htparse_error_inval_chunk,
     htparse_error_inval_state,
     htparse_error_user,
     htparse_error_status,
     htparse_error_generic
 };
Function Documentation
EVHTP_EXPORT size_t htparser_run (htparser * , htparse_hooks * , const char * , size_t)
References _MIN_READ, _str3_cmp, _str4cmp, _str5cmp, _str6cmp, _str8cmp, _str9cmp, CR, eval_hdr_val_connection, eval_hdr_val_content_length, eval_hdr_val_content_type, eval_hdr_val_hostname, eval_hdr_val_none, eval_hdr_val_proxy_connection, eval_hdr_val_transfer_encoding, evhtp_likely, evhtp_unlikely, get_method(), htp_method_CONNECT, htp_method_UNKNOWN, htp_scheme_ftp, htp_scheme_http, htp_scheme_https, htp_scheme_nfs, htp_scheme_unknown, htp_type_request, htp_type_response, htparse_error_generic, htparse_error_inval_chunk, htparse_error_inval_chunk_sz, htparse_error_inval_hdr, htparse_error_inval_method, htparse_error_inval_proto, htparse_error_inval_reqline, htparse_error_inval_schema, htparse_error_inval_state, htparse_error_inval_ver, htparse_error_none, htparse_error_status, htparse_error_too_big, htparse_error_user, htparse_log_debug, is_host_char(), LF, parser_flag_chunked, parser_flag_connection_close, parser_flag_connection_keep_alive, parser_flag_trailing, s_after_slash_in_uri, s_almost_done, s_body_read, s_check_uri, s_chunk_data, s_chunk_data_almost_done, s_chunk_data_done, s_chunk_size, s_chunk_size_almost_done, s_chunk_size_start, s_done, s_first_major_digit, s_first_minor_digit, s_hdrline_almost_done, s_hdrline_done, s_hdrline_hdr_almost_done, s_hdrline_hdr_done, s_hdrline_hdr_key, s_hdrline_hdr_space_before_val, s_hdrline_hdr_val, s_hdrline_start, s_host, s_host_done, s_host_ipv6, s_http_09, s_http_H, s_http_HT, s_http_HTT, s_http_HTTP, s_major_digit, s_method, s_minor_digit, s_port, s_schema, s_schema_slash, s_schema_slash_slash, s_space_after_status, s_spaces_after_digit, s_spaces_before_uri, s_start, s_status, s_status_text, and s_uri.
Referenced by _evhtp_connection_readcb(), and _run_test().
{
     unsigned char ch;
     char          c;
     size_t        i;
     htparse_log_debug("enter");
     htparse_log_debug("p == %p", p);
     p->error      = htparse_error_none;
     p->bytes_read = 0;
     for (i = 0; i < len; i++) {
         int res;
         int err;
         ch = data[i];
         htparse_log_debug("[%p] data[%d] = %c (%x)", p, i, isprint(ch) ? ch : ' ', ch);
         if (p->buf_idx >= sizeof(p->buf)) {
             p->error = htparse_error_too_big;
             return i + 1;
         }
         p->total_bytes_read += 1;
         p->bytes_read       += 1;
         switch (p->state) {
             case s_start:
                 htparse_log_debug("[%p] s_start", p);
                 if (ch == CR || ch == LF) {
                     break;
                 }
                 if ((ch < 'A' || ch > 'Z') && ch != '_') {
                     p->error = htparse_error_inval_reqline;
                     return i + 1;
                 }
                 p->flags             = 0;
                 p->error             = htparse_error_none;
                 p->method            = htp_method_UNKNOWN;
                 p->multipart         = 0;
                 p->major             = 0;
                 p->minor             = 0;
                 p->content_len       = 0;
                 p->orig_content_len  = 0;
                 p->status            = 0;
                 p->status_count      = 0;
                 p->scheme_offset     = NULL;
                 p->host_offset       = NULL;
                 p->port_offset       = NULL;
                 p->path_offset       = NULL;
                 p->args_offset       = NULL;
                 res = hook_on_msg_begin_run(p, hooks);
                 p->buf[p->buf_idx++] = ch;
                 p->buf[p->buf_idx]   = '\0';
                 if (evhtp_likely(p->type == htp_type_request)) {
                     p->state = s_method;
                 } else if (p->type == htp_type_response && ch == 'H') {
                     p->state = s_http_H;
                 } else {
                     p->error = htparse_error_inval_reqline;
                     return i + 1;
                 }
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_method:
                 htparse_log_debug("[%p] s_method", p);
                 do {
                     if (ch == ' ') {
                         p->method  = get_method(p->buf, p->buf_idx);
                         res        = hook_method_run(p, hooks, p->buf, p->buf_idx);
                         p->buf_idx = 0;
                         p->state   = s_spaces_before_uri;
                         if (res) {
                             p->error = htparse_error_user;
                             return i + 1;
                         }
                         break;
                     } else {
                         if ((ch < 'A' || ch > 'Z') && ch != '_') {
                             p->error = htparse_error_inval_method;
                             return i + 1;
                         }
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                     }
                     ch = data[++i];
                 } while (i < len);
                 break;
             case s_spaces_before_uri:
                 htparse_log_debug("[%p] s_spaces_before_uri", p);
                 /* CONNECT is special - RFC 2817 section 5.2:
                  * The Request-URI portion of the Request-Line is
                  * always an 'authority' as defined by URI Generic
                  * Syntax [2], which is to say the host name and port
                  * number destination of the requested connection
                  * separated by a colon
                  */
                 if (p->method == htp_method_CONNECT) {
                     switch (ch) {
                         case ' ':
                             break;
                         case '[':
                             /* Literal IPv6 address start. */
                             p->buf[p->buf_idx++] = ch;
                             p->buf[p->buf_idx]   = '\0';
                             p->host_offset       = &p->buf[p->buf_idx];
                             p->state = s_host_ipv6;
                             break;
                         default:
                             if (!is_host_char(ch)) {
                                 p->error = htparse_error_inval_reqline;
                                 return i + 1;
                             }
                             p->host_offset       = &p->buf[p->buf_idx];
                             p->buf[p->buf_idx++] = ch;
                             p->buf[p->buf_idx]   = '\0';
                             p->state = s_host;
                             break;
                     } /* switch */
                     break;
                 }
                 switch (ch) {
                     case ' ':
                         break;
                     case '/':
                         p->path_offset       = &p->buf[p->buf_idx];
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state = s_after_slash_in_uri;
                         break;
                     default:
                         c        = (unsigned char)(ch | 0x20);
                         if (c >= 'a' && c <= 'z') {
                             p->scheme_offset     = &p->buf[p->buf_idx];
                             p->buf[p->buf_idx++] = ch;
                             p->buf[p->buf_idx]   = '\0';
                             p->state = s_schema;
                             break;
                         }
                         p->error = htparse_error_inval_reqline;
                         return i + 1;
                 } /* switch */
                 break;
             case s_schema:
                 htparse_log_debug("[%p] s_schema", p);
                 c = (unsigned char)(ch | 0x20);
                 if (c >= 'a' && c <= 'z') {
                     p->buf[p->buf_idx++] = ch;
                     p->buf[p->buf_idx]   = '\0';
                     break;
                 }
                 switch (ch) {
                     case ':':
                         p->scheme = htp_scheme_unknown;
                         switch (p->buf_idx) {
                             case 3:
                                 if (_str3_cmp(p->scheme_offset, 'f', 't', 'p', '\0')) {
                                     p->scheme = htp_scheme_ftp;
                                     break;
                                 }
                                 if (_str3_cmp(p->scheme_offset, 'n', 'f', 's', '\0')) {
                                     p->scheme = htp_scheme_nfs;
                                     break;
                                 }
                                 break;
                             case 4:
                                 if (_str4cmp(p->scheme_offset, 'h', 't', 't', 'p')) {
                                     p->scheme = htp_scheme_http;
                                     break;
                                 }
                                 break;
                             case 5:
                                 if (_str5cmp(p->scheme_offset, 'h', 't', 't', 'p', 's')) {
                                     p->scheme = htp_scheme_https;
                                     break;
                                 }
                                 break;
                         } /* switch */
                         res                  = hook_scheme_run(p, hooks, p->scheme_offset, (&p->buf[p->buf_idx] - p->scheme_offset));
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state             = s_schema_slash;
                         if (res) {
                             p->error = htparse_error_user;
                             return i + 1;
                         }
                         break;
                     default:
                         p->error = htparse_error_inval_schema;
                         return i + 1;
                 } /* switch */
                 break;
             case s_schema_slash:
                 htparse_log_debug("[%p] s_schema_slash", p);
                 switch (ch) {
                     case '/':
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state = s_schema_slash_slash;
                         break;
                     default:
                         p->error = htparse_error_inval_schema;
                         return i + 1;
                 }
                 break;
             case s_schema_slash_slash:
                 htparse_log_debug("[%p] s_schema_slash_slash", p);
                 switch (ch) {
                     case '/':
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->host_offset       = &p->buf[p->buf_idx];
                         p->state = s_host;
                         break;
                     default:
                         p->error = htparse_error_inval_schema;
                         return i + 1;
                 }
                 break;
             case s_host:
                 if (ch == '[') {
                     /* Literal IPv6 address start. */
                     p->buf[p->buf_idx++] = ch;
                     p->buf[p->buf_idx]   = '\0';
                     p->host_offset       = &p->buf[p->buf_idx];
                     p->state = s_host_ipv6;
                     break;
                 }
                 if (is_host_char(ch)) {
                     p->buf[p->buf_idx++] = ch;
                     p->buf[p->buf_idx]   = '\0';
                     break;
                 }
                 res = hook_host_run(p, hooks, p->host_offset, (&p->buf[p->buf_idx] - p->host_offset));
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
             /* successfully parsed a NON-IPV6 hostname, knowing this, the
              * current character in 'ch' is actually the next state, so we
              * we fall through to avoid another loop.
              */
             case s_host_done:
                 res = 0;
                 switch (ch) {
                     case ':':
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->port_offset       = &p->buf[p->buf_idx];
                         p->state = s_port;
                         break;
                     case ' ':
                         /* this technically should never happen, but we should
                          * check anyway
                          */
                         if (i == 0) {
                             p->error = htparse_error_inval_state;
                             return i + 1;
                         }
                         i--;
                         ch = '/';
                     /* to accept requests like <method> <proto>://<host> <ver>
                      * we fallthrough to the next case.
                      */
                     case '/':
                         p->path_offset       = &p->buf[p->buf_idx];
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state = s_after_slash_in_uri;
                         break;
                     default:
                         p->error = htparse_error_inval_schema;
                         return i + 1;
                 } /* switch */
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_host_ipv6:
                 c = (unsigned char)(ch | 0x20);
                 if ((c >= 'a' && c <= 'f') ||
                     (ch >= '0' && ch <= '9') || ch == ':' || ch == '.') {
                     p->buf[p->buf_idx++] = ch;
                     p->buf[p->buf_idx]   = '\0';
                     break;
                 }
                 switch (ch) {
                     case ']':
                         res = hook_host_run(p, hooks, p->host_offset,
                                             (&p->buf[p->buf_idx] - p->host_offset));
                         if (res) {
                             p->error = htparse_error_user;
                             return i + 1;
                         }
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state = s_host_done;
                         break;
                     default:
                         p->error = htparse_error_inval_schema;
                         return i + 1;
                 }
                 break;
             case s_port:
                 res = 0;
                 if (ch >= '0' && ch <= '9') {
                     p->buf[p->buf_idx++] = ch;
                     p->buf[p->buf_idx]   = '\0';
                     break;
                 }
                 res = hook_port_run(p, hooks, p->port_offset,
                                     (&p->buf[p->buf_idx] - p->port_offset));
                 switch (ch) {
                     case ' ':
                         /* this technically should never happen, but we should
                          * check anyway
                          */
                         if (i == 0) {
                             p->error = htparse_error_inval_state;
                             return i + 1;
                         }
                         i--;
                         ch = '/';
                     /* to accept requests like <method> <proto>://<host> <ver>
                      * we fallthrough to the next case.
                      */
                     case '/':
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->path_offset       = &p->buf[p->buf_idx - 1];
                         p->state = s_after_slash_in_uri;
                         break;
                     default:
                         p->error = htparse_error_inval_reqline;
                         return i + 1;
                 } /* switch */
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_after_slash_in_uri:
                 htparse_log_debug("[%p] s_after_slash_in_uri", p);
                 res = 0;
                 if (usual[ch >> 5] & (1 << (ch & 0x1f))) {
                     p->buf[p->buf_idx++] = ch;
                     p->buf[p->buf_idx]   = '\0';
                     p->state = s_check_uri;
                     break;
                 }
                 switch (ch) {
                     case ' ':
                     {
                         int r1 = hook_path_run(p, hooks, p->path_offset,
                                                (&p->buf[p->buf_idx] - p->path_offset));
                         int r2 = hook_uri_run(p, hooks, p->buf, p->buf_idx);
                         p->state   = s_http_09;
                         p->buf_idx = 0;
                         if (r1 || r2) {
                             res = 1;
                         }
                     }
                     break;
                     case CR:
                         p->minor = 9;
                         p->state = s_almost_done;
                         break;
                     case LF:
                         p->minor = 9;
                         p->state = s_hdrline_start;
                         break;
                     case '.':
                     case '%':
                     case '/':
                     case '#':
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state             = s_uri;
                         break;
                     case '?':
                         res                  = hook_path_run(p, hooks, p->path_offset,
                                                              (&p->buf[p->buf_idx] - p->path_offset));
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->args_offset       = &p->buf[p->buf_idx];
                         p->state             = s_uri;
                         break;
                     default:
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state             = s_check_uri;
                         break;
                 } /* switch */
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_check_uri:
                 res = 0;
                 do {
                     htparse_log_debug("[%p] s_check_uri", p);
                     if (usual[ch >> 5] & (1 << (ch & 0x1f))) {
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                     } else {
                         break;
                     }
                     ch = data[++i];
                 } while (i < len);
                 switch (ch) {
                     case ' ':
                     {
                         int r1 = 0;
                         int r2 = 0;
                         if (p->args_offset) {
                             r1 = hook_args_run(p, hooks, p->args_offset,
                                                (&p->buf[p->buf_idx] - p->args_offset));
                         } else {
                             r1 = hook_path_run(p, hooks, p->path_offset,
                                                (&p->buf[p->buf_idx] - p->path_offset));
                         }
                         r2         = hook_uri_run(p, hooks, p->buf, p->buf_idx);
                         p->buf_idx = 0;
                         p->state   = s_http_09;
                         if (r1 || r2) {
                             res = 1;
                         }
                     }
                     break;
                     case '/':
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state = s_after_slash_in_uri;
                         break;
                     case CR:
                         p->minor = 9;
                         p->buf_idx           = 0;
                         p->state = s_almost_done;
                         break;
                     case LF:
                         p->minor = 9;
                         p->buf_idx           = 0;
                         p->state             = s_hdrline_start;
                         break;
                     case '?':
                         res                  = hook_path_run(p, hooks, p->path_offset, (&p->buf[p->buf_idx] - p->path_offset));
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->args_offset       = &p->buf[p->buf_idx];
                         p->state             = s_uri;
                         break;
                     default:
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state             = s_uri;
                         break;
                 } /* switch */
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_uri:
                 htparse_log_debug("[%p] s_uri", p);
                 res = 0;
                 do {
                     if (usual[ch >> 5] & (1 << (ch & 0x1f))) {
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                     } else {
                         break;
                     }
                     ch = data[++i];
                 } while (i < len);
                 switch (ch) {
                     case ' ':
                     {
                         int r1 = 0;
                         int r2 = 0;
                         if (p->args_offset) {
                             r1 = hook_args_run(p, hooks, p->args_offset,
                                                (&p->buf[p->buf_idx] - p->args_offset));
                         } else {
                             r1 = hook_path_run(p, hooks, p->path_offset,
                                                (&p->buf[p->buf_idx] - p->path_offset));
                         }
                         p->buf_idx = 0;
                         p->state   = s_http_09;
                         if (r1 || r2) {
                             res = 1;
                         }
                     }
                     break;
                     case CR:
                         p->minor   = 9;
                         p->buf_idx = 0;
                         p->state   = s_almost_done;
                         break;
                     case LF:
                         p->minor   = 9;
                         p->buf_idx = 0;
                         p->state   = s_hdrline_start;
                         break;
                     case '?':
                         /* RFC 3986 section 3.4:
                          * The query component is indicated by the
                          * first question mark ("?") character and
                          * terminated by a number sign ("#") character
                          * or by the end of the URI. */
                         if (!p->args_offset) {
                             res = hook_path_run(p, hooks, p->path_offset,
                                                 (&p->buf[p->buf_idx] - p->path_offset));
                             p->buf[p->buf_idx++] = ch;
                             p->buf[p->buf_idx]   = '\0';
                             p->args_offset       = &p->buf[p->buf_idx];
                             break;
                         }
                     /* Fall through. */
                     default:
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         break;
                 } /* switch */
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_http_09:
                 htparse_log_debug("[%p] s_http_09", p);
                 switch (ch) {
                     case ' ':
                         break;
                     case CR:
                         p->minor   = 9;
                         p->buf_idx = 0;
                         p->state   = s_almost_done;
                         break;
                     case LF:
                         p->minor   = 9;
                         p->buf_idx = 0;
                         p->state   = s_hdrline_start;
                         break;
                     case 'H':
                         p->buf_idx = 0;
                         p->state   = s_http_H;
                         break;
                     default:
                         p->error   = htparse_error_inval_proto;
                         return i + 1;
                 } /* switch */
                 break;
             case s_http_H:
                 htparse_log_debug("[%p] s_http_H", p);
                 switch (ch) {
                     case 'T':
                         p->state = s_http_HT;
                         break;
                     default:
                         p->error = htparse_error_inval_proto;
                         return i + 1;
                 }
                 break;
             case s_http_HT:
                 switch (ch) {
                     case 'T':
                         p->state = s_http_HTT;
                         break;
                     default:
                         p->error = htparse_error_inval_proto;
                         return i + 1;
                 }
                 break;
             case s_http_HTT:
                 switch (ch) {
                     case 'P':
                         p->state = s_http_HTTP;
                         break;
                     default:
                         p->error = htparse_error_inval_proto;
                         return i + 1;
                 }
                 break;
             case s_http_HTTP:
                 switch (ch) {
                     case '/':
                         p->state = s_first_major_digit;
                         break;
                     default:
                         p->error = htparse_error_inval_proto;
                         return i + 1;
                 }
                 break;
             case s_first_major_digit:
                 if (ch < '1' || ch > '9') {
                     p->error = htparse_error_inval_ver;
                     return i + 1;
                 }
                 p->major = ch - '0';
                 p->state = s_major_digit;
                 break;
             case s_major_digit:
                 if (ch == '.') {
                     p->state = s_first_minor_digit;
                     break;
                 }
                 if (ch < '0' || ch > '9') {
                     p->error = htparse_error_inval_ver;
                     return i + 1;
                 }
                 p->major = p->major * 10 + ch - '0';
                 break;
             case s_first_minor_digit:
                 if (ch < '0' || ch > '9') {
                     p->error = htparse_error_inval_ver;
                     return i + 1;
                 }
                 p->minor = ch - '0';
                 p->state = s_minor_digit;
                 break;
             case s_minor_digit:
                 switch (ch) {
                     case ' ':
                         if (evhtp_likely(p->type == htp_type_request)) {
                             p->state = s_spaces_after_digit;
                         } else if (p->type == htp_type_response) {
                             p->state = s_status;
                         }
                         break;
                     case CR:
                         p->state = s_almost_done;
                         break;
                     case LF:
                         /* LF without a CR? error.... */
                         p->error = htparse_error_inval_reqline;
                         return i + 1;
                     default:
                         if (ch < '0' || ch > '9') {
                             p->error = htparse_error_inval_ver;
                             return i + 1;
                         }
                         p->minor = p->minor * 10 + ch - '0';
                         break;
                 } /* switch */
                 break;
             case s_status:
                 /* http response status code */
                 if (ch == ' ') {
                     if (p->status) {
                         p->state = s_status_text;
                     }
                     break;
                 }
                 if (ch < '0' || ch > '9') {
                     p->error = htparse_error_status;
                     return i + 1;
                 }
                 p->status = p->status * 10 + ch - '0';
                 if (++p->status_count == 3) {
                     p->state = s_space_after_status;
                 }
                 break;
             case s_space_after_status:
                 switch (ch) {
                     case ' ':
                         p->state = s_status_text;
                         break;
                     case CR:
                         p->state = s_almost_done;
                         break;
                     case LF:
                         p->state = s_hdrline_start;
                         break;
                     default:
                         p->error = htparse_error_generic;
                         return i + 1;
                 }
                 break;
             case s_status_text:
                 switch (ch) {
                     case CR:
                         p->state = s_almost_done;
                         break;
                     case LF:
                         p->state = s_hdrline_start;
                         break;
                     default:
                         break;
                 }
                 break;
             case s_spaces_after_digit:
                 switch (ch) {
                     case ' ':
                         break;
                     case CR:
                         p->state = s_almost_done;
                         break;
                     case LF:
                         p->state = s_hdrline_start;
                         break;
                     default:
                         p->error = htparse_error_inval_ver;
                         return i + 1;
                 }
                 break;
             case s_almost_done:
                 switch (ch) {
                     case LF:
                         if (p->type == htp_type_response && p->status >= 100 && p->status < 200) {
                             res = hook_on_hdrs_begin_run(p, hooks);
                             if (res) {
                                 p->error = htparse_error_user;
                                 return i + 1;
                             }
                             p->status       = 0;
                             p->status_count = 0;
                             p->state        = s_start;
                             break;
                         }
                         p->state = s_done;
                         res      = hook_on_hdrs_begin_run(p, hooks);
                         if (res) {
                             p->error = htparse_error_user;
                             return i + 1;
                         }
                         break;
                     default:
                         p->error = htparse_error_inval_reqline;
                         return i + 1;
                 } /* switch */
                 break;
             case s_done:
                 switch (ch) {
                     case CR:
                         p->state = s_hdrline_almost_done;
                         break;
                     case LF:
                         return i + 1;
                     default:
                         goto hdrline_start;
                 }
                 break;
 hdrline_start:
             case s_hdrline_start:
                 htparse_log_debug("[%p] s_hdrline_start", p);
                 p->buf_idx = 0;
                 switch (ch) {
                     case CR:
                         p->state             = s_hdrline_hdr_almost_done;
                         break;
                     case LF:
                         p->state             = s_hdrline_hdr_done;
                         break;
                     default:
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state             = s_hdrline_hdr_key;
                         break;
                 }
                 break;
             case s_hdrline_hdr_key:
                 htparse_log_debug("[%p] s_hdrline_hdr_key", p);
                 do {
                     if (evhtp_unlikely(ch == ':')) {
                         res      = hook_hdr_key_run(p, hooks, p->buf, p->buf_idx);
                         /* figure out if the value of this header is valueable */
                         p->heval = eval_hdr_val_none;
                         switch (p->buf_idx + 1) {
                             case 5:
                                 if (!strcasecmp(p->buf, "host")) {
                                     p->heval = eval_hdr_val_hostname;
                                 }
                                 break;
                             case 11:
                                 if (!strcasecmp(p->buf, "connection")) {
                                     p->heval = eval_hdr_val_connection;
                                 }
                                 break;
                             case 13:
                                 if (!strcasecmp(p->buf, "content-type")) {
                                     p->heval = eval_hdr_val_content_type;
                                 }
                                 break;
                             case 15:
                                 if (!strcasecmp(p->buf, "content-length")) {
                                     p->heval = eval_hdr_val_content_length;
                                 }
                                 break;
                             case 17:
                                 if (!strcasecmp(p->buf, "proxy-connection")) {
                                     p->heval = eval_hdr_val_proxy_connection;
                                 }
                                 break;
                             case 18:
                                 if (!strcasecmp(p->buf, "transfer-encoding")) {
                                     p->heval = eval_hdr_val_transfer_encoding;
                                 }
                                 break;
                         } /* switch */
                         p->buf_idx = 0;
                         p->state   = s_hdrline_hdr_space_before_val;
                         if (res) {
                             p->error = htparse_error_user;
                             return i + 1;
                         }
                         break;
                     }
                     switch (ch) {
                         case CR:
                             p->state             = s_hdrline_hdr_almost_done;
                             break;
                         case LF:
                             p->state             = s_hdrline_hdr_done;
                             break;
                         default:
                             p->buf[p->buf_idx++] = ch;
                             p->buf[p->buf_idx]   = '\0';
                             break;
                     }
                     if (p->state != s_hdrline_hdr_key) {
                         break;
                     }
                     ch = data[++i];
                 } while (i < len);
                 break;
             case s_hdrline_hdr_space_before_val:
                 htparse_log_debug("[%p] s_hdrline_hdr_space_before_val", p);
                 switch (ch) {
                     case ' ':
                         break;
                     case CR:
                         /*
                          * we have an empty header value here, so we set the buf
                          * to empty, set the state to hdrline_hdr_val, and
                          * decrement the start byte counter.
                          */
                         p->buf[p->buf_idx++] = ' ';
                         p->buf[p->buf_idx]   = '\0';
                         p->state = s_hdrline_hdr_val;
                         /*
                          * make sure the next pass comes back to this CR byte,
                          * so it matches in s_hdrline_hdr_val.
                          */
                         i--;
                         break;
                     case LF:
                         /* never got a CR for an empty header, this is an
                          * invalid state.
                          */
                         p->error             = htparse_error_inval_hdr;
                         return i + 1;
                     default:
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state             = s_hdrline_hdr_val;
                         break;
                 } /* switch */
                 break;
             case s_hdrline_hdr_val:
                 err = 0;
                 res = 0;
                 do {
                     htparse_log_debug("[%p] s_hdrline_hdr_val", p);
                     if (ch == CR) {
                         switch (p->heval) {
                             case eval_hdr_val_none:
                                 break;
                             case eval_hdr_val_hostname:
                                 if (hook_hostname_run(p, hooks, p->buf, p->buf_idx)) {
                                     p->state = s_hdrline_hdr_almost_done;
                                     p->error = htparse_error_user;
                                     return i + 1;
                                 }
                                 break;
                             case eval_hdr_val_content_length:
                                 p->content_len      = str_to_uint64(p->buf, p->buf_idx, &err);
                                 p->orig_content_len = p->content_len;
                                 htparse_log_debug("[%p] s_hdrline_hdr_val content-lenth = %zu", p, p->content_len);
                                 if (err == 1) {
                                     p->error = htparse_error_too_big;
                                     return i + 1;
                                 }
                                 break;
                             case eval_hdr_val_connection:
                                 switch (p->buf[0]) {
                                     char         A_case;
                                     char         C_case;
                                     const char * S_buf;
                                     case 'K':
                                     case 'k':
                                         if (p->buf_idx != 10) {
                                             break;
                                         }
                                         A_case = (p->buf[5] == 'A') ?  'A' : 'a';
                                         S_buf  = (const char *)(p->buf + 1);
                                         if (_str9cmp(S_buf,
                                                      'e', 'e', 'p', '-', A_case, 'l', 'i', 'v', 'e')) {
                                             p->flags |= parser_flag_connection_keep_alive;
                                         }
                                         break;
                                     case 'c':
                                     case 'C':
                                         if (p->buf_idx != 5) {
                                             break;
                                         }
                                         C_case = (p->buf[0] == 'C') ? 'C' : 'c';
                                         S_buf  = (const char *)p->buf;
                                         if (_str5cmp(S_buf, C_case, 'l', 'o', 's', 'e')) {
                                             p->flags |= parser_flag_connection_close;
                                         }
                                         break;
                                 } /* switch */
                                 break;
                             case eval_hdr_val_transfer_encoding:
                                 if (p->buf_idx != 7) {
                                     break;
                                 }
                                 switch (p->buf[0]) {
                                     const char * S_buf;
                                     case 'c':
                                     case 'C':
                                         if (p->buf_idx != 7) {
                                             break;
                                         }
                                         S_buf = (const char *)(p->buf + 1);
                                         if (_str6cmp(S_buf, 'h', 'u', 'n', 'k', 'e', 'd')) {
                                             p->flags |= parser_flag_chunked;
                                         }
                                         break;
                                 }
                                 break;
                             case eval_hdr_val_content_type:
                                 if (p->buf_idx != 9) {
                                     break;
                                 }
                                 switch (p->buf[0]) {
                                     const char * S_buf;
                                     case 'm':
                                     case 'M':
                                         S_buf = (const char *)(p->buf + 1);
                                         if (_str8cmp(S_buf, 'u', 'l', 't', 'i', 'p', 'a', 'r', 't')) {
                                             p->multipart = 1;
                                         }
                                         break;
                                 }
                                 break;
                             case eval_hdr_val_proxy_connection:
                             default:
                                 break;
                         } /* switch */
                         p->state = s_hdrline_hdr_almost_done;
                         break;
                     }
                     switch (ch) {
                         case LF:
                             /* LF before CR? invalid */
                             p->error             = htparse_error_inval_hdr;
                             return i + 1;
                         default:
                             p->buf[p->buf_idx++] = ch;
                             p->buf[p->buf_idx]   = '\0';
                             break;
                     } /* switch */
                     if (p->state != s_hdrline_hdr_val) {
                         break;
                     }
                     ch = data[++i];
                 } while (i < len);
                 break;
             case s_hdrline_hdr_almost_done:
                 htparse_log_debug("[%p] s_hdrline_hdr_almost_done", p);
                 res = 0;
                 switch (ch) {
                     case LF:
                         if (p->flags & parser_flag_trailing) {
                             res      = hook_on_msg_complete_run(p, hooks);
                             p->state = s_start;
                             break;
                         }
                         p->state = s_hdrline_hdr_done;
                         break;
                     default:
                         p->error = htparse_error_inval_hdr;
                         return i + 1;
                 }
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_hdrline_hdr_done:
                 htparse_log_debug("[%p] s_hdrline_hdr_done", p);
                 switch (ch) {
                     case CR:
                         res      = hook_hdr_val_run(p, hooks, p->buf, p->buf_idx);
                         p->state = s_hdrline_almost_done;
                         if (res) {
                             p->error = htparse_error_user;
                             return i + 1;
                         }
                         break;
                     case LF:
                         /* got LFLF? is this valid? */
                         p->error             = htparse_error_inval_hdr;
                         return i + 1;
                     case '\t':
                         /* this is a multiline header value, we must go back to
                          * reading as a header value */
                         p->state             = s_hdrline_hdr_val;
                         break;
                     default:
                         res                  = hook_hdr_val_run(p, hooks, p->buf, p->buf_idx);
                         p->buf_idx           = 0;
                         p->buf[p->buf_idx++] = ch;
                         p->buf[p->buf_idx]   = '\0';
                         p->state             = s_hdrline_hdr_key;
                         if (res) {
                             p->error = htparse_error_user;
                             return i + 1;
                         }
                         break;
                 }         /* switch */
                 break;
             case s_hdrline_almost_done:
                 htparse_log_debug("[%p] s_hdrline_almost_done", p);
                 res = 0;
                 switch (ch) {
                     case LF:
                         res = hook_on_hdrs_complete_run(p, hooks);
                         if (res) {
                             p->error = htparse_error_user;
                             return i + 1;
                         }
                         p->buf_idx = 0;
                         htparse_log_debug("[%p] HERE", p);
                         if (p->flags & parser_flag_trailing) {
                             res      = hook_on_msg_complete_run(p, hooks);
                             p->state = s_start;
                         } else if (p->flags & parser_flag_chunked) {
                             p->state = s_chunk_size_start;
                         } else if (p->content_len > 0) {
                             p->state = s_body_read;
                         } else if (p->content_len == 0) {
                             res      = hook_on_msg_complete_run(p, hooks);
                             p->state = s_start;
                         } else {
                             p->state = s_hdrline_done;
                         }
                         if (res) {
                             p->error = htparse_error_user;
                             return i + 1;
                         }
                         break;
                     default:
                         p->error = htparse_error_inval_hdr;
                         return i + 1;
                 }         /* switch */
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_hdrline_done:
                 htparse_log_debug("[%p] s_hdrline_done", p);
                 res = 0;
                 if (p->flags & parser_flag_trailing) {
                     res      = hook_on_msg_complete_run(p, hooks);
                     p->state = s_start;
                     break;
                 } else if (p->flags & parser_flag_chunked) {
                     p->state = s_chunk_size_start;
                     i--;
                 } else if (p->content_len > 0) {
                     p->state = s_body_read;
                     i--;
                 } else if (p->content_len == 0) {
                     res      = hook_on_msg_complete_run(p, hooks);
                     p->state = s_start;
                 }
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_chunk_size_start:
                 c = unhex[(unsigned char)ch];
                 if (c == -1) {
                     p->error = htparse_error_inval_chunk_sz;
                     return i + 1;
                 }
                 p->content_len = c;
                 p->state       = s_chunk_size;
                 break;
             case s_chunk_size:
                 if (ch == CR) {
                     p->state = s_chunk_size_almost_done;
                     break;
                 }
                 c = unhex[(unsigned char)ch];
                 if (c == -1) {
                     p->error = htparse_error_inval_chunk_sz;
                     return i + 1;
                 }
                 p->content_len *= 16;
                 p->content_len += c;
                 break;
             case s_chunk_size_almost_done:
                 res = 0;
                 if (ch != LF) {
                     p->error = htparse_error_inval_chunk_sz;
                     return i + 1;
                 }
                 p->orig_content_len = p->content_len;
                 if (p->content_len == 0) {
                     res       = hook_on_chunks_complete_run(p, hooks);
                     p->flags |= parser_flag_trailing;
                     p->state  = s_hdrline_start;
                 } else {
                     res      = hook_on_new_chunk_run(p, hooks);
                     p->state = s_chunk_data;
                 }
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_chunk_data:
                 res = 0;
                 {
                     const char * pp      = &data[i];
                     const char * pe      = (const char *)(data + len);
                     size_t       to_read = _MIN_READ(pe - pp, p->content_len);
                     if (to_read > 0) {
                         res = hook_body_run(p, hooks, pp, to_read);
                         i  += to_read - 1;
                     }
                     if (to_read == p->content_len) {
                         p->state = s_chunk_data_almost_done;
                     }
                     p->content_len -= to_read;
                 }
                 if (res) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_chunk_data_almost_done:
                 if (ch != CR) {
                     p->error = htparse_error_inval_chunk;
                     return i + 1;
                 }
                 p->state = s_chunk_data_done;
                 break;
             case s_chunk_data_done:
                 if (ch != LF) {
                     p->error = htparse_error_inval_chunk;
                     return i + 1;
                 }
                 p->orig_content_len = 0;
                 p->state = s_chunk_size_start;
                 if (hook_on_chunk_complete_run(p, hooks)) {
                     p->error = htparse_error_user;
                     return i + 1;
                 }
                 break;
             case s_body_read:
                 res = 0;
                 {
                     const char * pp      = &data[i];
                     const char * pe      = (const char *)(data + len);
                     size_t       to_read = _MIN_READ(pe - pp, p->content_len);
                     if (to_read > 0) {
                         res = hook_body_run(p, hooks, pp, to_read);
                         i  += to_read - 1;
                         p->content_len -= to_read;
                     }
                     if (p->content_len == 0) {
                         res      = hook_on_msg_complete_run(p, hooks);
                         p->state = s_start;
                     }
                     if (res) {
                         p->error = htparse_error_user;
                         return i + 1;
                     }
                 }
                 break;
             default:
                 htparse_log_debug("[%p] This is a silly state....", p);
                 p->error = htparse_error_inval_state;
                 return i + 1;
         } /* switch */
         /* If we successfully completed a request/response we return
          * to caller, and leave it up to him to call us again if
          * parsing should continue. */
         if (p->state == s_start) {
             return i + 1;
         }
     }     /* switch */
     return i;
 }         /* htparser_run */
EVHTP_EXPORT int htparser_should_keep_alive (htparser * p)
References parser_flag_connection_close, and parser_flag_connection_keep_alive.
Referenced by _evhtp_request_parser_headers().
{
     if (p->major > 0 && p->minor > 0) {
         if (p->flags & parser_flag_connection_close) {
             return 0;
         } else {
             return 1;
         }
     } else {
         if (p->flags & parser_flag_connection_keep_alive) {
             return 1;
         } else {
             return 0;
         }
     }
     return 0;
 }
EVHTP_EXPORT htp_scheme htparser_get_scheme (htparser *)
Referenced by _evhtp_request_parser_path().
{
     return p->scheme;
 }
EVHTP_EXPORT htp_method htparser_get_method (htparser *)
Referenced by _evhtp_request_parser_path(), _method(), and evhtp_request_get_method().
{
     return p->method;
 }
EVHTP_EXPORT const char* htparser_get_methodstr (htparser *)
References htparser_get_methodstr_m().
{
     return htparser_get_methodstr_m(p->method);
 }
EVHTP_EXPORT const char* htparser_get_methodstr_m (htp_method)
References htp_method_UNKNOWN.
Referenced by evhtp_make_request(), and htparser_get_methodstr().
{
     if (meth >= htp_method_UNKNOWN) {
         return NULL;
     }
     return method_strmap[meth];
 }
EVHTP_EXPORT void htparser_set_major (htparser * , unsigned char)
Referenced by _evhtp_create_reply().
{
     p->major = major;
 }
EVHTP_EXPORT void htparser_set_minor (htparser * , unsigned char)
Referenced by _evhtp_create_reply().
{
     p->minor = minor;
 }
EVHTP_EXPORT unsigned char htparser_get_major (htparser *)
Referenced by _evhtp_create_reply(), and _evhtp_request_parser_headers().
{
     return p->major;
 }
EVHTP_EXPORT unsigned char htparser_get_minor (htparser *)
Referenced by _evhtp_create_reply(), and _evhtp_request_parser_headers().
{
     return p->minor;
 }
EVHTP_EXPORT unsigned char htparser_get_multipart (htparser *)
Referenced by _evhtp_create_reply().
{
     return p->multipart;
 }
EVHTP_EXPORT unsigned int htparser_get_status (htparser *)
Referenced by evhtp_request_status().
{
     return p->status;
 }
EVHTP_EXPORT uint64_t htparser_get_content_length (htparser *)
Referenced by _evhtp_request_parser_chunk_new(), and _new_chunk().
{
     return p->orig_content_len;
 }
EVHTP_EXPORT uint64_t htparser_get_content_pending (htparser *)
{
     return p->content_len;
 }
EVHTP_EXPORT uint64_t htparser_get_total_bytes_read (htparser *)
{
     return p->total_bytes_read;
 }
EVHTP_EXPORT htpparse_error htparser_get_error (htparser *)
Referenced by _evhtp_connection_readcb(), and htparser_get_strerror().
{
     return p->error;
 }
EVHTP_EXPORT const char* htparser_get_strerror (htparser *)
References htparse_error_generic, and htparser_get_error().
Referenced by _run_test().
{
     htpparse_error e = htparser_get_error(p);
     if (e > htparse_error_generic) {
         return "htparse_no_such_error";
     }
     return errstr_map[e];
 }
EVHTP_EXPORT void* htparser_get_userdata (htparser *)
Referenced by _args(), _body(), _chunk_complete(), _chunks_complete(), _evhtp_request_parser_args(), _evhtp_request_parser_body(), _evhtp_request_parser_chunk_fini(), _evhtp_request_parser_chunk_new(), _evhtp_request_parser_chunks_fini(), _evhtp_request_parser_fini(), _evhtp_request_parser_header_key(), _evhtp_request_parser_header_val(), _evhtp_request_parser_headers(), _evhtp_request_parser_headers_start(), _evhtp_request_parser_host(), _evhtp_request_parser_hostname(), _evhtp_request_parser_path(), _evhtp_request_parser_port(), _evhtp_request_parser_start(), _hdr_key(), _hdr_val(), _hdrs_begin(), _hdrs_complete(), _host(), _hostname(), _method(), _msg_begin(), _msg_complete(), _new_chunk(), _path(), _port(), _scheme(), and _uri().
{
     return p->userdata;
 }
EVHTP_EXPORT void htparser_set_userdata (htparser * , void *)
Referenced by _evhtp_connection_new(), _evhtp_connection_writecb(), and _run_test().
{
     p->userdata = ud;
 }
EVHTP_EXPORT void htparser_init (htparser * , htp_type)
References htp_method_UNKNOWN, htparse_error_none, and s_start.
Referenced by _evhtp_connection_new(), _evhtp_connection_writecb(), and _run_test().
{
     /* Do not memset entire string buffer. */
     memset(p, 0, offsetof(htparser, buf));
     p->buf[0] = '\0';
     p->state  = s_start;
     p->error  = htparse_error_none;
     p->method = htp_method_UNKNOWN;
     p->type   = type;
 }
EVHTP_EXPORT htparser* htparser_new (void)
Referenced by _evhtp_connection_new(), and main().
                    {
     return malloc(sizeof(htparser));
 }