Libevhtp: examples/test_query.c File Reference
test_query.c File Reference
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "evhtp.h"
Macros
#define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]))
#define PARSE_QUERY_TEST(tests, flags)
Functions
static int test_cmp (evhtp_query_t *query, evhtp_kv_t *kvobj, const char *valstr, struct expected *exp)
int kvs_print (evhtp_kv_t *kvobj, void *arg)
static int query_test (const char *raw_query, int exp_error, struct expected exp[], int flags)
static void test (const char *raw_query, int exp_error, struct expected exp[], int flags)
int main (int argc, char **argv)
Variables
struct test base_tests []
struct test ignore_hex_tests []
struct test allow_empty_tests []
struct test allow_null_tests []
struct test treat_semicolon_as_sep_tests []
struct test lenient_tests []
Macro Definition Documentation
#define ARRAY_SIZE (arr) (sizeof(arr) / sizeof((arr)[0]))
#define PARSE_QUERY_TEST (tests, flags)
Value:
do {                                          \
            printf("- " # tests "\n");                                                   \
            for (i = 0; i < ARRAY_SIZE(tests); i++) {                                    \
                test((tests)[i].raw_query, (tests)[i].exp_error, (tests)[i].exp, flags); \
            }                                                                            \
    } while (0)
Referenced by main().
Function Documentation
static int test_cmp (evhtp_query_t * query, evhtp_kv_t * kvobj, const char * valstr, struct expected * exp) static
Referenced by query_test().
{
     if (!query || !kvobj) {
         return -1;
     }
     if (exp->val == NULL) {
         if (kvobj->val || valstr) {
             return -1;
         }
         return 0;
     }
     if (strcmp(kvobj->val, exp->val)) {
         printf("\n");
         printf("    expected: '%s'\n", exp->val);
         printf("    actual:   '%s'\n", kvobj->val);
         return -1;
     }
     if (strcmp(valstr, exp->val)) {
         return -1;
     }
     return 0;
 }
int kvs_print (evhtp_kv_t * kvobj, void * arg)
Referenced by query_test().
{
     int * key_idx = arg;
     if (*key_idx) {
         printf(", ");
     }
     printf("\"%s\": %s%s%s", kvobj->key,
            kvobj->val ? "\"" : "",
            kvobj->val,
            kvobj->val ? "\"" : "");
     *key_idx += 1;
     return 0;
 }
static int query_test (const char * raw_query, int exp_error, struct expected exp[], int flags) static
References evhtp_kv_find(), evhtp_kvs_find_kv(), evhtp_kvs_for_each(), evhtp_parse_query_wflags(), evhtp_query_t, kvs_print(), and test_cmp().
Referenced by test().
{
     evhtp_query_t   * query;
     struct expected * check;
     int               key_idx    = 0;
     int               idx        = 0;
     int               num_errors = 0;
     /* print whether error is expected or not */
     printf("%-7s  ", exp_error ? "(error)" : "");
     query = evhtp_parse_query_wflags(raw_query, strlen(raw_query), flags);
     if (!query) {
         printf("<error>");
         return exp_error == 0;
     }
     printf("{");
     evhtp_kvs_for_each(query, kvs_print, &key_idx);
     /* TODO check for keys in query but not in exp */
     printf("}");
     while (1) {
         evhtp_kv_t * kvobj  = NULL;
         const char * valstr = NULL;
         check = &exp[idx++];
         if (check == NULL || check->key == NULL) {
             break;
         }
         kvobj  = evhtp_kvs_find_kv(query, check->key);
         valstr = evhtp_kv_find(query, check->key);
         if (test_cmp(query, kvobj, valstr, check) == -1) {
             num_errors += 1;
             printf("         ");
         }
     }
     if (exp_error) {
         return -1;
     }
     return num_errors;
 } /* query_test */
static void test (const char * raw_query, int exp_error, struct expected exp[], int flags) static
References query_test().
{
     printf("         %-30s  ", raw_query);
     printf("\r  %s\n", query_test(raw_query, exp_error, exp, flags) ? "ERROR" : "OK");
 }
int main (int argc, char ** argv)
References EVHTP_PARSE_QUERY_FLAG_ALLOW_EMPTY_VALS, EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS, EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX, EVHTP_PARSE_QUERY_FLAG_LENIENT, EVHTP_PARSE_QUERY_FLAG_STRICT, EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP, and PARSE_QUERY_TEST.
{
     int i;
     #define PARSE_QUERY_TEST(tests, flags) do {                                          \
             printf("- " # tests "\n");                                                   \
             for (i = 0; i < ARRAY_SIZE(tests); i++) {                                    \
                 test((tests)[i].raw_query, (tests)[i].exp_error, (tests)[i].exp, flags); \
             }                                                                            \
     } while (0)
     PARSE_QUERY_TEST(base_tests, EVHTP_PARSE_QUERY_FLAG_STRICT);
     PARSE_QUERY_TEST(ignore_hex_tests, EVHTP_PARSE_QUERY_FLAG_IGNORE_HEX);
     PARSE_QUERY_TEST(allow_empty_tests, EVHTP_PARSE_QUERY_FLAG_ALLOW_EMPTY_VALS);
     PARSE_QUERY_TEST(allow_null_tests, EVHTP_PARSE_QUERY_FLAG_ALLOW_NULL_VALS);
     PARSE_QUERY_TEST(treat_semicolon_as_sep_tests, EVHTP_PARSE_QUERY_FLAG_TREAT_SEMICOLON_AS_SEP);
     PARSE_QUERY_TEST(lenient_tests, EVHTP_PARSE_QUERY_FLAG_LENIENT);
     return 0;
 }
Variable Documentation
struct test base_tests[]
struct test ignore_hex_tests[]
Initial value:
= {
    { "hexa=some%20&hexb=bla%0&hexc=%", 0, {
                { "hexa",                           "some%20" },
                { "hexb",                           "bla%0" },
                { "hexc",                           "%" },
                { NULL,                             NULL },
            } },
    { "hexa%z=some",                    0, {
                { "hexa%z",                         "some" },
                { NULL,                             NULL },
            } },
    { "aaa=some%zz",                    0, {
                { "aaa",                            "some%zz" },
                { NULL,                             NULL },
            } },
}
struct test allow_empty_tests[]
Initial value:
= {
    { "end_empty_string=", 0, {
                { "end_empty_string",  "" },
                { NULL,                NULL },
            } },
}
struct test allow_null_tests[]
Initial value:
= {
    { "end_null", 0, {
                { "end_null", NULL },
                { NULL,       NULL },
            } },
}
struct test treat_semicolon_as_sep_tests[]
Initial value:
= {
    { "a=b;key=val", 0, {
                { "a",           "b" },
                { "key",         "val" },
                { NULL,          NULL },
            } },
    { "a;b=val",     1 },
}
struct test lenient_tests[]
Initial value:
= {
    { "a=b;key&c=val",                    0, {
                { "a",                                "b" },
                { "key",                              NULL },
                { "c",                                "val" },
                { NULL,                               NULL },
            } },
    { "a=b;key=val",                      0, {
                { "a",                                "b" },
                { "key",                              "val" },
                { NULL,                               NULL },
            } },
    { "end_empty_string=",                0, {
                { "end_empty_string",                 "" },
                { NULL,                               NULL },
            } },
    { "end_null",                         0, {
                { "end_null",                         NULL },
                { NULL,                               NULL },
            } },
    { "hexa=some\%a;hexb=bl%0&hexc=\%az", 0, {
                { "hexa",                             "some\%a" },
                { "hexb",                             "bl%0" },
                { "hexc",                             "\%az" },
                { NULL,                               NULL },
            } },
}