Libevhtp: examples/thread_design.c File Reference
thread_design.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <errno.h>
#include <evhtp.h>
#include <hiredis/hiredis.h>
#include <hiredis/async.h>
#include <hiredis/adapters/libevent.h>
Functions
static evthr_t * get_request_thr (evhtp_request_t *request)
void redis_global_incr_cb (redisAsyncContext *redis, void *redis_reply, void *arg)
void redis_srcaddr_incr_cb (redisAsyncContext *redis, void *redis_reply, void *arg)
void redis_set_srcport_cb (redisAsyncContext *redis, void *redis_reply, void *arg)
void redis_get_srcport_cb (redisAsyncContext *redis, void *redis_reply, void *arg)
void app_process_request (evhtp_request_t *request, void *arg)
void app_init_thread (evhtp_t *htp, evthr_t *thread, void *arg)
int main (int argc, char **argv)
Function Documentation
static evthr_t* get_request_thr (evhtp_request_t * request) static
References evhtp_request_get_connection().
Referenced by app_process_request().
{
     evhtp_connection_t * htpconn;
     evthr_t            * thread;
     htpconn = evhtp_request_get_connection(request);
     thread  = htpconn->thread;
     return thread;
 }
void redis_global_incr_cb (redisAsyncContext * redis, void * redis_reply, void * arg)
Referenced by app_process_request().
{
     redisReply      * reply   = redis_reply;
     evhtp_request_t * request = arg;
     printf("global_incr_cb(%p)\n", request);
     if (reply == NULL || reply->type != REDIS_REPLY_INTEGER) {
         evbuffer_add_printf(request->buffer_out,
                             "redis_global_incr_cb() failed\n");
         return;
     }
     evbuffer_add_printf(request->buffer_out,
                         "Total requests = %lld\n", reply->integer);
 }
void redis_srcaddr_incr_cb (redisAsyncContext * redis, void * redis_reply, void * arg)
Referenced by app_process_request().
{
     redisReply      * reply   = redis_reply;
     evhtp_request_t * request = arg;
     printf("incr_cb(%p)\n", request);
     if (reply == NULL || reply->type != REDIS_REPLY_INTEGER) {
         evbuffer_add_printf(request->buffer_out,
                             "redis_srcaddr_incr_cb() failed\n");
         return;
     }
     evbuffer_add_printf(request->buffer_out,
                         "Requests from this source IP = %lld\n", reply->integer);
 }
void redis_set_srcport_cb (redisAsyncContext * redis, void * redis_reply, void * arg)
Referenced by app_process_request().
{
     redisReply      * reply   = redis_reply;
     evhtp_request_t * request = arg;
     printf("set_srcport_cb(%p)\n", request);
     if (reply == NULL || reply->type != REDIS_REPLY_INTEGER) {
         evbuffer_add_printf(request->buffer_out,
                             "redis_set_srcport_cb() failed\n");
         return;
     }
     if (!reply->integer) {
         evbuffer_add_printf(request->buffer_out,
                             "This source port has been seen already.\n");
     } else {
         evbuffer_add_printf(request->buffer_out,
                             "This source port has never been seen.\n");
     }
 }
void redis_get_srcport_cb (redisAsyncContext * redis, void * redis_reply, void * arg)
References evhtp_request_resume(), EVHTP_RES_OK, and evhtp_send_reply().
Referenced by app_process_request().
{
     redisReply      * reply   = redis_reply;
     evhtp_request_t * request = arg;
     int               i;
     printf("get_srcport_cb(%p)\n", request);
     if (reply == NULL || reply->type != REDIS_REPLY_ARRAY) {
         evbuffer_add_printf(request->buffer_out,
                             "redis_get_srcport_cb() failed.\n");
         return;
     }
     evbuffer_add_printf(request->buffer_out,
                         "source ports which have been seen for your ip:\n");
     for (i = 0; i < reply->elements; i++) {
         redisReply * elem = reply->element[i];
         evbuffer_add_printf(request->buffer_out, "%s ", elem->str);
     }
     evbuffer_add(request->buffer_out, "\n", 1);
     /* final callback for redis, so send the response */
     evhtp_send_reply(request, EVHTP_RES_OK);
     evhtp_request_resume(request);
 }
void app_process_request (evhtp_request_t * request, void * arg)
References evhtp_request_get_connection(), evhtp_request_pause(), evthr_get_aux(), get_request_thr(), redis_get_srcport_cb(), redis_global_incr_cb(), redis_set_srcport_cb(), and redis_srcaddr_incr_cb().
Referenced by main().
{
     struct sockaddr_in * sin;
     struct app_parent  * app_parent;
     struct app         * app;
     evthr_t            * thread;
     evhtp_connection_t * conn;
     char                 tmp[1024];
     printf("process_request(%p)\n", request);
     thread = get_request_thr(request);
     conn   = evhtp_request_get_connection(request);
     app    = (struct app *)evthr_get_aux(thread);
     sin    = (struct sockaddr_in *)conn->saddr;
     evutil_inet_ntop(AF_INET, &sin->sin_addr, tmp, sizeof(tmp));
     /* increment a global counter of hits on redis */
     redisAsyncCommand(app->redis, redis_global_incr_cb,
                       (void *)request, "INCR requests:total");
     /* increment a counter for hits from this source address on redis */
     redisAsyncCommand(app->redis, redis_srcaddr_incr_cb,
                       (void *)request, "INCR requests:ip:%s", tmp);
     /* add the source port of this request to a source-specific set */
     redisAsyncCommand(app->redis, redis_set_srcport_cb, (void *)request,
                       "SADD requests:ip:%s:ports %d", tmp, ntohs(sin->sin_port));
     /* get all of the ports this source address has used */
     redisAsyncCommand(app->redis, redis_get_srcport_cb, (void *)request,
                       "SMEMBERS requests:ip:%s:ports", tmp);
     /* pause the request processing */
     evhtp_request_pause(request);
 }
void app_init_thread (evhtp_t * htp, evthr_t * thread, void * arg)
References evthr_get_base(), and evthr_set_aux().
Referenced by main().
{
     struct app_parent * app_parent;
     struct app        * app;
     app_parent  = (struct app_parent *)arg;
     app         = calloc(sizeof(struct app), 1);
     app->parent = app_parent;
     app->evbase = evthr_get_base(thread);
     app->redis  = redisAsyncConnect(app_parent->redis_host, app_parent->redis_port);
     redisLibeventAttach(app->redis, app->evbase);
     evthr_set_aux(thread, app);
 }
int main (int argc, char ** argv)
References app_init_thread(), app_process_request(), evhtp_bind_socket(), evhtp_new(), evhtp_set_gencb(), and evhtp_use_threads().
{
     evbase_t          * evbase;
     evhtp_t           * evhtp;
     struct app_parent * app_p;
     evbase            = event_base_new();
     evhtp             = evhtp_new(evbase, NULL);
     app_p             = calloc(sizeof(struct app_parent), 1);
     app_p->evhtp      = evhtp;
     app_p->evbase     = evbase;
     app_p->redis_host = "127.0.0.1";
     app_p->redis_port = 6379;
     evhtp_set_gencb(evhtp, app_process_request, NULL);
     evhtp_use_threads(evhtp, app_init_thread, 4, app_p);
     evhtp_bind_socket(evhtp, "127.0.0.1", 9090, 1024);
     event_base_loop(evbase, 0);
     return 0;
 }